In [1]:
import mysql.connector
import pandas as pd
import numpy as np

In [2]:
db = mysql.connector.connect(host="localhost",user="root", passwd="xiaoji", database="NYC_airbnb", charset='utf8' )

In [3]:
mycursor=db.cursor()

In [4]:
mycursor.execute("SHOW DATABASES")

for x in mycursor:
    print(x)

('information_schema',)
('mysql',)
('nyc_airbnb',)
('performance_schema',)
('sys',)
('university',)

In [5]:
mycursor.execute("show tables")

for x in mycursor:
    print(x)

('host',)
('house',)
('locate',)
('position',)
('possess',)

In [6]:
mycursor.execute("select * from host")

for x in mycursor:
    print(x)

In [7]:
mycursor.execute("select * from house;")

for x in mycursor:
    print(x)

In [37]:
df=pd.read_csv("AB_NYC_2019.csv")
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

In [38]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.889500e+04,4.889500e+04,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,38843.000000,48895.000000,48895.000000
mean,1.901714e+07,6.762001e+07,40.728949,-73.952170,152.720687,7.029962,23.274466,1.373221,7.143982,112.781327
std,1.098311e+07,7.861097e+07,0.054530,0.046157,240.154170,20.510550,44.550582,1.680442,32.952519,131.622289
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.471945e+06,7.822033e+06,40.690100,-73.983070,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967728e+07,3.079382e+07,40.723070,-73.955680,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915218e+07,1.074344e+08,40.763115,-73.936275,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [40]:
df=df.fillna(0)

In [41]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,0,0.00,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [ ]:
#Use MySql Workbench to create tables
CREATE TABLE `host` (
  `host_id` int(11) NOT NULL,
  `host_name` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`host_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `house` (
  `id` int(10) unsigned zerofill NOT NULL,
  `name` varchar(200) DEFAULT NULL,
  `latitude` float DEFAULT NULL,
  `longitude` float DEFAULT NULL,
  `room_type` varchar(200) DEFAULT NULL,
  `price` varchar(200) DEFAULT NULL,
  `minimum_nights` int(11) DEFAULT NULL,
  `number_of_reviews` int(11) DEFAULT NULL,
  `last_review` varchar(45) DEFAULT NULL,
  `reviews_per_month` float DEFAULT NULL,
  `calculated_host_listings_count` int(11) DEFAULT NULL,
  `availability_365` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `locate` (
  `id` int(11) NOT NULL,
  `neighbourhood` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `position` (
  `neighbourhood` varchar(200) NOT NULL,
  `neighbourhood_group` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`neighbourhood`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `possess` (
  `id` int(11) NOT NULL,
  `host_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

In [42]:
#Delete the "'"s to make it more easier to create sql commands.
#We can also use '' to replace ' sy
for index,row in df.iterrows():
    a=str(row['name']).split('\'')
    df['name'][index]=' '.join(a)
    b=str(row['neighbourhood']).split('\'')
    df['neighbourhood'][index]=' '.join(b)

c:\users\13121\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
c:\users\13121\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [27]:
mycursor.execute("show tables")

for x in mycursor:
    print(x)

('host',)
('house',)
('locate',)
('position',)
('possess',)

In [73]:
#Because the performance of importing data from csv using MySql Workbench is poor as a few seconds for one piece, I changed to u
#A simplified try with the data size set to 500
#table house
for i in range(500):
    sql="insert into house(id,name,latitude,longitude,room_type,price,\
    minimum_nights,number_of_reviews,last_review,reviews_per_month,\
    calculated_host_listings_count,availability_365) \
    values ("+str(df["id"][i])+",\'"+str(df["name"][i])+"\',"+str(df["latitude"][i])+"," \
    +str(df["longitude"][i])+",\'"+str(df["room_type"][i])+"\',"+str(df["price"][i])+","+ \
    str(df["minimum_nights"][i])+","+str(df["number_of_reviews"][i])+",\'"+str(df["last_review"][i])+"\',"+ \
    str(df["reviews_per_month"][i])+","+str(df["calculated_host_listings_count"][i])+","+str(df["availability_365"][i])+")"

    print(sql)
    mycursor.execute(sql)

    db.commit()

insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (2539,'Clean & quiet apt home by the park',40.647490000000005,-73.97237,'Private room',149,1,9,'2018-10-19',0.21,6,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (2595,'Skylit Midtown Castle',40.75362,-73.98376999999999,'Entire home/apt',225,1,45,'2019-05-21',0.38,2,355)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (3647,'THE VILLAGE OF HARLEM....NEW YORK !',40.809020000000004,-73.9419,'Private room',150,3,0,'0',0.0,1,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (3831,'Cozy Entire Floor of Brownstone',40.685140000000004,-73.95976,'Entire home/apt',89,1,270,'2019-07-05',4.64,1,194)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (5022,'Entire Apt: Spacious Studio/Loft by central park',40.79851,-73.94399,'Entire home/apt',80,10,9,'2018-11-19',0.1,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (5099,'Large Cozy 1 BR Apartment In Midtown East',40.74767,-73.975,'Entire home/apt',200,3,74,'2019-06-22',0.59,1,129)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (5121,'BlissArtsSpace!',40.68688,-73.95596,'Private room',60,45,49,'2017-10-05',0.4,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (5178,'Large Furnished Room Near B way ',40.76489,-73.98493,'Private room',79,2,430,'2019-06-24',3.47,1,220)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (5203,'Cozy Clean Guest Room - Family Apt',40.80178,-73.96723,'Private room',79,2,118,'2017-07-21',0.99,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (5238,'Cute & Cozy Lower East Side 1 bdrm',40.713440000000006,-73.99037,'Entire home/apt',150,1,160,'2019-06-09',1.33,4,188)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (5295,'Beautiful 1br on Upper West Side',40.80316,-73.96545,'Entire home/apt',135,5,53,'2019-06-22',0.43,1,6)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (5441,'Central Manhattan/near Broadway',40.76076,-73.98867,'Private room',85,2,188,'2019-06-23',1.5,1,39)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (5803,'Lovely Room 1, Garden, Best Area, Legal rental',40.66829,-73.98779,'Private room',89,4,167,'2019-06-24',1.34,3,314)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (6021,'Wonderful Guest Bedroom in Manhattan for SINGLES',40.79826,-73.96113000000001,'Private room',85,2,113,'2019-07-05',0.91,1,333)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (6090,'West Village Nest - Superhost',40.7353,-74.00525,'Entire home/apt',120,90,27,'2018-10-31',0.22,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (6848,'Only 2 stops to Manhattan studio',40.70837,-73.95352,'Entire home/apt',140,2,148,'2019-06-29',1.2,1,46)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (7097,'Perfect for Your Parents + Garden',40.69169,-73.97185,'Entire home/apt',215,2,198,'2019-06-28',1.72,1,321)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (7322,'Chelsea Perfect',40.74192,-73.99501,'Private room',140,1,260,'2019-07-01',2.12,1,12)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (7726,'Hip Historic Brownstone Apartment with Backyard',40.67592,-73.94694,'Entire home/apt',99,3,53,'2019-06-22',4.44,1,21)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (7750,'Huge 2 BR Upper East  Cental Park',40.79685,-73.94872,'Entire home/apt',190,7,0,'0',0.0,2,249)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (7801,'Sweet and Spacious Brooklyn Loft',40.71842,-73.95718000000001,'Entire home/apt',299,3,9,'2011-12-28',0.07,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (8024,'CBG CtyBGd HelpsHaiti rm#1:1-4',40.680690000000006,-73.97706,'Private room',130,2,130,'2019-07-01',1.09,6,347)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (8025,'CBG Helps Haiti Room#2.5',40.67989,-73.97798,'Private room',80,1,39,'2019-01-01',0.37,6,364)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (8110,'CBG Helps Haiti Rm #2',40.680009999999996,-73.97865,'Private room',110,2,71,'2019-07-02',0.61,6,304)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (8490,'MAISON DES SIRENES1,bohemian apartment',40.68371,-73.94028,'Entire home/apt',120,2,88,'2019-06-19',0.73,2,233)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (8505,'Sunny Bedroom Across Prospect Park',40.65599,-73.97519,'Private room',60,1,19,'2019-06-23',1.37,2,85)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (8700,'Magnifique Suite au N de Manhattan - vue Cloitres',40.867540000000005,-73.92639,'Private room',80,4,0,'0',0.0,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (9357,'Midtown Pied-a-terre',40.76715,-73.98533,'Entire home/apt',150,10,58,'2017-08-13',0.49,1,75)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (9518,'SPACIOUS, LOVELY FURNISHED MANHATTAN BEDROOM',40.86482,-73.92106,'Private room',44,3,108,'2019-06-15',1.11,3,311)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (9657,'Modern 1 BR / NYC / EAST VILLAGE',40.7292,-73.98541999999999,'Entire home/apt',180,14,29,'2019-04-19',0.24,1,67)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (9668,'front room/double bed',40.82245,-73.95104,'Private room',50,3,242,'2019-06-01',2.04,3,355)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (9704,'Spacious 1 bedroom in luxe building',40.81305,-73.95466,'Private room',52,2,88,'2019-06-14',1.42,1,255)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (9782,'Loft in Williamsburg Area w/ Roof',40.722190000000005,-73.93762,'Private room',55,4,197,'2019-06-15',1.65,3,284)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (9783,'back room/bunk beds',40.8213,-73.95318,'Private room',50,3,273,'2019-07-01',2.37,3,359)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (10452,'Large B&B Style rooms',40.6831,-73.95473,'Private room',70,1,74,'2019-05-12',0.66,2,269)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (10962,'Lovely room 2 & garden; Best area, Legal rental',40.668690000000005,-73.9878,'Private room',89,4,168,'2019-06-21',1.41,3,340)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (11452,'Clean and Quiet in Brooklyn',40.688759999999995,-73.94312,'Private room',35,60,0,'0',0.0,1,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (11708,'Cute apt in artist s home',40.701859999999996,-73.92745,'Entire home/apt',85,2,231,'2019-06-22',1.96,2,22)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (11943,'Country space in the city',40.63702,-73.96327,'Private room',150,1,0,'0',0.0,1,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (12048,'LowerEastSide apt share shortterm 1',40.714009999999995,-73.98917,'Shared room',40,1,214,'2019-07-05',1.81,4,188)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (12192,'ENJOY Downtown NYC!',40.7229,-73.98199,'Private room',68,2,245,'2019-06-21',2.08,2,96)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (12299,'Beautiful Sunny Park Slope Brooklyn',40.66278,-73.97966,'Entire home/apt',120,3,15,'2019-05-27',0.39,1,345)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (12303,'1bdr w private bath. in lofty apt',40.69673,-73.97584,'Private room',120,7,25,'2018-09-30',0.23,1,311)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (12318,'West Side Retreat',40.79009,-73.97927,'Private room',135,4,81,'2019-06-16',0.69,1,273)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (12343,'BEST BET IN HARLEM',40.81175,-73.94478000000001,'Entire home/apt',150,7,97,'2019-06-13',0.84,1,309)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (12627,'Entire apartment in central Brooklyn neighborhood.',40.659440000000004,-73.96238000000001,'Entire home/apt',150,29,11,'2019-06-05',0.49,1,95)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (12937,'1 Stop fr. Manhattan! Private Suite,Landmark Block',40.74771,-73.9474,'Private room',130,3,248,'2019-07-01',2.25,1,215)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (12940,'Charming Brownstone 3 - Near PRATT',40.68111,-73.95591,'Entire home/apt',110,7,61,'2019-05-25',0.52,1,265)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (13050,'bright and stylish duplex',40.68554,-73.9409,'Entire home/apt',115,3,11,'2017-01-01',0.1,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (13394,'Fort Greene brownstone ',40.69142,-73.97376,'Private room',80,3,135,'2019-06-17',1.16,2,192)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (13808,'Blue Room for 2 in Brownstone for $1350 monthly',40.68043,-73.93934,'Private room',80,1,112,'2019-06-16',1.01,3,251)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (14287,'Cozy 1BD on Central Park West in New York City',40.78635,-73.97008000000001,'Entire home/apt',151,2,73,'2019-07-07',0.63,1,302)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (14290,'* ORIGINAL BROOKLYN LOFT *',40.7042,-73.9356,'Entire home/apt',228,3,82,'2019-05-17',0.7,1,140)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (14314,'Greenpoint Place...Has It All! ',40.73506,-73.95392,'Entire home/apt',144,2,328,'2019-06-29',2.82,1,234)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (14322,'Beautiful Apartment in Manhattan!!!',40.73961,-73.98074,'Entire home/apt',200,7,19,'2019-03-25',0.22,1,257)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (14377,'Williamsburg 1 bedroom Apartment',40.70881,-73.9593,'Entire home/apt',150,30,105,'2019-06-22',0.9,1,30)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (14991,'Great Location, Manhattan Bedroom!',40.720040000000004,-73.99104,'Private room',110,5,19,'2019-05-18',0.17,1,301)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (15220,'Best Location in NYC! TIMES SQUARE!',40.755309999999994,-73.99293,'Private room',69,2,289,'2019-06-09',2.49,2,294)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (15338,'Room in Greenpoint Loft w/ Roof',40.72401,-73.93788,'Private room',49,4,138,'2019-06-04',1.19,3,320)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (15341,'**Bright Nolita Apt w Doorman/Elevators/Gym**',40.7221,-73.99775,'Entire home/apt',180,30,21,'2019-06-29',0.3,1,154)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (15385,'Very, very cozy place',40.71185,-73.96204,'Private room',80,2,42,'2019-06-30',0.38,1,263)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (15396,'Sunny & Spacious Chelsea Apartment',40.74623,-73.9953,'Entire home/apt',375,180,5,'2018-11-03',0.12,1,180)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (15711,'2 bedroom - Upper East Side-great for kids',40.77065,-73.95269,'Entire home/apt',250,2,66,'2019-03-30',0.57,2,231)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (16326,'Comfortable 4-bedroom apt in family house.',40.67811,-73.96428,'Entire home/apt',200,30,143,'2019-01-26',1.33,2,297)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (16338,'Double Room w Private Deck Clinton Hill Best Area',40.69,-73.96788000000001,'Private room',55,7,27,'2017-09-30',0.23,2,292)

insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (26012,'Sunny 2-story Brooklyn townhouse w deck and garden',40.68157,-73.98989,'Entire home/apt',200,30,19,'2017-03-17',0.2,1,208)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (26362,'Times Square, Safe, Clean and Cozy!',40.75527,-73.99291,'Private room',59,2,334,'2019-06-16',3.0,2,279)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (26520,'Cozy Room #3, Landmark Home 1 Block to PRATT',40.68698,-73.96571999999999,'Private room',125,2,19,'2019-06-02',0.2,6,250)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (26559,'Beautiful Apartment East Village',40.7288,-73.98192,'Entire home/apt',140,7,12,'2017-12-11',0.13,1,164)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (26785,'Park Slope Green Guest House',40.66853,-73.98912,'Entire home/apt',120,30,467,'2018-12-30',4.22,2,192)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (26933,'2 BR / 2 Bath Duplex Apt with patio! East Village',40.7254,-73.98156999999999,'Entire home/apt',350,2,7,'2017-08-09',0.06,4,298)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (26954,'NYC fabulous views Manhattan s eye',40.742940000000004,-73.98009,'Entire home/apt',199,5,38,'2015-12-02',0.38,1,260)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (26969,'2 story family home in Williamsburg',40.71942,-73.95748,'Entire home/apt',325,3,324,'2019-06-23',3.01,1,107)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (27006,'Comfortable UWS 2-BD Family-Friendly Brownstone',40.77823,-73.97636999999999,'Entire home/apt',235,6,27,'2019-04-27',0.27,1,199)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (27385,'Great Large 1 BR apt  in East Village!',40.72555,-73.97965,'Entire home/apt',225,1,115,'2019-06-07',1.05,4,299)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (27531,'Eveland Private Bed & Living Room w/ Own Entrance',40.66831,-73.98604,'Private room',99,2,354,'2019-05-20',3.2,3,20)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (27644,'Sugar Hill Rest Stop ',40.82754,-73.94919,'Entire home/apt',170,2,195,'2019-07-01',2.03,1,318)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (27659,'3 Story Town House in Park Slope',40.66499,-73.97925,'Entire home/apt',400,2,16,'2018-12-30',0.24,2,216)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (27759,'apartment next to Central park',40.778420000000004,-73.97556,'Entire home/apt',170,7,13,'2019-06-26',0.12,1,224)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (27883,'East Village Sanctuary',40.72245,-73.98527,'Entire home/apt',100,4,25,'2011-12-10',0.23,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (28321,'Large 1  BR in a 3 BR Brooklyn apt. next to Q Trn.',40.65593,-73.96053,'Private room',75,2,9,'2018-10-05',0.08,1,324)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (28396,'Modern Apt with Spectacular Views',40.719229999999996,-73.96468,'Private room',90,1,9,'2011-09-18',0.08,1,245)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (28907,'Garden studio in the Upper East Sid',40.778,-73.94821999999999,'Entire home/apt',150,5,21,'2017-08-15',0.19,1,189)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (29012,'Secluded Master Bedroom in Beautiful Huge Apt',40.85879,-73.93128,'Private room',85,15,36,'2017-08-17',0.33,1,307)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (29013,'B & B Room 1',40.68332,-73.9547,'Private room',70,3,63,'2019-05-14',0.58,2,310)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (29455,'ACCOMMODATIONS GALORE #1',40.816179999999996,-73.94894000000001,'Entire home/apt',120,3,155,'2019-06-20',1.42,3,213)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (29628,'Sunny Room in New Condo',40.68414,-73.96351,'Private room',89,3,260,'2019-07-03',2.35,1,278)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (29683,'Stylish & Sleek Apartment Near SoHo!',40.72392,-73.99143000000001,'Entire home/apt',185,5,73,'2019-06-25',0.66,1,209)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (30031,'NYC artists’ loft with roof deck',40.73494,-73.9503,'Private room',50,3,193,'2019-05-20',1.86,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (30927,'Unique & Charming small 1br Apt. LES',40.713409999999996,-73.98855999999999,'Entire home/apt',105,3,32,'2019-06-14',0.29,1,16)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (31130,'Most Central Location!',40.767540000000004,-73.98399,'Private room',130,2,50,'2019-05-26',0.45,3,234)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (31555,'Luminous Beautiful West Village Studio',40.73442,-74.00303000000001,'Entire home/apt',115,29,26,'2019-07-01',0.25,1,12)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (31902,'Sanctuary in East Flatbush',40.631879999999995,-73.93248,'Private room',77,2,2,'2019-01-01',0.02,1,178)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (31994,'Room with En Suite Bathroom & Deck',40.6873,-73.9634,'Private room',76,2,426,'2019-06-24',3.89,3,275)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (32023,'FLAT MACDONOUGH',40.682959999999994,-73.93661999999999,'Entire home/apt',125,3,227,'2019-06-23',2.09,2,163)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (32037,'Huge Private  Floor at The Waverly',40.6863,-73.96765,'Private room',135,4,84,'2019-07-01',0.77,3,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (32100,'Modern Greenpoint, Brooklyn Apt',40.73409,-73.95348,'Entire home/apt',250,29,3,'2017-07-30',0.03,1,34)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (32289,'Sun-drenched, artsy modernist 1 BDRM duplex',40.71561,-73.94835,'Entire home/apt',199,3,10,'2018-06-11',0.1,1,280)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (32331,'Sunny, Cobble Hill Apartment',40.6857,-73.99183000000001,'Entire home/apt',140,2,4,'2016-04-24',0.04,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (32363,'Fully Furnished Basement Apartment',40.74028,-73.83168,'Private room',140,2,1,'2011-09-19',0.01,1,1)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (32965,'FLAT MACDONOUGH GARDEN',40.682809999999996,-73.93524000000001,'Entire home/apt',115,3,124,'2019-06-20',1.72,2,170)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (32969,'Light filled Williamsburg Apartment',40.715959999999995,-73.93938,'Entire home/apt',160,3,11,'2019-07-02',0.11,1,188)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (33009,'Retreat in Williamsburg',40.71492,-73.95935,'Entire home/apt',195,4,240,'2019-06-17',2.19,1,214)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (33014,'NYC Zen',40.72354,-73.98295,'Entire home/apt',195,3,30,'2019-06-17',0.28,1,248)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (33223,'Cozy BR in Wiliamsburg 3 Bedroom',40.71165,-73.96087,'Private room',80,3,200,'2019-06-22',1.86,4,262)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (34760,'Sunny Room in Old Historical Brooklyn Townhouse',40.69101,-73.97312,'Private room',44,8,27,'2019-06-29',1.05,5,280)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (35526,'Sun Filled Classic West Village Apt',40.73474,-74.00101,'Private room',156,4,79,'2019-06-22',0.74,1,307)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (36121,'Lg Rm in Historic Prospect Heights',40.67386,-73.96641,'Private room',85,15,9,'2013-05-10',0.09,1,339)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (36133,'Classic Artist Loft Williamsburg',40.71536,-73.96056999999999,'Private room',125,3,155,'2019-06-13',1.61,1,1)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (36442,'Great location. Spacious on PROSPECT PARK',40.6741,-73.96595,'Entire home/apt',115,15,4,'2018-08-27',0.05,1,269)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (36647,'Private Bdrm/Bathrm. New! Elevator!',40.79295,-73.93997,'Private room',69,2,34,'2017-05-29',0.32,1,10)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (36703,'Sunny, clean 1 bdrm in W. Village',40.73226,-74.00401,'Entire home/apt',225,45,134,'2019-03-31',1.24,1,312)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (36934,'Great location in Williamsburg',40.71363,-73.96398,'Entire home/apt',125,6,27,'2018-12-27',0.25,1,189)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (38638,'Light and Airy Upper East Side 1 BDR apartment',40.77711,-73.9527,'Entire home/apt',219,4,126,'2019-06-26',1.16,2,290)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (38663,'Luxury Brownstone in Boerum Hill',40.685590000000005,-73.98094,'Entire home/apt',475,3,23,'2018-12-31',0.27,1,230)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (39267,'CENTRAL PARK LOFT all for YOU',40.77456,-73.95323,'Entire home/apt',99,1,234,'2019-06-08',2.6,2,164)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (39282,'Indie-Chic Share In Williamsburg',40.710879999999996,-73.95055,'Private room',69,4,202,'2019-05-28',1.86,2,53)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (39593,'A room w/ a Manhattan view, longer stay',40.74559,-73.92313,'Private room',79,30,28,'2019-04-12',0.26,1,126)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (39704,'Private, Large & Sunny 1BR w/W&D',40.68306,-73.94659,'Entire home/apt',135,2,309,'2019-06-22',2.86,2,3)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (40039,'Luxurious Condo in DUBMO with View',40.70207,-73.98571,'Private room',250,3,14,'2011-04-25',0.13,1,189)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (40453,'Charming & Cozy midtown loft any WEEK ENDS  !!!',40.76123,-73.9642,'Entire home/apt',250,3,4,'2016-09-23',0.08,1,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (41348,'* Spacious GARDEN Park Slope Duplex* 6 people max',40.66858,-73.99083,'Entire home/apt',250,2,80,'2019-07-06',2.17,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (41513,'Convenient cozy cheap apt Manhattan',40.827040000000004,-73.94906999999999,'Entire home/apt',80,3,2,'2015-11-02',0.04,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (42580,'Parlor Room In Victorian Townhouse',40.68843,-73.96408000000001,'Private room',70,2,294,'2019-06-24',3.47,3,336)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (42729,'House On Henry (2nd FLR Suite)',40.6783,-74.00135,'Entire home/apt',165,2,150,'2019-06-18',1.4,3,342)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (42882,'New York room with a view',40.64524,-74.08088000000001,'Private room',70,2,166,'2019-06-13',1.66,1,312)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (43957,'Sunny cozy room in Brklyn townhouse',40.70641,-73.91765,'Private room',50,2,47,'2019-06-19',0.94,1,37)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (44096,'Room with a View',40.83232,-73.93184000000001,'Private room',40,1,219,'2019-07-04',2.04,3,353)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (44161,'Light+Open+Airy+Rustic+Modern Loft',40.71045,-73.9677,'Entire home/apt',150,2,193,'2016-07-06',1.78,1,177)

insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (54453,'MIDTOWN WEST - Large alcove studio',40.76548,-73.98474,'Shared room',105,6,10,'2014-01-07',0.09,1,363)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (54466,'Beautiful Uptown Manhattan apartmnt',40.80234,-73.95603,'Private room',200,30,0,'0',0.0,1,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (54508,'Sml Rm in pr Brst  Park Sl great for Med/students',40.6787,-73.97261999999999,'Private room',100,2,226,'2019-06-06',2.12,3,250)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (54544,'City Room - Private Penthouse Apt.',40.81035,-73.94598,'Entire home/apt',121,1,104,'2019-06-22',1.0,5,247)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (54626,'Cozy bedroom by Yankee Stadium',40.83075,-73.93058,'Private room',45,1,138,'2019-06-30',1.45,3,323)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (54860,'Great apartment with private bathroom and entrance',40.79958,-73.94275,'Private room',100,5,204,'2019-06-23',1.92,1,192)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (55467,'Private Garden Apt • New Renovation',40.71625,-73.93845,'Entire home/apt',140,2,253,'2019-07-02',3.04,1,125)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (55498,'Modern comfort in art infused landmark Brownstone',40.6829,-73.93549,'Private room',71,2,23,'2019-07-01',0.22,1,91)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (55668,'NOHO/EAST VILLAGE, PRIVATE 1/2 BATH',40.72773,-73.99134000000001,'Private room',130,2,115,'2018-12-05',1.17,1,75)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (55737,'Sleek & Comfortable Soho Apt',40.728609999999996,-74.0049,'Entire home/apt',199,5,129,'2019-05-19',1.22,1,286)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (55959,'Spacious Williamsburg Share w/ LOFT BED',40.709790000000005,-73.95161999999999,'Private room',69,4,82,'2019-06-10',1.13,2,60)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (55982,'Cozy 2 br in sunny Fort Greene apt',40.68656,-73.97525,'Private room',68,3,37,'2018-12-31',0.35,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (56467,'Cozy East Village Railroad 1 Bed!',40.72752,-73.98432,'Entire home/apt',130,1,204,'2019-07-01',2.04,1,192)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (56525,'1 Bedroom Loft w/ Private Roof Deck',40.729,-73.95829,'Entire home/apt',195,2,69,'2019-06-13',0.65,1,58)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (56859,'City Room - Private & Comfy Bedroom',40.81219,-73.94499,'Private room',64,1,192,'2019-06-03',1.84,5,245)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (57166,'Elegant NYC Pad',40.77185,-73.90502,'Entire home/apt',140,2,17,'2019-06-17',0.16,1,292)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (57297,'Clean & bright 1BR in Cobble Hill, GREAT location!',40.68926,-73.99386,'Entire home/apt',159,2,222,'2019-06-24',2.12,1,279)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (57468,'Modern, Large East Village Loft',40.72821,-73.98701,'Entire home/apt',189,3,205,'2019-06-23',1.96,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (57618,'Great new apt, close to everything',40.7672,-73.98508000000001,'Entire home/apt',250,3,94,'2019-06-09',0.96,1,3)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (57740,'Quiet & Clean Retreat in the City',40.73012,-73.99053,'Entire home/apt',239,3,7,'2019-05-24',0.07,1,351)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (57754,'Stylish Large Gramercy Loft!',40.7403,-73.98498000000001,'Entire home/apt',305,2,108,'2019-06-30',1.09,1,201)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (57874,'The Brownstone-Luxury 1 Bd Apt/NYC',40.809309999999996,-73.94343,'Entire home/apt',155,3,222,'2019-06-26',2.1,2,232)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (58059,'PRIVATE Room on Historic Sugar Hill',40.8251,-73.94287,'Private room',60,1,458,'2019-07-03',4.58,2,258)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (58062,'South Slope Green',40.6585,-73.98397,'Private room',135,2,21,'2019-05-17',0.26,1,272)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (58467,'17 Flr. Manhattan Views, Nr. Subway',40.76193,-73.9501,'Private room',120,7,17,'2019-05-08',0.3,1,341)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (59014,'Spacious 1BR, Adorable Clean Quiet',40.72052,-73.98589,'Entire home/apt',150,3,41,'2019-01-02',0.39,1,244)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (59121,'Nice, clean, safe, convenient 3BR',40.70411,-73.89934000000001,'Entire home/apt',140,14,1,'2012-09-17',0.01,5,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (59642,'Franklin St Flat in Trendy Greenpoint Brooklyn',40.73401,-73.95966999999999,'Entire home/apt',135,2,69,'2019-05-19',0.67,1,12)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (59709,'Artistic, Cozy, and Spacious w/ Patio! Sleeps 5',40.71756,-73.99503,'Entire home/apt',250,4,18,'2019-07-01',0.18,2,265)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (59855,'One bedroom Apt. in NYC',40.7589,-73.96991,'Entire home/apt',250,30,82,'2016-01-05',0.78,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (60164,'Beautiful, elegant 3 bed SOHO loft',40.72003,-74.00262,'Entire home/apt',500,4,94,'2019-06-23',0.99,1,329)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (60457,'Spacious Greenwich Village Apt',40.73194,-73.99474000000001,'Entire home/apt',225,5,10,'2019-05-11',0.1,1,91)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (60611,'SpaHa Studio Monthly Rental',40.79163,-73.94573000000001,'Entire home/apt',125,28,183,'2018-09-29',1.83,2,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (60666,'City Room - Private Luxury Suite',40.8118,-73.94434,'Private room',92,1,189,'2019-06-11',1.82,5,253)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (60673,'Private Room/bath Luxurious Harlem',40.81583,-73.94707,'Private room',175,2,1,'2018-10-07',0.11,1,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (60680,'The gem of the East Village',40.72654,-73.98049,'Entire home/apt',99,2,127,'2019-06-20',1.22,1,320)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (60794,'Bright and spacious, garden below!',40.80021,-73.96070999999999,'Entire home/apt',195,4,4,'2017-08-25',0.04,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (60948,'ACCOMMODATIONS GALORE #2',40.80942,-73.93936,'Entire home/apt',140,3,135,'2019-06-20',1.3,3,192)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (61167,'Colorful Private One Bedroom Apt',40.719609999999996,-73.9954,'Entire home/apt',135,2,21,'2015-12-12',0.2,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (61224,'Huge Chelsea Loft',40.74358,-74.00027,'Entire home/apt',500,2,35,'2017-07-27',0.34,1,348)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (61406,'Great room in great location',40.80335,-73.9575,'Private room',80,14,10,'2019-06-01',2.21,2,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (61492,'Exclusive Room with Private Bath in  LES',40.71445,-73.9908,'Private room',120,4,171,'2019-06-23',1.8,2,353)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (61509,'Quiet, clean midtown apt w. elevato',40.757490000000004,-73.96897,'Entire home/apt',110,200,92,'2019-04-30',0.9,1,140)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (62095,'BK Sweet Suite w/Kitchen&FullBath',40.644459999999995,-73.9503,'Entire home/apt',65,3,238,'2019-06-14',2.3,1,2)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (62427,'Great East Village Apartment Rental',40.7268,-73.99079,'Entire home/apt',130,50,56,'2019-05-26',0.58,1,56)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (62430,'BROWNSTONE SUNDRENCHED BEAUTY',40.688,-73.9171,'Entire home/apt',99,3,111,'2019-06-22',2.13,1,68)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (62452,'A SpeciaL!! Private Room in NY',40.63536,-74.08537,'Private room',36,2,193,'2019-06-25',1.85,6,360)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (62461,'B NYC Staten Alternative...',40.63627,-74.08543,'Private room',37,2,147,'2019-06-10',1.44,6,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (62787,'C Private Room By The Ferry',40.63518,-74.08546,'Private room',37,2,177,'2019-07-02',1.71,6,320)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (62891,'Smallest House In The Village',40.72477,-73.98161,'Entire home/apt',175,3,185,'2019-05-24',1.78,2,326)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (62903,'Beautiful modern studio apartment in heart of NYC',40.74238,-73.99566999999999,'Entire home/apt',205,9,62,'2019-06-21',0.7,2,76)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (62925,'Beautiful Landmarked Duplex',40.72945,-73.95510999999999,'Entire home/apt',285,3,124,'2019-06-16',1.22,3,279)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (63299,'BROOKLYN > Guest Room w/ Queen Bed in Williamsburg',40.70763,-73.95177,'Private room',59,2,181,'2019-06-23',1.77,2,15)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (63320,'D Private Che@p Room 2 Explore NYC',40.634809999999995,-74.08519,'Private room',36,2,333,'2019-07-02',3.19,6,340)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (63360,'Safe cute near subway& Manhattan NY NY retro style',40.753840000000004,-73.91433,'Entire home/apt',99,5,441,'2019-06-24',4.5,1,226)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (63546,'Large and Cozy Private Bedroom',40.641059999999996,-73.97426,'Private room',39,1,45,'2019-05-16',0.46,2,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (63573,'Small tidy bedroom in duplex',40.66793,-73.98326999999999,'Private room',60,14,9,'2016-08-29',0.09,2,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (63588,'LL3',40.81309,-73.85514,'Private room',90,2,0,'0',0.0,7,349)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (63610,'DOMINIQUE S NY mini efficiency* wifi*metro*quiet',40.88057,-73.83572,'Entire home/apt',105,2,38,'2019-06-27',0.5,13,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (63657,'Private, Large & Sunny Top Floor Apt  w/W&D',40.682359999999996,-73.94314,'Entire home/apt',135,2,248,'2019-06-25',2.39,2,11)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (63693,'Cottage in the Village',40.72185,-73.98246,'Entire home/apt',390,5,143,'2019-06-19',1.38,2,316)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (63719,'BEDROOM1 FOR RENT 10min from Manhan',40.68503,-73.95385,'Private room',70,3,36,'2018-08-19',0.41,4,281)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (63913,'HOSTING YOUR  SUNNY, SPACIOUS NYC ROOM',40.866479999999996,-73.9263,'Private room',75,7,0,'0',0.0,2,323)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (64000,'Williamsburg near soho. / loftbed',40.7069,-73.95467,'Private room',60,17,14,'2019-01-07',0.14,4,362)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (64015,'Prime East Village 1 Bedroom',40.72807,-73.98594,'Entire home/apt',200,3,0,'0',0.0,1,0)

insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (84010,'Superior @ Box House',40.73813,-73.95394,'Private room',179,3,13,'2019-06-27',0.14,28,81)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (84059,'So Much Room in Brooklyn',40.675909999999995,-73.94715,'Entire home/apt',150,5,5,'2018-07-22',0.05,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (84659,'Large Studio--Heart of East Village',40.728429999999996,-73.98895,'Entire home/apt',139,1,388,'2019-06-26',3.88,1,142)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (84905,'Huge.Bright.Clean.Safe. Private Room',40.712709999999994,-73.99776,'Private room',95,3,223,'2019-06-23',2.22,2,60)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (85094,'Garden 1BR/1BA Brownstone Apt - 2 blocks to subway',40.66966,-73.94735,'Entire home/apt',79,15,11,'2019-01-14',0.11,5,179)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (86215,'MODERN SPACIOUS 2 BR APT DOWNTOWN MANHATTAN',40.71965,-73.98765999999999,'Entire home/apt',150,2,151,'2019-06-24',1.51,2,52)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (89427,'The Brooklyn Waverly',40.68613,-73.96536,'Entire home/apt',650,5,0,'0',0.0,3,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (89621,'WONDERFUL, COMFORTABLE STUDIO',40.680479999999996,-73.94911,'Entire home/apt',90,3,218,'2019-06-28',2.26,4,324)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (93313,'MAISON DES SIRENES 2',40.68314,-73.93963000000001,'Entire home/apt',120,2,75,'2019-06-23',0.76,2,237)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (94035,'Modern, Safe, Clean, Bright Room in Astoria for 2',40.759609999999995,-73.91117,'Private room',80,1,42,'2019-07-06',1.21,2,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (94209,'LARGE 1BR (CONV 2BR) CROWN HEIGHTS',40.67473,-73.94494,'Entire home/apt',100,90,0,'0',0.0,1,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (94477,'The Vernon On Greene',40.69305,-73.93185,'Entire home/apt',175,2,370,'2019-07-05',3.74,1,204)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (94783,'Beautiful, Bright’s, Warm & Spacious 1.5BR Apt',40.67174,-73.95663,'Entire home/apt',120,5,104,'2019-06-21',1.04,1,272)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (95747,'Lovely 1BR in Tree-lined WBurg',40.71055,-73.95098,'Entire home/apt',140,7,13,'2016-07-18',0.13,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (95883,'Spacious Loft in Clinton Hill',40.69465,-73.95458,'Entire home/apt',200,5,4,'2018-12-26',0.07,1,9)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (96471,'The Brooklyn Waverly, One Bedroom',40.684129999999996,-73.96542,'Private room',165,4,11,'2019-06-07',0.11,3,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (98330,'LOVELY APARTMENT IN THE HEART OF NY',40.73877,-73.97707,'Entire home/apt',125,4,1,'2012-01-03',0.01,3,181)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (98663,'Groovy NYC Chelsea Pad',40.74893,-73.99544,'Entire home/apt',130,30,19,'2018-06-11',0.19,1,189)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (99070,'Comfortable Cozy Space in El Barrio',40.794059999999995,-73.94102,'Shared room',65,7,131,'2019-05-26',1.31,2,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (99085,'Sunny Bklyn Jewel  Fort Greene JULY  - AUG 2019',40.68795,-73.97332,'Entire home/apt',123,30,15,'2019-05-01',0.15,1,189)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (100002,'MANHATTAN Neat, Nice, Bright ROOM',40.85295,-73.93361,'Private room',67,2,136,'2019-06-17',1.37,1,296)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (100184,'Bienvenue',40.72413,-73.76133,'Private room',50,1,43,'2019-07-08',0.45,1,88)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (100186,'Large Brand New Park Slope 1BR',40.66918,-73.99186999999999,'Entire home/apt',130,7,98,'2019-06-28',0.99,1,35)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (101053,'Colorful Artistic Williamsburg Apt',40.71125,-73.95613,'Private room',100,3,31,'2019-03-01',0.31,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (102995,'UWS Brownstone Near Central Park',40.785579999999996,-73.9696,'Entire home/apt',212,21,45,'2018-01-01',0.46,1,35)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (103161,'Artsy TopFloor Apt in PRIME BEDFORD Williamsburg',40.71577,-73.96053,'Entire home/apt',190,3,124,'2019-06-26',1.76,1,359)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (103311,'2 BR w/ Terrace @ Box House Hotel',40.738609999999994,-73.95485,'Private room',599,3,9,'2018-05-19',0.09,28,60)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (103806,'BOHEMIAN EAST VILLAGE 2 BED HAVEN',40.725770000000004,-73.98745,'Entire home/apt',249,5,166,'2019-05-27',1.68,2,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (105469,'Oceanfront Apartment in Rockaway',40.58615,-73.81245,'Private room',70,27,13,'2015-09-21',0.13,1,335)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (105510,'Private 1-Bedroom Apt in Townhouse',40.67086,-73.94872,'Entire home/apt',100,30,15,'2019-01-05',0.16,5,282)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (106363,'Bright Room With A Great River View',40.827729999999995,-73.95231,'Private room',60,3,380,'2019-06-26',3.83,2,247)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (106647,'Tree lined block modern apartment',40.68505,-73.95684,'Entire home/apt',135,2,86,'2019-06-16',0.87,1,102)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (107630,'Sweet Historic Greenpoint Duplex',40.72911,-73.95493,'Entire home/apt',175,3,248,'2019-06-20',2.53,3,274)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (107895,'Riverside Charm with Fire Place',40.77944,-73.98567,'Entire home/apt',120,5,49,'2019-06-19',0.56,1,201)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (110739,'Very Central, Nomad/Chelsea Loft Studio',40.74503,-73.98876,'Entire home/apt',169,18,54,'2019-07-03',0.57,1,98)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (112100,'Sunny 3BR Apt Ideal for Family  ',40.67539,-73.96093,'Entire home/apt',165,7,3,'2013-01-01',0.03,1,157)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (112304,'Cozy Private Room in West Harlem!',40.8054,-73.95189,'Private room',90,1,1,'2016-01-02',0.02,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (112359,'UES Quiet & Spacious 1 bdrm for 4',40.784909999999996,-73.9508,'Entire home/apt',225,2,56,'2018-12-28',0.57,1,312)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (112435,'ALL ABOUT A VERY COMFORTABLE ROOM..',40.69088,-73.97306999999999,'Private room',95,2,163,'2019-05-24',1.66,2,331)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (113265,'Brooklyn- Crown Heights Garden Apt.',40.67555,-73.95057,'Private room',55,2,247,'2019-06-21',2.51,2,275)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (113945,'Cozy room in Time Square!',40.75835,-73.99193000000001,'Private room',85,10,116,'2019-05-11',1.17,1,174)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (114123,'Large Park Slope Townhouse Duplex',40.66527,-73.9886,'Entire home/apt',199,14,27,'2019-05-19',0.28,2,223)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (114229,'Lower East Side 2 Bedroom Apt',40.71895,-73.99434000000001,'Entire home/apt',211,1,52,'2019-06-08',0.6,3,361)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (114969,'Manhattan Studio, Perfect Location',40.755790000000005,-73.96699,'Entire home/apt',145,6,39,'2018-09-24',0.4,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (115535,'Sun-Drenched Hamilton Hts Jewel   ',40.82399,-73.95328,'Private room',65,14,35,'2019-06-01',0.35,1,283)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (115678,'Your Stunning Vacation Apartment!',40.818220000000004,-73.94095,'Entire home/apt',99,1,320,'2019-06-23',3.23,1,220)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (115748,'1 BDRM Apt-Weekend Sublease',40.764340000000004,-73.92132,'Entire home/apt',110,4,30,'2019-06-16',0.32,1,363)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (116940,'ROOM WITH A  KITCHENETTE',40.67705,-73.94925,'Entire home/apt',80,3,225,'2019-06-24',2.27,4,315)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (117425,'Conveniently Located, Sunny Brooklyn Heights!',40.69263,-73.99438,'Entire home/apt',150,30,95,'2018-05-26',0.96,1,281)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (118061,'Style in Stuyvesant Heights',40.68448,-73.92747,'Entire home/apt',110,4,70,'2019-06-28',0.75,1,283)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (118430,'Heart of Meatpacking & Chelsea',40.74412,-74.00208,'Private room',290,2,35,'2019-01-03',0.36,1,20)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (118680,'Spacious East Village apt near it all',40.73067,-73.98702,'Private room',87,2,0,'0',0.0,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (120362,'Williamsburg apartment right by the subway',40.70665,-73.94060999999999,'Entire home/apt',190,4,50,'2019-07-02',0.51,1,331)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (121687,'Spacious Brooklyn Loft - 2 Bedroom',40.72063,-73.95952,'Entire home/apt',200,2,29,'2019-06-23',0.31,1,36)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (121861,'Park Slope Apt:, Spacious 2 bedroom',40.67644,-73.98082,'Entire home/apt',165,2,23,'2016-05-02',0.23,2,7)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (123784,'NYC Studio for Rent in Townhouse',40.804809999999996,-73.94794,'Entire home/apt',110,2,142,'2019-06-16',1.44,2,301)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (125053,'⚡Quiet Gem w/roof deck on NY s Hottest Street⚡',40.72533,-73.99143000000001,'Entire home/apt',395,2,70,'2019-07-01',0.73,1,170)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (125163,'Authentic New York City Living ',40.68569,-73.93038,'Private room',99,2,38,'2019-06-03',0.54,2,307)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (125594,'SUPER BIG AND COZY PRIVATE BEDROOM',40.64302,-73.97255,'Private room',39,1,82,'2019-05-19',0.94,2,365)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (126443,'☆Massive DUPLEX☆ 2BR & 2BTH East Village 9+ Guests',40.72939,-73.98857,'Entire home/apt',189,2,403,'2019-07-07',4.1,3,201)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (126816,'Gorgeous Upper West Side Apartment',40.79918,-73.96607,'Private room',85,1,3,'2014-11-06',0.03,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (127387,'Luxe, Spacious 2BR 2BA Nr Trains',40.668620000000004,-73.9926,'Entire home/apt',260,30,3,'2014-08-04',0.03,1,316)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (128975,'City Room - Street View Apt',40.81333,-73.94453,'Entire home/apt',122,1,116,'2019-06-13',1.18,5,271)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (131154,'Cozy and Bright One Bedroom in BK',40.72473,-73.95199000000001,'Entire home/apt',165,2,175,'2019-07-07',1.79,1,139)

insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (168123,'Sunny, quiet, legal homelike suite-Pk Slope South',40.66085,-73.98536999999999,'Entire home/apt',105,28,101,'2019-07-01',1.06,1,167)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (168546,'Spacious Duplex in Brownstone!',40.80113,-73.94503,'Entire home/apt',250,2,11,'2016-01-02',0.12,2,68)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (168810,'Lovely Vintage Haven—Heart of UWS',40.78569,-73.97581,'Entire home/apt',175,65,11,'2013-10-15',0.12,1,358)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (169002,'Modern Space in Charming Pre-war',40.82411,-73.94934,'Private room',65,2,41,'2019-06-16',0.43,2,59)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (169152,'Warehouse Loft with Garden view',40.681309999999996,-73.95331999999999,'Entire home/apt',75,2,87,'2017-04-18',1.09,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (169306,' Affordable & Cozy ',40.858109999999996,-73.90675,'Private room',37,4,117,'2019-05-21',1.21,1,232)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (169464,'Creative Vintage Loft in S. Williamsburg',40.70667,-73.96524000000001,'Entire home/apt',85,2,86,'2019-05-16',0.89,2,15)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (169483,'Very close to Downtown Awesome Private Apartment',40.60452,-73.97103,'Entire home/apt',106,7,0,'0',0.0,2,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (170420,'The Happy home!',40.7932,-73.94006999999999,'Entire home/apt',79,2,15,'2016-02-15',0.16,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (170761,'Fort Greene, Brooklyn: Front Bedroom',40.68768,-73.97610999999999,'Private room',85,2,35,'2019-07-02',0.55,2,161)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (171776,'Gorgeous 1 bdrm in huge duplex!',40.802240000000005,-73.94558,'Private room',170,2,17,'2015-10-01',0.18,2,88)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (172700,'Sunny, cozy room in Lower East Side',40.714729999999996,-73.98841999999999,'Private room',115,3,3,'2016-02-15',0.04,2,337)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (172870,'Large Quiet Bedroom Near Columbia U',40.80518,-73.95359,'Private room',89,5,43,'2018-01-03',0.47,2,247)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (173072,'Cozy Pre-War Harlem Apartment',40.80827,-73.95329,'Shared room',49,3,168,'2019-07-06',4.6,1,248)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (173151,'spacious studio',40.729009999999995,-73.95812,'Private room',91,3,241,'2019-06-24',2.49,1,287)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (173742,'Elegant 2-BR duplex, Union Square',40.734759999999994,-73.98451999999999,'Entire home/apt',400,2,105,'2019-06-23',1.13,1,304)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (174527,'Cozy private family home in Bushwick',40.69055,-73.92357,'Entire home/apt',150,2,11,'2018-10-28',0.46,1,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (174966,'Luxury 2Bed/2.5Bath Central Park View',40.7735,-73.98697,'Entire home/apt',2000,30,30,'2018-05-05',0.33,11,0)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (176135,'Cosy Sunny 1brm in Prospect Heights',40.67505,-73.95969000000001,'Entire home/apt',97,3,31,'2018-10-23',0.32,1,193)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (176653,'East Village bedroom w rooftop',40.72974,-73.98201,'Private room',100,4,49,'2019-05-07',0.51,2,43)
insert into house(id,name,latitude,longitude,room_type,price,    minimum_nights,number_of_reviews,last_review,reviews_per_month,    calculated_host_listings_count,availability_365)     values (176962,'Williamsburg Home Away From Home!',40.70925,-73.95425,'Entire home/apt',179,4,23,'2019-04-13',0.24,1,25)

In [74]:
mycursor.execute("select name from house where room_type='Private room' ")

for x in mycursor:
    print(x)

('Clean & quiet apt home by the park',)
('THE VILLAGE OF HARLEM....NEW YORK !',)
('BlissArtsSpace!',)
('Large Furnished Room Near B way ',)
('Cozy Clean Guest Room - Family Apt',)
('Central Manhattan/near Broadway',)
('Lovely Room 1, Garden, Best Area, Legal rental',)
('Wonderful Guest Bedroom in Manhattan for SINGLES',)
('Chelsea Perfect',)
('CBG CtyBGd HelpsHaiti rm#1:1-4',)
('CBG Helps Haiti Room#2.5',)
('CBG Helps Haiti Rm #2',)
('Sunny Bedroom Across Prospect Park',)
('Magnifique Suite au N de Manhattan - vue Cloitres',)
('SPACIOUS, LOVELY FURNISHED MANHATTAN BEDROOM',)
('front room/double bed',)
('Spacious 1 bedroom in luxe building',)
('Loft in Williamsburg Area w/ Roof',)
('back room/bunk beds',)
('Large B&B Style rooms',)
('Lovely room 2 & garden; Best area, Legal rental',)
('Clean and Quiet in Brooklyn',)
('Country space in the city',)
('ENJOY Downtown NYC!',)
('1bdr w private bath. in lofty apt',)
('West Side Retreat',)
('1 Stop fr. Manhattan! Private Suite,Landmark Block',)
('Fort Greene brownstone ',)
('Blue Room for 2 in Brownstone for $1350 monthly',)
('Great Location, Manhattan Bedroom!',)
('Best Location in NYC! TIMES SQUARE!',)
('Room in Greenpoint Loft w/ Roof',)
('Very, very cozy place',)
('Double Room w Private Deck Clinton Hill Best Area',)
('Your Heaven in Hells Kitchen',)
('Sunny, Modern room in East Village!',)
('Large Room in Amazing East Village Apt',)
('Cool Room in Hell s Kitchen',)
('HARLEM, NEW YORK WELCOMES YOU!!',)
('BLUE TRIM GUEST HOUSE',)
('Manhattan Room',)
('Little King of Queens',)
('Fort Greene Retreat on the Park',)
('Beautiful Meatpacking District Loft',)
('Cozy 2 BR in Williamsburg ',)
('Private room Great Deal at Lower East Side',)
('Oh glorious spring!',)
('Great Location for NYC',)
('Cozy Bedroom in Williamsburg 3 BR',)
('Sunny room+Pvte office in huge loft',)
('Large Parlor Room, Landmark Home 1 block to PRATT',)
('Upper Manhattan, New York',)
('COZY QUIET room 4 DOOGLERS!',)
('loft bed - near transportation-15min to times sq',)
('Monkey Retreat Manhattan',)
('Williamsburg—Steps To Subway, Private Bath&Balcony',)
('1,800 sq foot in luxury building',)
('Times Square, Safe, Clean and Cozy!',)
('Cozy Room #3, Landmark Home 1 Block to PRATT',)
('Eveland Private Bed & Living Room w/ Own Entrance',)
('Large 1  BR in a 3 BR Brooklyn apt. next to Q Trn.',)
('Modern Apt with Spectacular Views',)
('Secluded Master Bedroom in Beautiful Huge Apt',)
('B & B Room 1',)
('Sunny Room in New Condo',)
('NYC artists’ loft with roof deck',)
('Most Central Location!',)
('Sanctuary in East Flatbush',)
('Room with En Suite Bathroom & Deck',)
('Huge Private  Floor at The Waverly',)
('Fully Furnished Basement Apartment',)
('Cozy BR in Wiliamsburg 3 Bedroom',)
('Sunny Room in Old Historical Brooklyn Townhouse',)
('Sun Filled Classic West Village Apt',)
('Lg Rm in Historic Prospect Heights',)
('Classic Artist Loft Williamsburg',)
('Private Bdrm/Bathrm. New! Elevator!',)
('Indie-Chic Share In Williamsburg',)
('A room w/ a Manhattan view, longer stay',)
('Luxurious Condo in DUBMO with View',)
('Parlor Room In Victorian Townhouse',)
('New York room with a view',)
('Sunny cozy room in Brklyn townhouse',)
('Room with a View',)
('West Inn 2 - East Village',)
('BROOKLYN VICTORIAN STYLE SUITE.....',)
('Fort Greene, Brooklyn: Center Bedroom',)
('Couldn t Be Closer To Columbia Uni',)
('SAFE  AND BEAUTIFUL ACCOMODATION',)
('Large Room in private Brownstone in Park Slope',)
('NEW YORK CITY, 1 BDRM.(NEAR CENTRAL PARK & METRO)',)
('1 Bedroom in 2 Bdrm Apt- Upper East',)
('Lower East Side $57~/night',)
('Prime Location in Manhattan',)
('( F) Excellent/Pvt Rm',)
('Big Room/Washer-Dryer/Wifi/AC/JMZ',)
('Clean and convenient 2BR apartment',)
('Beautiful Uptown Manhattan apartmnt',)
('Sml Rm in pr Brst  Park Sl great for Med/students',)
('Cozy bedroom by Yankee Stadium',)
('Great apartment with private bathroom and entrance',)
('Modern comfort in art infused landmark Brownstone',)
('NOHO/EAST VILLAGE, PRIVATE 1/2 BATH',)
('Spacious Williamsburg Share w/ LOFT BED',)
('Cozy 2 br in sunny Fort Greene apt',)
('City Room - Private & Comfy Bedroom',)
('PRIVATE Room on Historic Sugar Hill',)
('South Slope Green',)
('17 Flr. Manhattan Views, Nr. Subway',)
('City Room - Private Luxury Suite',)
('Private Room/bath Luxurious Harlem',)
('Great room in great location',)
('Exclusive Room with Private Bath in  LES',)
('A SpeciaL!! Private Room in NY',)
('B NYC Staten Alternative...',)
('C Private Room By The Ferry',)
('BROOKLYN > Guest Room w/ Queen Bed in Williamsburg',)
('D Private Che@p Room 2 Explore NYC',)
('Large and Cozy Private Bedroom',)
('Small tidy bedroom in duplex',)
('LL3',)
('BEDROOM1 FOR RENT 10min from Manhan',)
('HOSTING YOUR  SUNNY, SPACIOUS NYC ROOM',)
('Williamsburg near soho. / loftbed',)
('BROOKLYN  STUDIO APARTMENT',)
('BEDROOM2 FOR RENT  10min from Manh',)
('cozy bedroom in lovely garden apt',)
('Crown Heights Garden Apt.',)
('ENJOY Downtown NYC!!',)
('Share a HOME - $75 for 1 bdrm/++ for 2 - Brooklyn',)
('Room in S3rd/Bedford, Williamsburg',)
('Suite Sugar Hill, Harlem, Private Rm in Hosted Apt',)
('Private Bedroom Brownstone Brooklyn',)
('Lower East Side Magic Room',)
('SoHa comfort-by NW Central Park!',)
('Cozy room in Upper West Side',)
('Cozy Private Room in Apartment',)
('Bright Beautiful Brooklyn',)
('Brooklyn Writer s Nook',)
('Private Bedroom in Large NYC Apartment',)
('Large, Sunny Room East Village NYC',)
('Private room in cozy Greenpoint',)
('Sunlit and Cozy Williamsburg/Greenpoint, Brooklyn',)
('BROOKLYN > Guest Room w/ King Bed in Williamsburg',)
('Superior @ Box House',)
('Hells Kitchen Garden of Eden',)
('Williamsburg HUGE, PRIVATE BATH - Next to Train!',)
('Cozy room in East Village with AC',)
('Duplex w/ Terrace @ Box House Hotel',)
('Loft w/ Terrace @ Box House Hotel',)
('Loft w/ Terrace @ Box House Hotel',)
('Columbia Castle in Brooklyn Heights',)
('Superior @ Box House',)
('Huge.Bright.Clean.Safe. Private Room',)
('Modern, Safe, Clean, Bright Room in Astoria for 2',)
('The Brooklyn Waverly, One Bedroom',)
('MANHATTAN Neat, Nice, Bright ROOM',)
('Bienvenue',)
('Colorful Artistic Williamsburg Apt',)
('2 BR w/ Terrace @ Box House Hotel',)
('Oceanfront Apartment in Rockaway',)
('Bright Room With A Great River View',)
('Cozy Private Room in West Harlem!',)
('ALL ABOUT A VERY COMFORTABLE ROOM..',)
('Brooklyn- Crown Heights Garden Apt.',)
('Cozy room in Time Square!',)
('Sun-Drenched Hamilton Hts Jewel   ',)
('Heart of Meatpacking & Chelsea',)
('Spacious East Village apt near it all',)
('Authentic New York City Living ',)
('SUPER BIG AND COZY PRIVATE BEDROOM',)
('Gorgeous Upper West Side Apartment',)
('Midtown cozy convenient',)
('Private, spacious room in Brooklyn',)
('Holiday Time in NY - Oh My!!',)
('1 Bdrm in 4 Bdrm dupelx/roof deck',)
('BIG, COMFY , PRIV. ROOM, BIG APT, YARD, GREAT LOC.',)
('CHARMING PRIVATE BEDROOM EAST VILLAGE',)
('City Room - Semi Private Bedroom',)
('Female Only Clean15min to Manhattan',)
('Private E. Village Townhouse Stay',)
('Harlem/Hamilton Heights Cozy Room',)
('Hancock Town House!-Stuyvesant Mews',)
('Clinton Hill + Free Coffee = #smile',)
('Purple Room for 2/3 in brownstone $1450 per month',)
('Red Room for two in Brownstone for $1355/mo',)
('Chelsea living, 2BR best location',)
('Sunny 15min to Manhattan LADY only',)
('Surfer room 15mins to downtown NYC!',)
('Blue Room in Awesome Artist s Apartment!',)
('Greenpoint Loft / Le Chez Andrea',)
('*SoHo: Clean, Safe, Private, Peaceful Bedroom (A)*',)
('Couldn t Be Closer To Columbia Uni2',)
('Lady only Curtain-divided room',)
('LG Private Room/Family Friendly',)
('Spacious Quiet rm - 20mins to Midtown',)
('CBG# 4Tiny room w/ huge window/AC',)
('Modern Space in Charming Pre-war',)
(' Affordable & Cozy ',)
('Fort Greene, Brooklyn: Front Bedroom',)
('Gorgeous 1 bdrm in huge duplex!',)
('Sunny, cozy room in Lower East Side',)
('Large Quiet Bedroom Near Columbia U',)
('spacious studio',)
('East Village bedroom w rooftop',)

In [11]:
#table possess
for i in range(500):
    sql="insert into possess(id,host_id) \
    values ("+str(df["id"][i])+",\'"+str(df["host_id"][i])+"\'"+")"

    print(sql)
    mycursor.execute(sql)

    db.commit()

insert into possess(id,host_id)     values (2539,'2787')
insert into possess(id,host_id)     values (2595,'2845')
insert into possess(id,host_id)     values (3647,'4632')
insert into possess(id,host_id)     values (3831,'4869')
insert into possess(id,host_id)     values (5022,'7192')
insert into possess(id,host_id)     values (5099,'7322')
insert into possess(id,host_id)     values (5121,'7356')
insert into possess(id,host_id)     values (5178,'8967')
insert into possess(id,host_id)     values (5203,'7490')
insert into possess(id,host_id)     values (5238,'7549')
insert into possess(id,host_id)     values (5295,'7702')
insert into possess(id,host_id)     values (5441,'7989')
insert into possess(id,host_id)     values (5803,'9744')
insert into possess(id,host_id)     values (6021,'11528')
insert into possess(id,host_id)     values (6090,'11975')
insert into possess(id,host_id)     values (6848,'15991')
insert into possess(id,host_id)     values (7097,'17571')
insert into possess(id,host_id)     values (7322,'18946')
insert into possess(id,host_id)     values (7726,'20950')
insert into possess(id,host_id)     values (7750,'17985')
insert into possess(id,host_id)     values (7801,'21207')
insert into possess(id,host_id)     values (8024,'22486')
insert into possess(id,host_id)     values (8025,'22486')
insert into possess(id,host_id)     values (8110,'22486')
insert into possess(id,host_id)     values (8490,'25183')
insert into possess(id,host_id)     values (8505,'25326')
insert into possess(id,host_id)     values (8700,'26394')
insert into possess(id,host_id)     values (9357,'30193')
insert into possess(id,host_id)     values (9518,'31374')
insert into possess(id,host_id)     values (9657,'21904')
insert into possess(id,host_id)     values (9668,'32294')
insert into possess(id,host_id)     values (9704,'32045')
insert into possess(id,host_id)     values (9782,'32169')
insert into possess(id,host_id)     values (9783,'32294')
insert into possess(id,host_id)     values (10452,'35935')
insert into possess(id,host_id)     values (10962,'9744')
insert into possess(id,host_id)     values (11452,'7355')
insert into possess(id,host_id)     values (11708,'44145')
insert into possess(id,host_id)     values (11943,'45445')
insert into possess(id,host_id)     values (12048,'7549')
insert into possess(id,host_id)     values (12192,'46978')
insert into possess(id,host_id)     values (12299,'47610')
insert into possess(id,host_id)     values (12303,'47618')
insert into possess(id,host_id)     values (12318,'16800')
insert into possess(id,host_id)     values (12343,'47727')
insert into possess(id,host_id)     values (12627,'49670')
insert into possess(id,host_id)     values (12937,'50124')
insert into possess(id,host_id)     values (12940,'50148')
insert into possess(id,host_id)     values (13050,'50846')
insert into possess(id,host_id)     values (13394,'52335')
insert into possess(id,host_id)     values (13808,'54275')
insert into possess(id,host_id)     values (14287,'56094')
insert into possess(id,host_id)     values (14290,'56104')
insert into possess(id,host_id)     values (14314,'56246')
insert into possess(id,host_id)     values (14322,'56284')
insert into possess(id,host_id)     values (14377,'56512')
insert into possess(id,host_id)     values (14991,'59023')
insert into possess(id,host_id)     values (15220,'59734')
insert into possess(id,host_id)     values (15338,'32169')
insert into possess(id,host_id)     values (15341,'60049')
insert into possess(id,host_id)     values (15385,'60252')
insert into possess(id,host_id)     values (15396,'60278')
insert into possess(id,host_id)     values (15711,'61491')
insert into possess(id,host_id)     values (16326,'63588')
insert into possess(id,host_id)     values (16338,'63613')
insert into possess(id,host_id)     values (16421,'63924')
insert into possess(id,host_id)     values (16458,'64056')
insert into possess(id,host_id)     values (16580,'64442')
insert into possess(id,host_id)     values (16595,'64522')
insert into possess(id,host_id)     values (16821,'4396')
insert into possess(id,host_id)     values (16974,'65837')
insert into possess(id,host_id)     values (17037,'66035')
insert into possess(id,host_id)     values (17092,'66243')
insert into possess(id,host_id)     values (17693,'68428')
insert into possess(id,host_id)     values (17747,'68599')
insert into possess(id,host_id)     values (18127,'69829')
insert into possess(id,host_id)     values (18152,'69942')
insert into possess(id,host_id)     values (18198,'70091')
insert into possess(id,host_id)     values (18590,'71512')
insert into possess(id,host_id)     values (18728,'71876')
insert into possess(id,host_id)     values (18764,'72014')
insert into possess(id,host_id)     values (19159,'73051')
insert into possess(id,host_id)     values (19169,'73128')
insert into possess(id,host_id)     values (19282,'73469')
insert into possess(id,host_id)     values (19319,'44263')
insert into possess(id,host_id)     values (19601,'74303')
insert into possess(id,host_id)     values (19812,'74857')
insert into possess(id,host_id)     values (20299,'62407')
insert into possess(id,host_id)     values (20300,'76627')
insert into possess(id,host_id)     values (20611,'72014')
insert into possess(id,host_id)     values (20724,'961342')
insert into possess(id,host_id)     values (20734,'78460')
insert into possess(id,host_id)     values (20755,'51038')
insert into possess(id,host_id)     values (20853,'79070')
insert into possess(id,host_id)     values (20913,'79402')
insert into possess(id,host_id)     values (21293,'44145')
insert into possess(id,host_id)     values (21456,'42032')
insert into possess(id,host_id)     values (21644,'82685')
insert into possess(id,host_id)     values (21794,'83257')
insert into possess(id,host_id)     values (22911,'87773')
insert into possess(id,host_id)     values (22918,'32294')
insert into possess(id,host_id)     values (23135,'11481')
insert into possess(id,host_id)     values (23501,'63318')
insert into possess(id,host_id)     values (23686,'93790')
insert into possess(id,host_id)     values (24143,'97219')
insert into possess(id,host_id)     values (24285,'97797')
insert into possess(id,host_id)     values (25235,'87773')
insert into possess(id,host_id)     values (25406,'105538')
insert into possess(id,host_id)     values (25696,'107628')
insert into possess(id,host_id)     values (26012,'109589')
insert into possess(id,host_id)     values (26362,'59734')
insert into possess(id,host_id)     values (26520,'51038')
insert into possess(id,host_id)     values (26559,'112793')
insert into possess(id,host_id)     values (26785,'42273')
insert into possess(id,host_id)     values (26933,'72062')
insert into possess(id,host_id)     values (26954,'115157')
insert into possess(id,host_id)     values (26969,'115307')
insert into possess(id,host_id)     values (27006,'115560')
insert into possess(id,host_id)     values (27385,'72062')
insert into possess(id,host_id)     values (27531,'118971')
insert into possess(id,host_id)     values (27644,'119510')
insert into possess(id,host_id)     values (27659,'119588')
insert into possess(id,host_id)     values (27759,'119900')
insert into possess(id,host_id)     values (27883,'120223')
insert into possess(id,host_id)     values (28321,'65091')
insert into possess(id,host_id)     values (28396,'6197784')
insert into possess(id,host_id)     values (28907,'124352')
insert into possess(id,host_id)     values (29012,'124797')
insert into possess(id,host_id)     values (29013,'35935')
insert into possess(id,host_id)     values (29455,'126607')
insert into possess(id,host_id)     values (29628,'127608')
insert into possess(id,host_id)     values (29683,'125857')
insert into possess(id,host_id)     values (30031,'129352')
insert into possess(id,host_id)     values (30927,'120335')
insert into possess(id,host_id)     values (31130,'117287')
insert into possess(id,host_id)     values (31555,'135619')
insert into possess(id,host_id)     values (31902,'137292')
insert into possess(id,host_id)     values (31994,'137814')
insert into possess(id,host_id)     values (32023,'137974')
insert into possess(id,host_id)     values (32037,'116599')
insert into possess(id,host_id)     values (32100,'138579')
insert into possess(id,host_id)     values (32289,'139612')
insert into possess(id,host_id)     values (32331,'139874')
insert into possess(id,host_id)     values (32363,'140025')
insert into possess(id,host_id)     values (32965,'137974')
insert into possess(id,host_id)     values (32969,'142833')
insert into possess(id,host_id)     values (33009,'143027')
insert into possess(id,host_id)     values (33014,'143048')
insert into possess(id,host_id)     values (33223,'72014')
insert into possess(id,host_id)     values (34760,'149929')
insert into possess(id,host_id)     values (35526,'120291')
insert into possess(id,host_id)     values (36121,'62165')
insert into possess(id,host_id)     values (36133,'142684')
insert into possess(id,host_id)     values (36442,'137432')
insert into possess(id,host_id)     values (36647,'157798')
insert into possess(id,host_id)     values (36703,'158284')

insert into possess(id,host_id)     values (36934,'159370')
insert into possess(id,host_id)     values (38638,'92788')
insert into possess(id,host_id)     values (38663,'165789')
insert into possess(id,host_id)     values (39267,'168417')
insert into possess(id,host_id)     values (39282,'168525')
insert into possess(id,host_id)     values (39593,'110506')
insert into possess(id,host_id)     values (39704,'170510')
insert into possess(id,host_id)     values (40039,'171851')
insert into possess(id,host_id)     values (40453,'174025')
insert into possess(id,host_id)     values (41348,'180083')
insert into possess(id,host_id)     values (41513,'181167')
insert into possess(id,host_id)     values (42580,'137814')
insert into possess(id,host_id)     values (42729,'11481')
insert into possess(id,host_id)     values (42882,'185978')
insert into possess(id,host_id)     values (43957,'177536')
insert into possess(id,host_id)     values (44096,'190409')
insert into possess(id,host_id)     values (44161,'193360')
insert into possess(id,host_id)     values (44212,'72062')
insert into possess(id,host_id)     values (44221,'193722')
insert into possess(id,host_id)     values (44229,'181376')
insert into possess(id,host_id)     values (44288,'193637')
insert into possess(id,host_id)     values (44506,'126607')
insert into possess(id,host_id)     values (45393,'201297')
insert into possess(id,host_id)     values (45542,'202249')
insert into possess(id,host_id)     values (45556,'67778')
insert into possess(id,host_id)     values (45910,'204539')
insert into possess(id,host_id)     values (45936,'867225')
insert into possess(id,host_id)     values (45940,'204724')
insert into possess(id,host_id)     values (46544,'8198')
insert into possess(id,host_id)     values (46723,'209460')
insert into possess(id,host_id)     values (46911,'210746')
insert into possess(id,host_id)     values (47199,'212722')
insert into possess(id,host_id)     values (47362,'214148')
insert into possess(id,host_id)     values (47370,'214287')
insert into possess(id,host_id)     values (47926,'218404')
insert into possess(id,host_id)     values (48719,'221873')
insert into possess(id,host_id)     values (50447,'9744')
insert into possess(id,host_id)     values (51438,'236421')
insert into possess(id,host_id)     values (51485,'236655')
insert into possess(id,host_id)     values (51572,'237329')
insert into possess(id,host_id)     values (51850,'27848')
insert into possess(id,host_id)     values (53137,'240360')
insert into possess(id,host_id)     values (53196,'247432')
insert into possess(id,host_id)     values (53469,'204539')
insert into possess(id,host_id)     values (53470,'204539')
insert into possess(id,host_id)     values (53477,'204539')
insert into possess(id,host_id)     values (54158,'10889')
insert into possess(id,host_id)     values (54453,'255583')
insert into possess(id,host_id)     values (54466,'253385')
insert into possess(id,host_id)     values (54508,'210746')
insert into possess(id,host_id)     values (54544,'256161')
insert into possess(id,host_id)     values (54626,'190409')
insert into possess(id,host_id)     values (54860,'258164')
insert into possess(id,host_id)     values (55467,'260709')
insert into possess(id,host_id)     values (55498,'262138')
insert into possess(id,host_id)     values (55668,'88209')
insert into possess(id,host_id)     values (55737,'263414')
insert into possess(id,host_id)     values (55959,'168525')
insert into possess(id,host_id)     values (55982,'264928')
insert into possess(id,host_id)     values (56467,'267593')
insert into possess(id,host_id)     values (56525,'268014')
insert into possess(id,host_id)     values (56859,'256161')
insert into possess(id,host_id)     values (57166,'272006')
insert into possess(id,host_id)     values (57297,'199392')
insert into possess(id,host_id)     values (57468,'239208')
insert into possess(id,host_id)     values (57618,'274557')
insert into possess(id,host_id)     values (57740,'275459')
insert into possess(id,host_id)     values (57754,'275578')
insert into possess(id,host_id)     values (57874,'276291')
insert into possess(id,host_id)     values (58059,'277379')
insert into possess(id,host_id)     values (58062,'277394')
insert into possess(id,host_id)     values (58467,'279797')
insert into possess(id,host_id)     values (59014,'282927')
insert into possess(id,host_id)     values (59121,'204539')
insert into possess(id,host_id)     values (59642,'274782')
insert into possess(id,host_id)     values (59709,'186084')
insert into possess(id,host_id)     values (59855,'288031')
insert into possess(id,host_id)     values (60164,'289653')
insert into possess(id,host_id)     values (60457,'99212')
insert into possess(id,host_id)     values (60611,'292204')
insert into possess(id,host_id)     values (60666,'256161')
insert into possess(id,host_id)     values (60673,'249372')
insert into possess(id,host_id)     values (60680,'292630')
insert into possess(id,host_id)     values (60794,'293394')
insert into possess(id,host_id)     values (60948,'126607')
insert into possess(id,host_id)     values (61167,'295760')
insert into possess(id,host_id)     values (61224,'291112')
insert into possess(id,host_id)     values (61406,'297176')
insert into possess(id,host_id)     values (61492,'297769')
insert into possess(id,host_id)     values (61509,'23619')
insert into possess(id,host_id)     values (62095,'281764')
insert into possess(id,host_id)     values (62427,'303882')
insert into possess(id,host_id)     values (62430,'197755')
insert into possess(id,host_id)     values (62452,'303939')
insert into possess(id,host_id)     values (62461,'303939')
insert into possess(id,host_id)     values (62787,'303939')
insert into possess(id,host_id)     values (62891,'306545')
insert into possess(id,host_id)     values (62903,'306605')
insert into possess(id,host_id)     values (62925,'306739')
insert into possess(id,host_id)     values (63299,'308875')
insert into possess(id,host_id)     values (63320,'303939')
insert into possess(id,host_id)     values (63360,'307962')
insert into possess(id,host_id)     values (63546,'308652')
insert into possess(id,host_id)     values (63573,'310458')
insert into possess(id,host_id)     values (63588,'295128')
insert into possess(id,host_id)     values (63610,'310670')
insert into possess(id,host_id)     values (63657,'170510')
insert into possess(id,host_id)     values (63693,'306545')
insert into possess(id,host_id)     values (63719,'311286')
insert into possess(id,host_id)     values (63913,'312288')
insert into possess(id,host_id)     values (64000,'312722')
insert into possess(id,host_id)     values (64015,'146944')
insert into possess(id,host_id)     values (64107,'313317')
insert into possess(id,host_id)     values (64277,'311286')
insert into possess(id,host_id)     values (64314,'314256')
insert into possess(id,host_id)     values (64365,'314582')
insert into possess(id,host_id)     values (64707,'7310')
insert into possess(id,host_id)     values (64837,'46978')
insert into possess(id,host_id)     values (65019,'317809')
insert into possess(id,host_id)     values (65268,'319092')
insert into possess(id,host_id)     values (65556,'320422')
insert into possess(id,host_id)     values (65562,'320450')
insert into possess(id,host_id)     values (65615,'320761')
insert into possess(id,host_id)     values (65660,'320538')
insert into possess(id,host_id)     values (65813,'321756')
insert into possess(id,host_id)     values (65834,'321934')
insert into possess(id,host_id)     values (66008,'322884')
insert into possess(id,host_id)     values (66026,'322716')
insert into possess(id,host_id)     values (66251,'324460')
insert into possess(id,host_id)     values (66275,'314941')
insert into possess(id,host_id)     values (66451,'325389')
insert into possess(id,host_id)     values (66718,'136227')
insert into possess(id,host_id)     values (66741,'327673')
insert into possess(id,host_id)     values (66974,'329436')
insert into possess(id,host_id)     values (67288,'101597')
insert into possess(id,host_id)     values (67299,'330347')
insert into possess(id,host_id)     values (67397,'332189')
insert into possess(id,host_id)     values (68099,'323517')
insert into possess(id,host_id)     values (68305,'338454')
insert into possess(id,host_id)     values (68403,'240427')
insert into possess(id,host_id)     values (68735,'342054')
insert into possess(id,host_id)     values (68765,'282655')
insert into possess(id,host_id)     values (68900,'343250')
insert into possess(id,host_id)     values (68974,'281229')
insert into possess(id,host_id)     values (69894,'352168')

insert into possess(id,host_id)     values (69921,'155689')
insert into possess(id,host_id)     values (70095,'353965')
insert into possess(id,host_id)     values (70128,'354330')
insert into possess(id,host_id)     values (70609,'72062')
insert into possess(id,host_id)     values (71010,'361855')
insert into possess(id,host_id)     values (71248,'363834')
insert into possess(id,host_id)     values (71366,'364955')
insert into possess(id,host_id)     values (71384,'365153')
insert into possess(id,host_id)     values (71812,'369015')
insert into possess(id,host_id)     values (72190,'373085')
insert into possess(id,host_id)     values (72265,'340692')
insert into possess(id,host_id)     values (74073,'211877')
insert into possess(id,host_id)     values (74240,'389924')
insert into possess(id,host_id)     values (74333,'331328')
insert into possess(id,host_id)     values (74404,'391325')
insert into possess(id,host_id)     values (74680,'265109')
insert into possess(id,host_id)     values (74860,'394752')
insert into possess(id,host_id)     values (75193,'308875')
insert into possess(id,host_id)     values (75635,'401696')
insert into possess(id,host_id)     values (76761,'118971')
insert into possess(id,host_id)     values (77765,'417504')
insert into possess(id,host_id)     values (77936,'134355')
insert into possess(id,host_id)     values (78919,'422561')
insert into possess(id,host_id)     values (79067,'425506')
insert into possess(id,host_id)     values (79782,'430188')
insert into possess(id,host_id)     values (80493,'434987')
insert into possess(id,host_id)     values (80684,'417504')
insert into possess(id,host_id)     values (80700,'417504')
insert into possess(id,host_id)     values (80924,'438133')
insert into possess(id,host_id)     values (81739,'417504')
insert into possess(id,host_id)     values (82549,'448312')
insert into possess(id,host_id)     values (82550,'448312')
insert into possess(id,host_id)     values (82638,'449787')
insert into possess(id,host_id)     values (82928,'451545')
insert into possess(id,host_id)     values (83243,'453519')
insert into possess(id,host_id)     values (83446,'454756')
insert into possess(id,host_id)     values (83722,'456638')
insert into possess(id,host_id)     values (83847,'410094')
insert into possess(id,host_id)     values (84010,'417504')
insert into possess(id,host_id)     values (84059,'459054')
insert into possess(id,host_id)     values (84659,'462776')
insert into possess(id,host_id)     values (84905,'464506')
insert into possess(id,host_id)     values (85094,'322716')
insert into possess(id,host_id)     values (86215,'327900')
insert into possess(id,host_id)     values (89427,'116599')
insert into possess(id,host_id)     values (89621,'209460')
insert into possess(id,host_id)     values (93313,'25183')
insert into possess(id,host_id)     values (94035,'35375')
insert into possess(id,host_id)     values (94209,'503800')
insert into possess(id,host_id)     values (94477,'478395')
insert into possess(id,host_id)     values (94783,'473113')
insert into possess(id,host_id)     values (95747,'509341')
insert into possess(id,host_id)     values (95883,'509918')
insert into possess(id,host_id)     values (96471,'116599')
insert into possess(id,host_id)     values (98330,'31374')
insert into possess(id,host_id)     values (98663,'520279')
insert into possess(id,host_id)     values (99070,'522065')
insert into possess(id,host_id)     values (99085,'522164')
insert into possess(id,host_id)     values (100002,'523218')
insert into possess(id,host_id)     values (100184,'526653')
insert into possess(id,host_id)     values (100186,'526805')
insert into possess(id,host_id)     values (101053,'530032')
insert into possess(id,host_id)     values (102995,'178043')
insert into possess(id,host_id)     values (103161,'465278')
insert into possess(id,host_id)     values (103311,'417504')
insert into possess(id,host_id)     values (103806,'251176')
insert into possess(id,host_id)     values (105469,'547386')
insert into possess(id,host_id)     values (105510,'322716')
insert into possess(id,host_id)     values (106363,'551055')
insert into possess(id,host_id)     values (106647,'552679')
insert into possess(id,host_id)     values (107630,'306739')
insert into possess(id,host_id)     values (107895,'3088389')
insert into possess(id,host_id)     values (110739,'568568')
insert into possess(id,host_id)     values (112100,'572527')
insert into possess(id,host_id)     values (112304,'573316')
insert into possess(id,host_id)     values (112359,'571952')
insert into possess(id,host_id)     values (112435,'181376')
insert into possess(id,host_id)     values (113265,'314582')
insert into possess(id,host_id)     values (113945,'275582')
insert into possess(id,host_id)     values (114123,'579495')
insert into possess(id,host_id)     values (114229,'314941')
insert into possess(id,host_id)     values (114969,'582598')
insert into possess(id,host_id)     values (115535,'567187')
insert into possess(id,host_id)     values (115678,'127772')
insert into possess(id,host_id)     values (115748,'585166')
insert into possess(id,host_id)     values (116940,'209460')
insert into possess(id,host_id)     values (117425,'593115')
insert into possess(id,host_id)     values (118061,'2248897')
insert into possess(id,host_id)     values (118430,'585458')
insert into possess(id,host_id)     values (118680,'599354')
insert into possess(id,host_id)     values (120362,'138069')
insert into possess(id,host_id)     values (121687,'262812')
insert into possess(id,host_id)     values (121861,'611716')
insert into possess(id,host_id)     values (123784,'617990')
insert into possess(id,host_id)     values (125053,'622460')
insert into possess(id,host_id)     values (125163,'622855')
insert into possess(id,host_id)     values (125594,'308652')
insert into possess(id,host_id)     values (126443,'627217')
insert into possess(id,host_id)     values (126816,'620288')
insert into possess(id,host_id)     values (127387,'23276')
insert into possess(id,host_id)     values (128975,'256161')
insert into possess(id,host_id)     values (131154,'275563')
insert into possess(id,host_id)     values (132516,'85330')
insert into possess(id,host_id)     values (132570,'651390')
insert into possess(id,host_id)     values (132695,'507186')
insert into possess(id,host_id)     values (133025,'653405')
insert into possess(id,host_id)     values (134934,'652842')
insert into possess(id,host_id)     values (135393,'663764')
insert into possess(id,host_id)     values (135465,'663879')
insert into possess(id,host_id)     values (135706,'665013')
insert into possess(id,host_id)     values (136493,'663384')
insert into possess(id,host_id)     values (138216,'674970')
insert into possess(id,host_id)     values (139624,'680818')
insert into possess(id,host_id)     values (140133,'622866')
insert into possess(id,host_id)     values (140425,'683975')
insert into possess(id,host_id)     values (140973,'686147')
insert into possess(id,host_id)     values (141154,'686768')
insert into possess(id,host_id)     values (141335,'687361')
insert into possess(id,host_id)     values (141890,'689661')
insert into possess(id,host_id)     values (141984,'630453')
insert into possess(id,host_id)     values (142069,'277747')
insert into possess(id,host_id)     values (144087,'616825')
insert into possess(id,host_id)     values (144148,'299755')
insert into possess(id,host_id)     values (145064,'404424')
insert into possess(id,host_id)     values (145188,'703156')
insert into possess(id,host_id)     values (145994,'706418')
insert into possess(id,host_id)     values (146754,'709434')
insert into possess(id,host_id)     values (147586,'709334')
insert into possess(id,host_id)     values (148201,'715807')
insert into possess(id,host_id)     values (148259,'716064')
insert into possess(id,host_id)     values (148825,'718349')
insert into possess(id,host_id)     values (149287,'720320')
insert into possess(id,host_id)     values (149777,'716306')
insert into possess(id,host_id)     values (150804,'726333')
insert into possess(id,host_id)     values (151199,'722320')
insert into possess(id,host_id)     values (151478,'216191')
insert into possess(id,host_id)     values (152071,'731855')
insert into possess(id,host_id)     values (152078,'731904')
insert into possess(id,host_id)     values (152259,'256161')
insert into possess(id,host_id)     values (152263,'732535')
insert into possess(id,host_id)     values (152520,'733894')
insert into possess(id,host_id)     values (153405,'737585')
insert into possess(id,host_id)     values (153780,'739499')
insert into possess(id,host_id)     values (154934,'745069')
insert into possess(id,host_id)     values (155296,'656841')
insert into possess(id,host_id)     values (157673,'757166')
insert into possess(id,host_id)     values (158061,'758441')
insert into possess(id,host_id)     values (158176,'573065')
insert into possess(id,host_id)     values (158290,'759583')
insert into possess(id,host_id)     values (158913,'762563')
insert into possess(id,host_id)     values (158955,'465589')
insert into possess(id,host_id)     values (159749,'54275')
insert into possess(id,host_id)     values (159815,'54275')
insert into possess(id,host_id)     values (159913,'759883')
insert into possess(id,host_id)     values (160609,'769247')
insert into possess(id,host_id)     values (160994,'770831')
insert into possess(id,host_id)     values (161366,'733894')
insert into possess(id,host_id)     values (161394,'772300')
insert into possess(id,host_id)     values (161996,'1856604')
insert into possess(id,host_id)     values (162493,'776490')
insert into possess(id,host_id)     values (162508,'776645')
insert into possess(id,host_id)     values (163627,'242506')
insert into possess(id,host_id)     values (163809,'781647')
insert into possess(id,host_id)     values (163814,'627217')
insert into possess(id,host_id)     values (163836,'32169')
insert into possess(id,host_id)     values (164989,'69439')

insert into possess(id,host_id)     values (165080,'787273')
insert into possess(id,host_id)     values (165461,'867225')
insert into possess(id,host_id)     values (165824,'733894')
insert into possess(id,host_id)     values (166006,'791287')
insert into possess(id,host_id)     values (166172,'792159')
insert into possess(id,host_id)     values (166541,'793620')
insert into possess(id,host_id)     values (166983,'795640')
insert into possess(id,host_id)     values (167013,'306605')
insert into possess(id,host_id)     values (167017,'795889')
insert into possess(id,host_id)     values (167222,'22486')
insert into possess(id,host_id)     values (167482,'789257')
insert into possess(id,host_id)     values (168084,'800982')
insert into possess(id,host_id)     values (168123,'720558')
insert into possess(id,host_id)     values (168546,'803086')
insert into possess(id,host_id)     values (168810,'747698')
insert into possess(id,host_id)     values (169002,'805344')
insert into possess(id,host_id)     values (169152,'806112')
insert into possess(id,host_id)     values (169306,'806214')
insert into possess(id,host_id)     values (169464,'806774')
insert into possess(id,host_id)     values (169483,'807642')
insert into possess(id,host_id)     values (170420,'812814')
insert into possess(id,host_id)     values (170761,'67778')
insert into possess(id,host_id)     values (171776,'803086')
insert into possess(id,host_id)     values (172700,'302772')
insert into possess(id,host_id)     values (172870,'781647')
insert into possess(id,host_id)     values (173072,'826192')
insert into possess(id,host_id)     values (173151,'826459')
insert into possess(id,host_id)     values (173742,'829652')
insert into possess(id,host_id)     values (174527,'833926')
insert into possess(id,host_id)     values (174966,'836168')
insert into possess(id,host_id)     values (176135,'842125')
insert into possess(id,host_id)     values (176653,'844862')
insert into possess(id,host_id)     values (176962,'846309')

In [21]:
#table host
for i in range(500):
    try:
        sql="insert into host(host_id,host_name) \
        values ("+str(df["host_id"][i])+",\'"+str(df["host_name"][i])+"\'"+")"
        print(sql)
        mycursor.execute(sql)

        db.commit()
    except:
        print("Duplicate")

insert into host(host_id,host_name)         values (2787,'John')
Duplicate
insert into host(host_id,host_name)         values (2845,'Jennifer')
Duplicate
insert into host(host_id,host_name)         values (4632,'Elisabeth')
Duplicate
insert into host(host_id,host_name)         values (4869,'LisaRoxanne')
Duplicate
insert into host(host_id,host_name)         values (7192,'Laura')
Duplicate
insert into host(host_id,host_name)         values (7322,'Chris')
Duplicate
insert into host(host_id,host_name)         values (7356,'Garon')
Duplicate
insert into host(host_id,host_name)         values (8967,'Shunichi')
Duplicate
insert into host(host_id,host_name)         values (7490,'MaryEllen')
Duplicate
insert into host(host_id,host_name)         values (7549,'Ben')
Duplicate
insert into host(host_id,host_name)         values (7702,'Lena')
Duplicate
insert into host(host_id,host_name)         values (7989,'Kate')
Duplicate
insert into host(host_id,host_name)         values (9744,'Laurie')
Duplicate
insert into host(host_id,host_name)         values (11528,'Claudio')
Duplicate
insert into host(host_id,host_name)         values (11975,'Alina')
Duplicate
insert into host(host_id,host_name)         values (15991,'Allen & Irina')
Duplicate
insert into host(host_id,host_name)         values (17571,'Jane')
Duplicate
insert into host(host_id,host_name)         values (18946,'Doti')
Duplicate
insert into host(host_id,host_name)         values (20950,'Adam And Charity')
Duplicate
insert into host(host_id,host_name)         values (17985,'Sing')
Duplicate
insert into host(host_id,host_name)         values (21207,'Chaya')
Duplicate
insert into host(host_id,host_name)         values (22486,'Lisel')
Duplicate
insert into host(host_id,host_name)         values (22486,'Lisel')
Duplicate
insert into host(host_id,host_name)         values (22486,'Lisel')
Duplicate
insert into host(host_id,host_name)         values (25183,'Nathalie')
insert into host(host_id,host_name)         values (25326,'Gregory')
insert into host(host_id,host_name)         values (26394,'Claude & Sophie')
insert into host(host_id,host_name)         values (30193,'Tommi')
insert into host(host_id,host_name)         values (31374,'Shon')
insert into host(host_id,host_name)         values (21904,'Dana')
insert into host(host_id,host_name)         values (32294,'Ssameer Or Trip')
insert into host(host_id,host_name)         values (32045,'Teri')
insert into host(host_id,host_name)         values (32169,'Andrea')
insert into host(host_id,host_name)         values (32294,'Ssameer Or Trip')
Duplicate
insert into host(host_id,host_name)         values (35935,'Angela')
insert into host(host_id,host_name)         values (9744,'Laurie')
Duplicate
insert into host(host_id,host_name)         values (7355,'Vt')
insert into host(host_id,host_name)         values (44145,'Tyrome')
insert into host(host_id,host_name)         values (45445,'Harriet')
insert into host(host_id,host_name)         values (7549,'Ben')
Duplicate
insert into host(host_id,host_name)         values (46978,'Edward')
insert into host(host_id,host_name)         values (47610,'Abdul')
insert into host(host_id,host_name)         values (47618,'Yolande')
insert into host(host_id,host_name)         values (16800,'Cyn')
insert into host(host_id,host_name)         values (47727,'Earl')
insert into host(host_id,host_name)         values (49670,'Rana')
insert into host(host_id,host_name)         values (50124,'Orestes')
insert into host(host_id,host_name)         values (50148,'Adreinne')
insert into host(host_id,host_name)         values (50846,'Jennifer')
insert into host(host_id,host_name)         values (52335,'Alexander')
insert into host(host_id,host_name)         values (54275,'JT And Tiziana')
insert into host(host_id,host_name)         values (56094,'Joya')
insert into host(host_id,host_name)         values (56104,'James')
insert into host(host_id,host_name)         values (56246,'Jeanne')
insert into host(host_id,host_name)         values (56284,'Francesca')
insert into host(host_id,host_name)         values (56512,'Joanna')
insert into host(host_id,host_name)         values (59023,'Bianca')
insert into host(host_id,host_name)         values (59734,'Luiz')
insert into host(host_id,host_name)         values (32169,'Andrea')
Duplicate
insert into host(host_id,host_name)         values (60049,'Ted')
insert into host(host_id,host_name)         values (60252,'Cristina')
insert into host(host_id,host_name)         values (60278,'Petra')
insert into host(host_id,host_name)         values (61491,'D')
insert into host(host_id,host_name)         values (63588,'Dimitri')
insert into host(host_id,host_name)         values (63613,'Patricia')
insert into host(host_id,host_name)         values (63924,'Mark')
insert into host(host_id,host_name)         values (64056,'Sara')
insert into host(host_id,host_name)         values (64442,'Reka')
insert into host(host_id,host_name)         values (64522,'Daniel')
insert into host(host_id,host_name)         values (4396,'Casey')
insert into host(host_id,host_name)         values (65837,'Robin')
insert into host(host_id,host_name)         values (66035,'Anna')
insert into host(host_id,host_name)         values (66243,'Enzo')
insert into host(host_id,host_name)         values (68428,'Tye And Etienne')
insert into host(host_id,host_name)         values (68599,'George')
insert into host(host_id,host_name)         values (69829,'Josh')
insert into host(host_id,host_name)         values (69942,'Victoria')
insert into host(host_id,host_name)         values (70091,'Justin')
insert into host(host_id,host_name)         values (71512,'Blaise')
insert into host(host_id,host_name)         values (71876,'DAVID And RICK')
insert into host(host_id,host_name)         values (72014,'Lulú')
insert into host(host_id,host_name)         values (73051,'Sybilla')
insert into host(host_id,host_name)         values (73128,'JoLynn')
insert into host(host_id,host_name)         values (73469,'Gaia')
insert into host(host_id,host_name)         values (44263,'Ana')
insert into host(host_id,host_name)         values (74303,'Maggie')
insert into host(host_id,host_name)         values (74857,'Starlee')
insert into host(host_id,host_name)         values (62407,'Edward')
insert into host(host_id,host_name)         values (76627,'Pas')
insert into host(host_id,host_name)         values (72014,'Lulú')
Duplicate
insert into host(host_id,host_name)         values (961342,'Augustin')
insert into host(host_id,host_name)         values (78460,'Sean & Lynette')
insert into host(host_id,host_name)         values (51038,'Erica')
insert into host(host_id,host_name)         values (79070,'Tracy')
insert into host(host_id,host_name)         values (79402,'Christiana')
insert into host(host_id,host_name)         values (44145,'Tyrome')
Duplicate
insert into host(host_id,host_name)         values (42032,'Dana')
insert into host(host_id,host_name)         values (82685,'Elliott')
insert into host(host_id,host_name)         values (83257,'Olan')
insert into host(host_id,host_name)         values (87773,'Shelly')
insert into host(host_id,host_name)         values (32294,'Ssameer Or Trip')
Duplicate
insert into host(host_id,host_name)         values (11481,'Annette')
insert into host(host_id,host_name)         values (63318,'Meka')
insert into host(host_id,host_name)         values (93790,'Ann')
insert into host(host_id,host_name)         values (97219,'Seth')
insert into host(host_id,host_name)         values (97797,'Brenda')
insert into host(host_id,host_name)         values (87773,'Shelly')
Duplicate
insert into host(host_id,host_name)         values (105538,'Erik')
insert into host(host_id,host_name)         values (107628,'Dena')
insert into host(host_id,host_name)         values (109589,'Jessica')
insert into host(host_id,host_name)         values (59734,'Luiz')
Duplicate
insert into host(host_id,host_name)         values (51038,'Erica')
Duplicate
insert into host(host_id,host_name)         values (112793,'Sally')
insert into host(host_id,host_name)         values (42273,'Dani')
insert into host(host_id,host_name)         values (72062,'Bruce')
insert into host(host_id,host_name)         values (115157,'Nimo')
insert into host(host_id,host_name)         values (115307,'Alexandra')

insert into host(host_id,host_name)         values (115560,'Stacy')
insert into host(host_id,host_name)         values (72062,'Bruce')
Duplicate
insert into host(host_id,host_name)         values (118971,'Evelyn')
insert into host(host_id,host_name)         values (119510,'Emma')
insert into host(host_id,host_name)         values (119588,'Vero')
insert into host(host_id,host_name)         values (119900,'Sylvie')
insert into host(host_id,host_name)         values (120223,'Jen')
insert into host(host_id,host_name)         values (65091,'Kay')
insert into host(host_id,host_name)         values (6197784,'Jo')
insert into host(host_id,host_name)         values (124352,'Lisa')
insert into host(host_id,host_name)         values (124797,'Fernando And Lenin')
insert into host(host_id,host_name)         values (35935,'Angela')
Duplicate
insert into host(host_id,host_name)         values (126607,'Laurine')
insert into host(host_id,host_name)         values (127608,'Chris')
insert into host(host_id,host_name)         values (125857,'Uli')
insert into host(host_id,host_name)         values (129352,'Sol')
insert into host(host_id,host_name)         values (120335,'Cs')
insert into host(host_id,host_name)         values (117287,'Lara')
insert into host(host_id,host_name)         values (135619,'Tom')
insert into host(host_id,host_name)         values (137292,'Sunder')
insert into host(host_id,host_name)         values (137814,'Waldemar')
insert into host(host_id,host_name)         values (137974,'Khem')
insert into host(host_id,host_name)         values (116599,'Sahr')
insert into host(host_id,host_name)         values (138579,'Ali+Scott')
insert into host(host_id,host_name)         values (139612,'Elisabeth')
insert into host(host_id,host_name)         values (139874,'Sarah')
insert into host(host_id,host_name)         values (140025,'Fredah')
insert into host(host_id,host_name)         values (137974,'Khem')
Duplicate
insert into host(host_id,host_name)         values (142833,'Katherine')
insert into host(host_id,host_name)         values (143027,'Ming')
insert into host(host_id,host_name)         values (143048,'Paula')
insert into host(host_id,host_name)         values (72014,'Lulú')
Duplicate
insert into host(host_id,host_name)         values (149929,'Obed')
insert into host(host_id,host_name)         values (120291,'Karen')
insert into host(host_id,host_name)         values (62165,'Michael')
insert into host(host_id,host_name)         values (142684,'White')
insert into host(host_id,host_name)         values (137432,'Paz')
insert into host(host_id,host_name)         values (157798,'Irene')
insert into host(host_id,host_name)         values (158284,'Karene')
insert into host(host_id,host_name)         values (159370,'Viviana')
insert into host(host_id,host_name)         values (92788,'Sara')
insert into host(host_id,host_name)         values (165789,'Sarah')
insert into host(host_id,host_name)         values (168417,'Marie')
insert into host(host_id,host_name)         values (168525,'Gus')
insert into host(host_id,host_name)         values (110506,'Myung')
insert into host(host_id,host_name)         values (170510,'Renée')
insert into host(host_id,host_name)         values (171851,'Henry')
insert into host(host_id,host_name)         values (174025,'Sylvia')
insert into host(host_id,host_name)         values (180083,'Syl')
insert into host(host_id,host_name)         values (181167,'Lorenzo')
insert into host(host_id,host_name)         values (137814,'Waldemar')
Duplicate
insert into host(host_id,host_name)         values (11481,'Annette')
Duplicate
insert into host(host_id,host_name)         values (185978,'Newyorkroomwithaview')
insert into host(host_id,host_name)         values (177536,'Tessa')
insert into host(host_id,host_name)         values (190409,'Waundell')
insert into host(host_id,host_name)         values (193360,'Young')
insert into host(host_id,host_name)         values (72062,'Bruce')
Duplicate
insert into host(host_id,host_name)         values (193722,'Coral')
insert into host(host_id,host_name)         values (181376,'Carol')
insert into host(host_id,host_name)         values (193637,'Sara')
insert into host(host_id,host_name)         values (126607,'Laurine')
Duplicate
insert into host(host_id,host_name)         values (201297,'Myrna')
insert into host(host_id,host_name)         values (202249,'Campbell')
insert into host(host_id,host_name)         values (67778,'Doug')
insert into host(host_id,host_name)         values (204539,'Mark')
insert into host(host_id,host_name)         values (867225,'Rahul')
insert into host(host_id,host_name)         values (204724,'Miyoung')
insert into host(host_id,host_name)         values (8198,'Monica')
insert into host(host_id,host_name)         values (209460,'Marylyn')
insert into host(host_id,host_name)         values (210746,'Kathleen R.')
insert into host(host_id,host_name)         values (212722,'Teresa')
insert into host(host_id,host_name)         values (214148,'Robert')
insert into host(host_id,host_name)         values (214287,'Alex')
insert into host(host_id,host_name)         values (218404,'Claudia')
insert into host(host_id,host_name)         values (221873,'Shane')
insert into host(host_id,host_name)         values (9744,'Laurie')
Duplicate
insert into host(host_id,host_name)         values (236421,'Jessica')
insert into host(host_id,host_name)         values (236655,'Erina')
insert into host(host_id,host_name)         values (237329,'Lee')
insert into host(host_id,host_name)         values (27848,'Jullett')
insert into host(host_id,host_name)         values (240360,'Marlaine')
insert into host(host_id,host_name)         values (247432,'Charlotte')
insert into host(host_id,host_name)         values (204539,'Mark')
Duplicate
insert into host(host_id,host_name)         values (204539,'Mark')
Duplicate
insert into host(host_id,host_name)         values (204539,'Mark')
Duplicate
insert into host(host_id,host_name)         values (10889,'Bob')
insert into host(host_id,host_name)         values (255583,'Anka')
insert into host(host_id,host_name)         values (253385,'Douglas')
insert into host(host_id,host_name)         values (210746,'Kathleen R.')
Duplicate
insert into host(host_id,host_name)         values (256161,'Wayne')
insert into host(host_id,host_name)         values (190409,'Waundell')
Duplicate
insert into host(host_id,host_name)         values (258164,'Jenny')
insert into host(host_id,host_name)         values (260709,'Paul')
insert into host(host_id,host_name)         values (262138,'Tami')
insert into host(host_id,host_name)         values (88209,'Jason')
insert into host(host_id,host_name)         values (263414,'Pete')
insert into host(host_id,host_name)         values (168525,'Gus')
Duplicate
insert into host(host_id,host_name)         values (264928,'Sally')
insert into host(host_id,host_name)         values (267593,'Leonardo')
insert into host(host_id,host_name)         values (268014,'Alex')
insert into host(host_id,host_name)         values (256161,'Wayne')
Duplicate
insert into host(host_id,host_name)         values (272006,'Vasili')
insert into host(host_id,host_name)         values (199392,'S.M.')
insert into host(host_id,host_name)         values (239208,'Ori')
insert into host(host_id,host_name)         values (274557,'Ana')
insert into host(host_id,host_name)         values (275459,'I')
insert into host(host_id,host_name)         values (275578,'R')
insert into host(host_id,host_name)         values (276291,'Simon')
insert into host(host_id,host_name)         values (277379,'Agnes')
insert into host(host_id,host_name)         values (277394,'Linda')
insert into host(host_id,host_name)         values (279797,'Dave')
insert into host(host_id,host_name)         values (282927,'Drica')
insert into host(host_id,host_name)         values (204539,'Mark')
Duplicate
insert into host(host_id,host_name)         values (274782,'Betty')
insert into host(host_id,host_name)         values (186084,'Ricardo & Ashlie')
insert into host(host_id,host_name)         values (288031,'Leslie')
insert into host(host_id,host_name)         values (289653,'Harrison')
insert into host(host_id,host_name)         values (99212,'Jessica')
insert into host(host_id,host_name)         values (292204,'Blanca')
insert into host(host_id,host_name)         values (256161,'Wayne')
Duplicate
insert into host(host_id,host_name)         values (249372,'Cynthia')
insert into host(host_id,host_name)         values (292630,'Mich')
insert into host(host_id,host_name)         values (293394,'Rachel')
insert into host(host_id,host_name)         values (126607,'Laurine')
Duplicate
insert into host(host_id,host_name)         values (295760,'Greta')
insert into host(host_id,host_name)         values (291112,'Frank')
insert into host(host_id,host_name)         values (297176,'Bethania')
insert into host(host_id,host_name)         values (297769,'Tunji')
insert into host(host_id,host_name)         values (23619,'Anna/Fonzy')
insert into host(host_id,host_name)         values (281764,'Colette&Sean')
insert into host(host_id,host_name)         values (303882,'Brie')
insert into host(host_id,host_name)         values (197755,'Sheila')
insert into host(host_id,host_name)         values (303939,'Lissette')
insert into host(host_id,host_name)         values (303939,'Lissette')
Duplicate
insert into host(host_id,host_name)         values (303939,'Lissette')
Duplicate
insert into host(host_id,host_name)         values (306545,'Olivia')
insert into host(host_id,host_name)         values (306605,'Daniel')
insert into host(host_id,host_name)         values (306739,'Maya')
insert into host(host_id,host_name)         values (308875,'Scott')
insert into host(host_id,host_name)         values (303939,'Lissette')
Duplicate
insert into host(host_id,host_name)         values (307962,'Dennis & Naoko')
insert into host(host_id,host_name)         values (308652,'Antonín')
insert into host(host_id,host_name)         values (310458,'Emily')
insert into host(host_id,host_name)         values (295128,'Carol Gloria')
insert into host(host_id,host_name)         values (310670,'Vie')
insert into host(host_id,host_name)         values (170510,'Renée')
Duplicate
insert into host(host_id,host_name)         values (306545,'Olivia')
Duplicate
insert into host(host_id,host_name)         values (311286,'Helene')
insert into host(host_id,host_name)         values (312288,'Paula')
insert into host(host_id,host_name)         values (312722,'Kristian & Di')
insert into host(host_id,host_name)         values (146944,'David')
insert into host(host_id,host_name)         values (313317,'Niya')
insert into host(host_id,host_name)         values (311286,'Helene')
Duplicate
insert into host(host_id,host_name)         values (314256,'Debbie')
insert into host(host_id,host_name)         values (314582,'Anthony')
insert into host(host_id,host_name)         values (7310,'Tilly')
insert into host(host_id,host_name)         values (46978,'Edward')
Duplicate
insert into host(host_id,host_name)         values (317809,'Claire')
insert into host(host_id,host_name)         values (319092,'Juhli')
insert into host(host_id,host_name)         values (320422,'Marlon')
insert into host(host_id,host_name)         values (320450,'Mary D')
insert into host(host_id,host_name)         values (320761,'Valerie')
insert into host(host_id,host_name)         values (320538,'Larissa')
insert into host(host_id,host_name)         values (321756,'Eric')
insert into host(host_id,host_name)         values (321934,'Jessica')
insert into host(host_id,host_name)         values (322884,'Melissa')
insert into host(host_id,host_name)         values (322716,'Alex')
insert into host(host_id,host_name)         values (324460,'Samir')
insert into host(host_id,host_name)         values (314941,'Tony')
insert into host(host_id,host_name)         values (325389,'Luis Fernando')
insert into host(host_id,host_name)         values (136227,'Henning')
insert into host(host_id,host_name)         values (327673,'Stefano')
insert into host(host_id,host_name)         values (329436,'Jana')
insert into host(host_id,host_name)         values (101597,'Per')
insert into host(host_id,host_name)         values (330347,'Adrienne')

insert into host(host_id,host_name)         values (332189,'Elise')
insert into host(host_id,host_name)         values (323517,'Deda')
insert into host(host_id,host_name)         values (338454,'Share')
insert into host(host_id,host_name)         values (240427,'Naimah')
insert into host(host_id,host_name)         values (342054,'Violetta')
insert into host(host_id,host_name)         values (282655,'Jenna')
insert into host(host_id,host_name)         values (343250,'Jason')
insert into host(host_id,host_name)         values (281229,'Alicia')
insert into host(host_id,host_name)         values (352168,'Silvia')
insert into host(host_id,host_name)         values (155689,'Joab')
insert into host(host_id,host_name)         values (353965,'Mary And Geoff')
insert into host(host_id,host_name)         values (354330,'Eyal')
insert into host(host_id,host_name)         values (72062,'Bruce')
Duplicate
insert into host(host_id,host_name)         values (361855,'Kurt')
insert into host(host_id,host_name)         values (363834,'Jennifer')
insert into host(host_id,host_name)         values (364955,'Ruperto')
insert into host(host_id,host_name)         values (365153,'Ben')
insert into host(host_id,host_name)         values (369015,'Thai')
insert into host(host_id,host_name)         values (373085,'Hudson')
insert into host(host_id,host_name)         values (340692,'Vanessa')
insert into host(host_id,host_name)         values (211877,'Daniel')
insert into host(host_id,host_name)         values (389924,'Patty')
insert into host(host_id,host_name)         values (331328,'Amir')
insert into host(host_id,host_name)         values (391325,'G & S')
insert into host(host_id,host_name)         values (265109,'Nazleen')
insert into host(host_id,host_name)         values (394752,'Allison')
insert into host(host_id,host_name)         values (308875,'Scott')
Duplicate
insert into host(host_id,host_name)         values (401696,'Patricia')
insert into host(host_id,host_name)         values (118971,'Evelyn')
Duplicate
insert into host(host_id,host_name)         values (417504,'The Box House Hotel')
insert into host(host_id,host_name)         values (134355,'Moss Owen')
insert into host(host_id,host_name)         values (422561,'Nancy')
insert into host(host_id,host_name)         values (425506,'Bliss')
insert into host(host_id,host_name)         values (430188,'Pam')
insert into host(host_id,host_name)         values (434987,'Jennifer')
insert into host(host_id,host_name)         values (417504,'The Box House Hotel')
Duplicate
insert into host(host_id,host_name)         values (417504,'The Box House Hotel')
Duplicate
insert into host(host_id,host_name)         values (438133,'Ellis')
insert into host(host_id,host_name)         values (417504,'The Box House Hotel')
Duplicate
insert into host(host_id,host_name)         values (448312,'Christopher')
insert into host(host_id,host_name)         values (448312,'Christopher')
Duplicate
insert into host(host_id,host_name)         values (449787,'Sarah')
insert into host(host_id,host_name)         values (451545,'Ruthven')
insert into host(host_id,host_name)         values (453519,'Julian')
insert into host(host_id,host_name)         values (454756,'Leslie')
insert into host(host_id,host_name)         values (456638,'Sophie')
insert into host(host_id,host_name)         values (410094,'Yvette')
insert into host(host_id,host_name)         values (417504,'The Box House Hotel')
Duplicate
insert into host(host_id,host_name)         values (459054,'Famous')
insert into host(host_id,host_name)         values (462776,'Kyle')
insert into host(host_id,host_name)         values (464506,'Ange')
insert into host(host_id,host_name)         values (322716,'Alex')
Duplicate
insert into host(host_id,host_name)         values (327900,'T')
insert into host(host_id,host_name)         values (116599,'Sahr')
Duplicate
insert into host(host_id,host_name)         values (209460,'Marylyn')
Duplicate
insert into host(host_id,host_name)         values (25183,'Nathalie')
Duplicate
insert into host(host_id,host_name)         values (35375,'Savannah')
insert into host(host_id,host_name)         values (503800,'Sadatu')
insert into host(host_id,host_name)         values (478395,'Jason')
insert into host(host_id,host_name)         values (473113,'Keishera')
insert into host(host_id,host_name)         values (509341,'Tessa')
insert into host(host_id,host_name)         values (509918,'Eduardo')
insert into host(host_id,host_name)         values (116599,'Sahr')
Duplicate
insert into host(host_id,host_name)         values (31374,'Shon')
Duplicate
insert into host(host_id,host_name)         values (520279,'Peter Michael')
insert into host(host_id,host_name)         values (522065,'Liz And Melissa')
insert into host(host_id,host_name)         values (522164,'Wanda')
insert into host(host_id,host_name)         values (523218,'Giorgio')
insert into host(host_id,host_name)         values (526653,'0')
insert into host(host_id,host_name)         values (526805,'Mi')
insert into host(host_id,host_name)         values (530032,'Lee And Tara')
insert into host(host_id,host_name)         values (178043,'Chas')
insert into host(host_id,host_name)         values (465278,'Ade')
insert into host(host_id,host_name)         values (417504,'The Box House Hotel')
Duplicate
insert into host(host_id,host_name)         values (251176,'Jason')
insert into host(host_id,host_name)         values (547386,'Michelle')
insert into host(host_id,host_name)         values (322716,'Alex')
Duplicate
insert into host(host_id,host_name)         values (551055,'Alicia')
insert into host(host_id,host_name)         values (552679,'Olivia')
insert into host(host_id,host_name)         values (306739,'Maya')
Duplicate
insert into host(host_id,host_name)         values (3088389,'Kai')
insert into host(host_id,host_name)         values (568568,'Driss')
insert into host(host_id,host_name)         values (572527,'Marine')
insert into host(host_id,host_name)         values (573316,'Kelli')
insert into host(host_id,host_name)         values (571952,'Olivia')
insert into host(host_id,host_name)         values (181376,'Carol')
Duplicate
insert into host(host_id,host_name)         values (314582,'Anthony')
Duplicate
insert into host(host_id,host_name)         values (275582,'Natalia')
insert into host(host_id,host_name)         values (579495,'Susi')
insert into host(host_id,host_name)         values (314941,'Tony')
Duplicate
insert into host(host_id,host_name)         values (582598,'Andrey')
insert into host(host_id,host_name)         values (567187,'Jane')
insert into host(host_id,host_name)         values (127772,'Will')
insert into host(host_id,host_name)         values (585166,'Lilly')
insert into host(host_id,host_name)         values (209460,'Marylyn')
Duplicate
insert into host(host_id,host_name)         values (593115,'LuLu')
insert into host(host_id,host_name)         values (2248897,'Roberta')
insert into host(host_id,host_name)         values (585458,'Paul')
insert into host(host_id,host_name)         values (599354,'Bobby')
insert into host(host_id,host_name)         values (138069,'Itamar')
insert into host(host_id,host_name)         values (262812,'Vikram')
insert into host(host_id,host_name)         values (611716,'Elizabeth')
insert into host(host_id,host_name)         values (617990,'Christopher')
insert into host(host_id,host_name)         values (622460,'Justin')
insert into host(host_id,host_name)         values (622855,'Rodney')
insert into host(host_id,host_name)         values (308652,'Antonín')
Duplicate
insert into host(host_id,host_name)         values (627217,'Seith')
insert into host(host_id,host_name)         values (620288,'Eric')
insert into host(host_id,host_name)         values (23276,'Katharine')
insert into host(host_id,host_name)         values (256161,'Wayne')
Duplicate
insert into host(host_id,host_name)         values (275563,'Lauren')
insert into host(host_id,host_name)         values (85330,'Jean')
insert into host(host_id,host_name)         values (651390,'Catherine')
insert into host(host_id,host_name)         values (507186,'Holly')
insert into host(host_id,host_name)         values (653405,'Tracy')
insert into host(host_id,host_name)         values (652842,'Giovanni')
insert into host(host_id,host_name)         values (663764,'Karen')
insert into host(host_id,host_name)         values (663879,'Christopher')
insert into host(host_id,host_name)         values (665013,'Jeff')
insert into host(host_id,host_name)         values (663384,'Irena')
insert into host(host_id,host_name)         values (674970,'Michael')
insert into host(host_id,host_name)         values (680818,'Jessica')
insert into host(host_id,host_name)         values (622866,'Daniel')
insert into host(host_id,host_name)         values (683975,'Ivy')
insert into host(host_id,host_name)         values (686147,'Dave')
insert into host(host_id,host_name)         values (686768,'Mark')
insert into host(host_id,host_name)         values (687361,'Orna')
insert into host(host_id,host_name)         values (689661,'Allison')
insert into host(host_id,host_name)         values (630453,'Vanessa')
insert into host(host_id,host_name)         values (277747,'Josh')
insert into host(host_id,host_name)         values (616825,'Rinaldo')
insert into host(host_id,host_name)         values (299755,'Jonathan')
insert into host(host_id,host_name)         values (404424,'Oliver')
insert into host(host_id,host_name)         values (703156,'Kristin')
insert into host(host_id,host_name)         values (706418,'Carolyn')
insert into host(host_id,host_name)         values (709434,'Meighan')
insert into host(host_id,host_name)         values (709334,'Julie')
insert into host(host_id,host_name)         values (715807,'John')
insert into host(host_id,host_name)         values (716064,'Mihalis')
insert into host(host_id,host_name)         values (718349,'B.')
insert into host(host_id,host_name)         values (720320,'Nancy')
insert into host(host_id,host_name)         values (716306,'Dee, Dre & Mama Shelley')
insert into host(host_id,host_name)         values (726333,'Peter')
insert into host(host_id,host_name)         values (722320,'Gladys & Bob')
insert into host(host_id,host_name)         values (216191,'M')
insert into host(host_id,host_name)         values (731855,'Wendy')
insert into host(host_id,host_name)         values (731904,'Ewelina')
insert into host(host_id,host_name)         values (256161,'Wayne')
Duplicate
insert into host(host_id,host_name)         values (732535,'William')
insert into host(host_id,host_name)         values (733894,'Lucy')
insert into host(host_id,host_name)         values (737585,'Pat')
insert into host(host_id,host_name)         values (739499,'Donna')
insert into host(host_id,host_name)         values (745069,'Kimberly')
insert into host(host_id,host_name)         values (656841,'Meredith')
insert into host(host_id,host_name)         values (757166,'Tokunbo')
insert into host(host_id,host_name)         values (758441,'Fred')
insert into host(host_id,host_name)         values (573065,'Laura')
insert into host(host_id,host_name)         values (759583,'Pepe')
insert into host(host_id,host_name)         values (762563,'Lennny & Megan')
insert into host(host_id,host_name)         values (465589,'Amia')
insert into host(host_id,host_name)         values (54275,'JT And Tiziana')
Duplicate
insert into host(host_id,host_name)         values (54275,'JT And Tiziana')
Duplicate
insert into host(host_id,host_name)         values (759883,'Kaye')
insert into host(host_id,host_name)         values (769247,'Ligia')
insert into host(host_id,host_name)         values (770831,'James')

insert into host(host_id,host_name)         values (733894,'Lucy')
Duplicate
insert into host(host_id,host_name)         values (772300,'Alain')
insert into host(host_id,host_name)         values (1856604,'Robert "Bob"')
insert into host(host_id,host_name)         values (776490,'Andres')
insert into host(host_id,host_name)         values (776645,'Placid')
insert into host(host_id,host_name)         values (242506,'Jsun')
insert into host(host_id,host_name)         values (781647,'Jorin')
insert into host(host_id,host_name)         values (627217,'Seith')
Duplicate
insert into host(host_id,host_name)         values (32169,'Andrea')
Duplicate
insert into host(host_id,host_name)         values (69439,'Jade')
insert into host(host_id,host_name)         values (787273,'Smadar')
insert into host(host_id,host_name)         values (867225,'Rahul')
Duplicate
insert into host(host_id,host_name)         values (733894,'Lucy')
Duplicate
insert into host(host_id,host_name)         values (791287,'Giancarlo')
insert into host(host_id,host_name)         values (792159,'Wanda')
insert into host(host_id,host_name)         values (793620,'Yvette')
insert into host(host_id,host_name)         values (795640,'Jilly')
insert into host(host_id,host_name)         values (306605,'Daniel')
Duplicate
insert into host(host_id,host_name)         values (795889,'Adam')
insert into host(host_id,host_name)         values (22486,'Lisel')
Duplicate
insert into host(host_id,host_name)         values (789257,'Barbara')
insert into host(host_id,host_name)         values (800982,'Chris')
insert into host(host_id,host_name)         values (720558,'Sara')
insert into host(host_id,host_name)         values (803086,'Benton')
insert into host(host_id,host_name)         values (747698,'Linda & Chris')
insert into host(host_id,host_name)         values (805344,'Alec')
insert into host(host_id,host_name)         values (806112,'Julia')
insert into host(host_id,host_name)         values (806214,'Vanessa')
insert into host(host_id,host_name)         values (806774,'Ali & SweetPea')
insert into host(host_id,host_name)         values (807642,'Jeffrey')
insert into host(host_id,host_name)         values (812814,'Lena')
insert into host(host_id,host_name)         values (67778,'Doug')
Duplicate
insert into host(host_id,host_name)         values (803086,'Benton')
Duplicate
insert into host(host_id,host_name)         values (302772,'Cheryl')
insert into host(host_id,host_name)         values (781647,'Jorin')
Duplicate
insert into host(host_id,host_name)         values (826192,'Lewis')
insert into host(host_id,host_name)         values (826459,'Jane')
insert into host(host_id,host_name)         values (829652,'Donna')
insert into host(host_id,host_name)         values (833926,'Kris')
insert into host(host_id,host_name)         values (836168,'Henry')
insert into host(host_id,host_name)         values (842125,'Jennifer')
insert into host(host_id,host_name)         values (844862,'Cj')
insert into host(host_id,host_name)         values (846309,'Dani')

In [57]:
#table position
for i in range(500):
    sql="insert into position(neighbourhood,neighbourhood_group) values(\'"+str(df["neighbourhood"][i])+"\',\'"+str(df["neighbourhood_group"][i])+"\'"+")"
    print(sql)
    mycursor.execute(sql)

    db.commit()
#It's strange that I get an error with a code of 1064 (42000), but I don't have a column name which is the same as one of the reserved words.
#But We can still fill the table using the workbench.

insert into position(neighbourhood,neighbourhood_group) values('Kensington','Brooklyn')

ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'position(neighbourhood,neighbourhood_group) values('Kensington','Brooklyn')' at line 1

In [59]:
#table locate
for i in range(500):
    sql="insert into locate(id,neighbourhood) \
    values ("+str(df["id"][i])+",\'"+str(df["neighbourhood"][i])+"\'"+")"
    print(sql)
    mycursor.execute(sql)

    db.commit()

insert into locate(id,neighbourhood)     values (2539,'Kensington')
insert into locate(id,neighbourhood)     values (2595,'Midtown')
insert into locate(id,neighbourhood)     values (3647,'Harlem')
insert into locate(id,neighbourhood)     values (3831,'Clinton Hill')
insert into locate(id,neighbourhood)     values (5022,'East Harlem')
insert into locate(id,neighbourhood)     values (5099,'Murray Hill')
insert into locate(id,neighbourhood)     values (5121,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (5178,'Hell s Kitchen')
insert into locate(id,neighbourhood)     values (5203,'Upper West Side')
insert into locate(id,neighbourhood)     values (5238,'Chinatown')
insert into locate(id,neighbourhood)     values (5295,'Upper West Side')
insert into locate(id,neighbourhood)     values (5441,'Hell s Kitchen')
insert into locate(id,neighbourhood)     values (5803,'South Slope')
insert into locate(id,neighbourhood)     values (6021,'Upper West Side')
insert into locate(id,neighbourhood)     values (6090,'West Village')
insert into locate(id,neighbourhood)     values (6848,'Williamsburg')
insert into locate(id,neighbourhood)     values (7097,'Fort Greene')
insert into locate(id,neighbourhood)     values (7322,'Chelsea')
insert into locate(id,neighbourhood)     values (7726,'Crown Heights')
insert into locate(id,neighbourhood)     values (7750,'East Harlem')
insert into locate(id,neighbourhood)     values (7801,'Williamsburg')
insert into locate(id,neighbourhood)     values (8024,'Park Slope')
insert into locate(id,neighbourhood)     values (8025,'Park Slope')
insert into locate(id,neighbourhood)     values (8110,'Park Slope')
insert into locate(id,neighbourhood)     values (8490,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (8505,'Windsor Terrace')
insert into locate(id,neighbourhood)     values (8700,'Inwood')
insert into locate(id,neighbourhood)     values (9357,'Hell s Kitchen')
insert into locate(id,neighbourhood)     values (9518,'Inwood')
insert into locate(id,neighbourhood)     values (9657,'East Village')
insert into locate(id,neighbourhood)     values (9668,'Harlem')
insert into locate(id,neighbourhood)     values (9704,'Harlem')
insert into locate(id,neighbourhood)     values (9782,'Greenpoint')
insert into locate(id,neighbourhood)     values (9783,'Harlem')
insert into locate(id,neighbourhood)     values (10452,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (10962,'South Slope')
insert into locate(id,neighbourhood)     values (11452,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (11708,'Bushwick')
insert into locate(id,neighbourhood)     values (11943,'Flatbush')
insert into locate(id,neighbourhood)     values (12048,'Lower East Side')
insert into locate(id,neighbourhood)     values (12192,'East Village')
insert into locate(id,neighbourhood)     values (12299,'South Slope')
insert into locate(id,neighbourhood)     values (12303,'Fort Greene')
insert into locate(id,neighbourhood)     values (12318,'Upper West Side')
insert into locate(id,neighbourhood)     values (12343,'Harlem')
insert into locate(id,neighbourhood)     values (12627,'Prospect-Lefferts Gardens')
insert into locate(id,neighbourhood)     values (12937,'Long Island City')
insert into locate(id,neighbourhood)     values (12940,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (13050,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (13394,'Fort Greene')
insert into locate(id,neighbourhood)     values (13808,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (14287,'Upper West Side')
insert into locate(id,neighbourhood)     values (14290,'Williamsburg')
insert into locate(id,neighbourhood)     values (14314,'Greenpoint')
insert into locate(id,neighbourhood)     values (14322,'Kips Bay')
insert into locate(id,neighbourhood)     values (14377,'Williamsburg')
insert into locate(id,neighbourhood)     values (14991,'Lower East Side')
insert into locate(id,neighbourhood)     values (15220,'Hell s Kitchen')
insert into locate(id,neighbourhood)     values (15338,'Greenpoint')
insert into locate(id,neighbourhood)     values (15341,'SoHo')
insert into locate(id,neighbourhood)     values (15385,'Williamsburg')
insert into locate(id,neighbourhood)     values (15396,'Chelsea')
insert into locate(id,neighbourhood)     values (15711,'Upper East Side')
insert into locate(id,neighbourhood)     values (16326,'Prospect Heights')
insert into locate(id,neighbourhood)     values (16338,'Clinton Hill')
insert into locate(id,neighbourhood)     values (16421,'Hell s Kitchen')
insert into locate(id,neighbourhood)     values (16458,'Park Slope')
insert into locate(id,neighbourhood)     values (16580,'East Village')
insert into locate(id,neighbourhood)     values (16595,'Williamsburg')
insert into locate(id,neighbourhood)     values (16821,'East Village')
insert into locate(id,neighbourhood)     values (16974,'East Harlem')
insert into locate(id,neighbourhood)     values (17037,'East Village')
insert into locate(id,neighbourhood)     values (17092,'Hell s Kitchen')
insert into locate(id,neighbourhood)     values (17693,'Washington Heights')
insert into locate(id,neighbourhood)     values (17747,'Clinton Hill')
insert into locate(id,neighbourhood)     values (18127,'East Village')
insert into locate(id,neighbourhood)     values (18152,'Upper East Side')
insert into locate(id,neighbourhood)     values (18198,'Woodside')
insert into locate(id,neighbourhood)     values (18590,'Fort Greene')
insert into locate(id,neighbourhood)     values (18728,'Chelsea')
insert into locate(id,neighbourhood)     values (18764,'Williamsburg')
insert into locate(id,neighbourhood)     values (19159,'Harlem')
insert into locate(id,neighbourhood)     values (19169,'Lower East Side')
insert into locate(id,neighbourhood)     values (19282,'Flatbush')
insert into locate(id,neighbourhood)     values (19319,'Lower East Side')
insert into locate(id,neighbourhood)     values (19601,'Brooklyn Heights')
insert into locate(id,neighbourhood)     values (19812,'Williamsburg')
insert into locate(id,neighbourhood)     values (20299,'East Village')
insert into locate(id,neighbourhood)     values (20300,'East Village')
insert into locate(id,neighbourhood)     values (20611,'Williamsburg')
insert into locate(id,neighbourhood)     values (20724,'Bushwick')
insert into locate(id,neighbourhood)     values (20734,'Prospect Heights')
insert into locate(id,neighbourhood)     values (20755,'Clinton Hill')
insert into locate(id,neighbourhood)     values (20853,'Prospect Heights')
insert into locate(id,neighbourhood)     values (20913,'Williamsburg')
insert into locate(id,neighbourhood)     values (21293,'Bushwick')
insert into locate(id,neighbourhood)     values (21456,'Upper West Side')
insert into locate(id,neighbourhood)     values (21644,'Harlem')
insert into locate(id,neighbourhood)     values (21794,'Chelsea')
insert into locate(id,neighbourhood)     values (22911,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (22918,'Harlem')
insert into locate(id,neighbourhood)     values (23135,'Carroll Gardens')
insert into locate(id,neighbourhood)     values (23501,'Washington Heights')
insert into locate(id,neighbourhood)     values (23686,'West Village')
insert into locate(id,neighbourhood)     values (24143,'Williamsburg')
insert into locate(id,neighbourhood)     values (24285,'Park Slope')
insert into locate(id,neighbourhood)     values (25235,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (25406,'Williamsburg')
insert into locate(id,neighbourhood)     values (25696,'Harlem')
insert into locate(id,neighbourhood)     values (26012,'Gowanus')
insert into locate(id,neighbourhood)     values (26362,'Hell s Kitchen')
insert into locate(id,neighbourhood)     values (26520,'Clinton Hill')
insert into locate(id,neighbourhood)     values (26559,'East Village')
insert into locate(id,neighbourhood)     values (26785,'South Slope')
insert into locate(id,neighbourhood)     values (26933,'East Village')
insert into locate(id,neighbourhood)     values (26954,'Kips Bay')
insert into locate(id,neighbourhood)     values (26969,'Williamsburg')
insert into locate(id,neighbourhood)     values (27006,'Upper West Side')
insert into locate(id,neighbourhood)     values (27385,'East Village')
insert into locate(id,neighbourhood)     values (27531,'South Slope')
insert into locate(id,neighbourhood)     values (27644,'Harlem')
insert into locate(id,neighbourhood)     values (27659,'South Slope')
insert into locate(id,neighbourhood)     values (27759,'Upper West Side')
insert into locate(id,neighbourhood)     values (27883,'East Village')
insert into locate(id,neighbourhood)     values (28321,'Prospect-Lefferts Gardens')
insert into locate(id,neighbourhood)     values (28396,'Williamsburg')
insert into locate(id,neighbourhood)     values (28907,'Upper East Side')
insert into locate(id,neighbourhood)     values (29012,'Washington Heights')
insert into locate(id,neighbourhood)     values (29013,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (29455,'Harlem')
insert into locate(id,neighbourhood)     values (29628,'Clinton Hill')
insert into locate(id,neighbourhood)     values (29683,'East Village')
insert into locate(id,neighbourhood)     values (30031,'Greenpoint')
insert into locate(id,neighbourhood)     values (30927,'Lower East Side')
insert into locate(id,neighbourhood)     values (31130,'Hell s Kitchen')
insert into locate(id,neighbourhood)     values (31555,'West Village')
insert into locate(id,neighbourhood)     values (31902,'Flatlands')
insert into locate(id,neighbourhood)     values (31994,'Clinton Hill')
insert into locate(id,neighbourhood)     values (32023,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (32037,'Clinton Hill')
insert into locate(id,neighbourhood)     values (32100,'Greenpoint')
insert into locate(id,neighbourhood)     values (32289,'Williamsburg')
insert into locate(id,neighbourhood)     values (32331,'Cobble Hill')
insert into locate(id,neighbourhood)     values (32363,'Flushing')
insert into locate(id,neighbourhood)     values (32965,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (32969,'Williamsburg')
insert into locate(id,neighbourhood)     values (33009,'Williamsburg')
insert into locate(id,neighbourhood)     values (33014,'East Village')
insert into locate(id,neighbourhood)     values (33223,'Williamsburg')
insert into locate(id,neighbourhood)     values (34760,'Fort Greene')
insert into locate(id,neighbourhood)     values (35526,'West Village')
insert into locate(id,neighbourhood)     values (36121,'Prospect Heights')
insert into locate(id,neighbourhood)     values (36133,'Williamsburg')
insert into locate(id,neighbourhood)     values (36442,'Prospect Heights')
insert into locate(id,neighbourhood)     values (36647,'East Harlem')
insert into locate(id,neighbourhood)     values (36703,'West Village')
insert into locate(id,neighbourhood)     values (36934,'Williamsburg')
insert into locate(id,neighbourhood)     values (38638,'Upper East Side')
insert into locate(id,neighbourhood)     values (38663,'Boerum Hill')
insert into locate(id,neighbourhood)     values (39267,'Upper East Side')
insert into locate(id,neighbourhood)     values (39282,'Williamsburg')
insert into locate(id,neighbourhood)     values (39593,'Sunnyside')
insert into locate(id,neighbourhood)     values (39704,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (40039,'DUMBO')
insert into locate(id,neighbourhood)     values (40453,'Upper East Side')
insert into locate(id,neighbourhood)     values (41348,'Gowanus')

insert into locate(id,neighbourhood)     values (41513,'Harlem')
insert into locate(id,neighbourhood)     values (42580,'Clinton Hill')
insert into locate(id,neighbourhood)     values (42729,'Carroll Gardens')
insert into locate(id,neighbourhood)     values (42882,'St. George')
insert into locate(id,neighbourhood)     values (43957,'Bushwick')
insert into locate(id,neighbourhood)     values (44096,'Highbridge')
insert into locate(id,neighbourhood)     values (44161,'Williamsburg')
insert into locate(id,neighbourhood)     values (44212,'East Village')
insert into locate(id,neighbourhood)     values (44221,'Financial District')
insert into locate(id,neighbourhood)     values (44229,'Fort Greene')
insert into locate(id,neighbourhood)     values (44288,'West Village')
insert into locate(id,neighbourhood)     values (44506,'Harlem')
insert into locate(id,neighbourhood)     values (45393,'West Village')
insert into locate(id,neighbourhood)     values (45542,'Harlem')
insert into locate(id,neighbourhood)     values (45556,'Fort Greene')
insert into locate(id,neighbourhood)     values (45910,'Ridgewood')
insert into locate(id,neighbourhood)     values (45936,'Morningside Heights')
insert into locate(id,neighbourhood)     values (45940,'Williamsburg')
insert into locate(id,neighbourhood)     values (46544,'Park Slope')
insert into locate(id,neighbourhood)     values (46723,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (46911,'Prospect Heights')
insert into locate(id,neighbourhood)     values (47199,'Upper East Side')
insert into locate(id,neighbourhood)     values (47362,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (47370,'Chelsea')
insert into locate(id,neighbourhood)     values (47926,'Hell s Kitchen')
insert into locate(id,neighbourhood)     values (48719,'Lower East Side')
insert into locate(id,neighbourhood)     values (50447,'South Slope')
insert into locate(id,neighbourhood)     values (51438,'Upper East Side')
insert into locate(id,neighbourhood)     values (51485,'Lower East Side')
insert into locate(id,neighbourhood)     values (51572,'Chelsea')
insert into locate(id,neighbourhood)     values (51850,'Jamaica')
insert into locate(id,neighbourhood)     values (53137,'Hell s Kitchen')
insert into locate(id,neighbourhood)     values (53196,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (53469,'Middle Village')
insert into locate(id,neighbourhood)     values (53470,'Ridgewood')
insert into locate(id,neighbourhood)     values (53477,'Middle Village')
insert into locate(id,neighbourhood)     values (54158,'Williamsburg')
insert into locate(id,neighbourhood)     values (54453,'Hell s Kitchen')
insert into locate(id,neighbourhood)     values (54466,'Harlem')
insert into locate(id,neighbourhood)     values (54508,'Prospect Heights')
insert into locate(id,neighbourhood)     values (54544,'Harlem')
insert into locate(id,neighbourhood)     values (54626,'Highbridge')
insert into locate(id,neighbourhood)     values (54860,'East Harlem')
insert into locate(id,neighbourhood)     values (55467,'Williamsburg')
insert into locate(id,neighbourhood)     values (55498,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (55668,'NoHo')
insert into locate(id,neighbourhood)     values (55737,'West Village')
insert into locate(id,neighbourhood)     values (55959,'Williamsburg')
insert into locate(id,neighbourhood)     values (55982,'Fort Greene')
insert into locate(id,neighbourhood)     values (56467,'East Village')
insert into locate(id,neighbourhood)     values (56525,'Greenpoint')
insert into locate(id,neighbourhood)     values (56859,'Harlem')
insert into locate(id,neighbourhood)     values (57166,'Ditmars Steinway')
insert into locate(id,neighbourhood)     values (57297,'Cobble Hill')
insert into locate(id,neighbourhood)     values (57468,'East Village')
insert into locate(id,neighbourhood)     values (57618,'Hell s Kitchen')
insert into locate(id,neighbourhood)     values (57740,'East Village')
insert into locate(id,neighbourhood)     values (57754,'Flatiron District')
insert into locate(id,neighbourhood)     values (57874,'Harlem')
insert into locate(id,neighbourhood)     values (58059,'Harlem')
insert into locate(id,neighbourhood)     values (58062,'Windsor Terrace')
insert into locate(id,neighbourhood)     values (58467,'Roosevelt Island')
insert into locate(id,neighbourhood)     values (59014,'Lower East Side')
insert into locate(id,neighbourhood)     values (59121,'Ridgewood')
insert into locate(id,neighbourhood)     values (59642,'Greenpoint')
insert into locate(id,neighbourhood)     values (59709,'Chinatown')
insert into locate(id,neighbourhood)     values (59855,'Midtown')
insert into locate(id,neighbourhood)     values (60164,'SoHo')
insert into locate(id,neighbourhood)     values (60457,'Greenwich Village')
insert into locate(id,neighbourhood)     values (60611,'East Harlem')
insert into locate(id,neighbourhood)     values (60666,'Harlem')
insert into locate(id,neighbourhood)     values (60673,'Harlem')
insert into locate(id,neighbourhood)     values (60680,'East Village')
insert into locate(id,neighbourhood)     values (60794,'Upper West Side')
insert into locate(id,neighbourhood)     values (60948,'East Harlem')
insert into locate(id,neighbourhood)     values (61167,'Little Italy')
insert into locate(id,neighbourhood)     values (61224,'Chelsea')
insert into locate(id,neighbourhood)     values (61406,'Harlem')
insert into locate(id,neighbourhood)     values (61492,'Chinatown')
insert into locate(id,neighbourhood)     values (61509,'Midtown')
insert into locate(id,neighbourhood)     values (62095,'East Flatbush')
insert into locate(id,neighbourhood)     values (62427,'East Village')
insert into locate(id,neighbourhood)     values (62430,'Bushwick')
insert into locate(id,neighbourhood)     values (62452,'Tompkinsville')
insert into locate(id,neighbourhood)     values (62461,'Tompkinsville')
insert into locate(id,neighbourhood)     values (62787,'Tompkinsville')
insert into locate(id,neighbourhood)     values (62891,'East Village')
insert into locate(id,neighbourhood)     values (62903,'Chelsea')
insert into locate(id,neighbourhood)     values (62925,'Greenpoint')
insert into locate(id,neighbourhood)     values (63299,'Williamsburg')
insert into locate(id,neighbourhood)     values (63320,'Tompkinsville')
insert into locate(id,neighbourhood)     values (63360,'Astoria')
insert into locate(id,neighbourhood)     values (63546,'Kensington')
insert into locate(id,neighbourhood)     values (63573,'Park Slope')
insert into locate(id,neighbourhood)     values (63588,'Clason Point')
insert into locate(id,neighbourhood)     values (63610,'Eastchester')
insert into locate(id,neighbourhood)     values (63657,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (63693,'East Village')
insert into locate(id,neighbourhood)     values (63719,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (63913,'Inwood')
insert into locate(id,neighbourhood)     values (64000,'Williamsburg')
insert into locate(id,neighbourhood)     values (64015,'East Village')
insert into locate(id,neighbourhood)     values (64107,'Crown Heights')
insert into locate(id,neighbourhood)     values (64277,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (64314,'Crown Heights')
insert into locate(id,neighbourhood)     values (64365,'Crown Heights')
insert into locate(id,neighbourhood)     values (64707,'Little Italy')
insert into locate(id,neighbourhood)     values (64837,'East Village')
insert into locate(id,neighbourhood)     values (65019,'Upper West Side')
insert into locate(id,neighbourhood)     values (65268,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (65556,'Williamsburg')
insert into locate(id,neighbourhood)     values (65562,'East Village')
insert into locate(id,neighbourhood)     values (65615,'Williamsburg')
insert into locate(id,neighbourhood)     values (65660,'Williamsburg')
insert into locate(id,neighbourhood)     values (65813,'Harlem')
insert into locate(id,neighbourhood)     values (65834,'Park Slope')
insert into locate(id,neighbourhood)     values (66008,'Carroll Gardens')
insert into locate(id,neighbourhood)     values (66026,'Crown Heights')
insert into locate(id,neighbourhood)     values (66251,'East Village')
insert into locate(id,neighbourhood)     values (66275,'Lower East Side')
insert into locate(id,neighbourhood)     values (66451,'Williamsburg')
insert into locate(id,neighbourhood)     values (66718,'Harlem')
insert into locate(id,neighbourhood)     values (66741,'Park Slope')
insert into locate(id,neighbourhood)     values (66974,'Gowanus')
insert into locate(id,neighbourhood)     values (67288,'East Harlem')
insert into locate(id,neighbourhood)     values (67299,'Williamsburg')
insert into locate(id,neighbourhood)     values (67397,'Morningside Heights')
insert into locate(id,neighbourhood)     values (68099,'Upper West Side')
insert into locate(id,neighbourhood)     values (68305,'Harlem')
insert into locate(id,neighbourhood)     values (68403,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (68735,'Upper West Side')
insert into locate(id,neighbourhood)     values (68765,'Carroll Gardens')
insert into locate(id,neighbourhood)     values (68900,'Greenpoint')
insert into locate(id,neighbourhood)     values (68974,'Little Italy')
insert into locate(id,neighbourhood)     values (69894,'Upper West Side')
insert into locate(id,neighbourhood)     values (69921,'Bushwick')
insert into locate(id,neighbourhood)     values (70095,'Inwood')
insert into locate(id,neighbourhood)     values (70128,'East Village')
insert into locate(id,neighbourhood)     values (70609,'East Village')
insert into locate(id,neighbourhood)     values (71010,'Washington Heights')
insert into locate(id,neighbourhood)     values (71248,'Chinatown')
insert into locate(id,neighbourhood)     values (71366,'West Village')
insert into locate(id,neighbourhood)     values (71384,'Greenpoint')

insert into locate(id,neighbourhood)     values (71812,'Kingsbridge')
insert into locate(id,neighbourhood)     values (72190,'Upper West Side')
insert into locate(id,neighbourhood)     values (72265,'Greenpoint')
insert into locate(id,neighbourhood)     values (74073,'Williamsburg')
insert into locate(id,neighbourhood)     values (74240,'Williamsburg')
insert into locate(id,neighbourhood)     values (74333,'East Harlem')
insert into locate(id,neighbourhood)     values (74404,'Harlem')
insert into locate(id,neighbourhood)     values (74680,'Astoria')
insert into locate(id,neighbourhood)     values (74860,'Greenpoint')
insert into locate(id,neighbourhood)     values (75193,'Williamsburg')
insert into locate(id,neighbourhood)     values (75635,'Lower East Side')
insert into locate(id,neighbourhood)     values (76761,'South Slope')
insert into locate(id,neighbourhood)     values (77765,'Greenpoint')
insert into locate(id,neighbourhood)     values (77936,'Hell s Kitchen')
insert into locate(id,neighbourhood)     values (78919,'Boerum Hill')
insert into locate(id,neighbourhood)     values (79067,'Clinton Hill')
insert into locate(id,neighbourhood)     values (79782,'Williamsburg')
insert into locate(id,neighbourhood)     values (80493,'East Village')
insert into locate(id,neighbourhood)     values (80684,'Greenpoint')
insert into locate(id,neighbourhood)     values (80700,'Greenpoint')
insert into locate(id,neighbourhood)     values (80924,'Park Slope')
insert into locate(id,neighbourhood)     values (81739,'Greenpoint')
insert into locate(id,neighbourhood)     values (82549,'Brooklyn Heights')
insert into locate(id,neighbourhood)     values (82550,'Brooklyn Heights')
insert into locate(id,neighbourhood)     values (82638,'East Village')
insert into locate(id,neighbourhood)     values (82928,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (83243,'Bushwick')
insert into locate(id,neighbourhood)     values (83446,'Fort Greene')
insert into locate(id,neighbourhood)     values (83722,'Williamsburg')
insert into locate(id,neighbourhood)     values (83847,'East Village')
insert into locate(id,neighbourhood)     values (84010,'Greenpoint')
insert into locate(id,neighbourhood)     values (84059,'Crown Heights')
insert into locate(id,neighbourhood)     values (84659,'East Village')
insert into locate(id,neighbourhood)     values (84905,'Two Bridges')
insert into locate(id,neighbourhood)     values (85094,'Crown Heights')
insert into locate(id,neighbourhood)     values (86215,'Lower East Side')
insert into locate(id,neighbourhood)     values (89427,'Clinton Hill')
insert into locate(id,neighbourhood)     values (89621,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (93313,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (94035,'Astoria')
insert into locate(id,neighbourhood)     values (94209,'Crown Heights')
insert into locate(id,neighbourhood)     values (94477,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (94783,'Crown Heights')
insert into locate(id,neighbourhood)     values (95747,'Williamsburg')
insert into locate(id,neighbourhood)     values (95883,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (96471,'Clinton Hill')
insert into locate(id,neighbourhood)     values (98330,'Kips Bay')
insert into locate(id,neighbourhood)     values (98663,'Chelsea')
insert into locate(id,neighbourhood)     values (99070,'East Harlem')
insert into locate(id,neighbourhood)     values (99085,'Fort Greene')
insert into locate(id,neighbourhood)     values (100002,'Washington Heights')
insert into locate(id,neighbourhood)     values (100184,'Queens Village')
insert into locate(id,neighbourhood)     values (100186,'Gowanus')
insert into locate(id,neighbourhood)     values (101053,'Williamsburg')
insert into locate(id,neighbourhood)     values (102995,'Upper West Side')
insert into locate(id,neighbourhood)     values (103161,'Williamsburg')
insert into locate(id,neighbourhood)     values (103311,'Greenpoint')
insert into locate(id,neighbourhood)     values (103806,'East Village')
insert into locate(id,neighbourhood)     values (105469,'Rockaway Beach')
insert into locate(id,neighbourhood)     values (105510,'Crown Heights')
insert into locate(id,neighbourhood)     values (106363,'Harlem')
insert into locate(id,neighbourhood)     values (106647,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (107630,'Greenpoint')
insert into locate(id,neighbourhood)     values (107895,'Upper West Side')
insert into locate(id,neighbourhood)     values (110739,'Midtown')
insert into locate(id,neighbourhood)     values (112100,'Crown Heights')
insert into locate(id,neighbourhood)     values (112304,'Harlem')
insert into locate(id,neighbourhood)     values (112359,'Upper East Side')
insert into locate(id,neighbourhood)     values (112435,'Fort Greene')
insert into locate(id,neighbourhood)     values (113265,'Crown Heights')
insert into locate(id,neighbourhood)     values (113945,'Hell s Kitchen')
insert into locate(id,neighbourhood)     values (114123,'South Slope')
insert into locate(id,neighbourhood)     values (114229,'Lower East Side')
insert into locate(id,neighbourhood)     values (114969,'Midtown')
insert into locate(id,neighbourhood)     values (115535,'Harlem')
insert into locate(id,neighbourhood)     values (115678,'Harlem')
insert into locate(id,neighbourhood)     values (115748,'Astoria')
insert into locate(id,neighbourhood)     values (116940,'Crown Heights')
insert into locate(id,neighbourhood)     values (117425,'Brooklyn Heights')
insert into locate(id,neighbourhood)     values (118061,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (118430,'Chelsea')
insert into locate(id,neighbourhood)     values (118680,'East Village')
insert into locate(id,neighbourhood)     values (120362,'Williamsburg')
insert into locate(id,neighbourhood)     values (121687,'Williamsburg')
insert into locate(id,neighbourhood)     values (121861,'Park Slope')
insert into locate(id,neighbourhood)     values (123784,'Harlem')
insert into locate(id,neighbourhood)     values (125053,'East Village')
insert into locate(id,neighbourhood)     values (125163,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (125594,'Kensington')
insert into locate(id,neighbourhood)     values (126443,'East Village')
insert into locate(id,neighbourhood)     values (126816,'Upper West Side')
insert into locate(id,neighbourhood)     values (127387,'Gowanus')
insert into locate(id,neighbourhood)     values (128975,'Harlem')
insert into locate(id,neighbourhood)     values (131154,'Greenpoint')
insert into locate(id,neighbourhood)     values (132516,'Forest Hills')
insert into locate(id,neighbourhood)     values (132570,'West Village')
insert into locate(id,neighbourhood)     values (132695,'Williamsburg')
insert into locate(id,neighbourhood)     values (133025,'Murray Hill')
insert into locate(id,neighbourhood)     values (134934,'Williamsburg')
insert into locate(id,neighbourhood)     values (135393,'East Flatbush')
insert into locate(id,neighbourhood)     values (135465,'Fort Greene')
insert into locate(id,neighbourhood)     values (135706,'Chelsea')
insert into locate(id,neighbourhood)     values (136493,'Park Slope')
insert into locate(id,neighbourhood)     values (138216,'Greenpoint')
insert into locate(id,neighbourhood)     values (139624,'Crown Heights')
insert into locate(id,neighbourhood)     values (140133,'Williamsburg')
insert into locate(id,neighbourhood)     values (140425,'Crown Heights')
insert into locate(id,neighbourhood)     values (140973,'East Village')
insert into locate(id,neighbourhood)     values (141154,'Boerum Hill')
insert into locate(id,neighbourhood)     values (141335,'Park Slope')
insert into locate(id,neighbourhood)     values (141890,'Nolita')
insert into locate(id,neighbourhood)     values (141984,'Nolita')
insert into locate(id,neighbourhood)     values (142069,'East Village')
insert into locate(id,neighbourhood)     values (144087,'Harlem')
insert into locate(id,neighbourhood)     values (144148,'East Village')
insert into locate(id,neighbourhood)     values (145064,'Williamsburg')
insert into locate(id,neighbourhood)     values (145188,'Chelsea')
insert into locate(id,neighbourhood)     values (145994,'Upper West Side')
insert into locate(id,neighbourhood)     values (146754,'Windsor Terrace')
insert into locate(id,neighbourhood)     values (147586,'Harlem')
insert into locate(id,neighbourhood)     values (148201,'Greenwich Village')
insert into locate(id,neighbourhood)     values (148259,'Williamsburg')
insert into locate(id,neighbourhood)     values (148825,'Upper West Side')
insert into locate(id,neighbourhood)     values (149287,'Upper East Side')
insert into locate(id,neighbourhood)     values (149777,'Woodlawn')
insert into locate(id,neighbourhood)     values (150804,'Lower East Side')
insert into locate(id,neighbourhood)     values (151199,'Astoria')
insert into locate(id,neighbourhood)     values (151478,'Williamsburg')
insert into locate(id,neighbourhood)     values (152071,'Park Slope')
insert into locate(id,neighbourhood)     values (152078,'East Village')

insert into locate(id,neighbourhood)     values (152259,'Harlem')
insert into locate(id,neighbourhood)     values (152263,'Harlem')
insert into locate(id,neighbourhood)     values (152520,'Sunnyside')
insert into locate(id,neighbourhood)     values (153405,'Greenpoint')
insert into locate(id,neighbourhood)     values (153780,'East Village')
insert into locate(id,neighbourhood)     values (154934,'Harlem')
insert into locate(id,neighbourhood)     values (155296,'Williamsburg')
insert into locate(id,neighbourhood)     values (157673,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (158061,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (158176,'Williamsburg')
insert into locate(id,neighbourhood)     values (158290,'Clinton Hill')
insert into locate(id,neighbourhood)     values (158913,'Greenpoint')
insert into locate(id,neighbourhood)     values (158955,'Williamsburg')
insert into locate(id,neighbourhood)     values (159749,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (159815,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (159913,'Chelsea')
insert into locate(id,neighbourhood)     values (160609,'Upper West Side')
insert into locate(id,neighbourhood)     values (160994,'East Village')
insert into locate(id,neighbourhood)     values (161366,'Sunnyside')
insert into locate(id,neighbourhood)     values (161394,'Williamsburg')
insert into locate(id,neighbourhood)     values (161996,'Harlem')
insert into locate(id,neighbourhood)     values (162493,'Williamsburg')
insert into locate(id,neighbourhood)     values (162508,'Crown Heights')
insert into locate(id,neighbourhood)     values (163627,'Williamsburg')
insert into locate(id,neighbourhood)     values (163809,'Harlem')
insert into locate(id,neighbourhood)     values (163814,'East Village')
insert into locate(id,neighbourhood)     values (163836,'Greenpoint')
insert into locate(id,neighbourhood)     values (164989,'SoHo')
insert into locate(id,neighbourhood)     values (165080,'Carroll Gardens')
insert into locate(id,neighbourhood)     values (165461,'Morningside Heights')
insert into locate(id,neighbourhood)     values (165824,'Sunnyside')
insert into locate(id,neighbourhood)     values (166006,'Upper West Side')
insert into locate(id,neighbourhood)     values (166172,'Bushwick')
insert into locate(id,neighbourhood)     values (166541,'Washington Heights')
insert into locate(id,neighbourhood)     values (166983,'Carroll Gardens')
insert into locate(id,neighbourhood)     values (167013,'Chelsea')
insert into locate(id,neighbourhood)     values (167017,'Park Slope')
insert into locate(id,neighbourhood)     values (167222,'Park Slope')
insert into locate(id,neighbourhood)     values (167482,'Upper West Side')
insert into locate(id,neighbourhood)     values (168084,'East Village')
insert into locate(id,neighbourhood)     values (168123,'South Slope')
insert into locate(id,neighbourhood)     values (168546,'East Harlem')
insert into locate(id,neighbourhood)     values (168810,'Upper West Side')
insert into locate(id,neighbourhood)     values (169002,'Harlem')
insert into locate(id,neighbourhood)     values (169152,'Bedford-Stuyvesant')
insert into locate(id,neighbourhood)     values (169306,'University Heights')
insert into locate(id,neighbourhood)     values (169464,'Williamsburg')
insert into locate(id,neighbourhood)     values (169483,'Gravesend')
insert into locate(id,neighbourhood)     values (170420,'East Harlem')
insert into locate(id,neighbourhood)     values (170761,'Fort Greene')
insert into locate(id,neighbourhood)     values (171776,'Harlem')
insert into locate(id,neighbourhood)     values (172700,'Lower East Side')
insert into locate(id,neighbourhood)     values (172870,'Harlem')
insert into locate(id,neighbourhood)     values (173072,'Harlem')
insert into locate(id,neighbourhood)     values (173151,'Greenpoint')
insert into locate(id,neighbourhood)     values (173742,'Gramercy')
insert into locate(id,neighbourhood)     values (174527,'Bushwick')
insert into locate(id,neighbourhood)     values (174966,'Upper West Side')
insert into locate(id,neighbourhood)     values (176135,'Crown Heights')
insert into locate(id,neighbourhood)     values (176653,'East Village')
insert into locate(id,neighbourhood)     values (176962,'Williamsburg')

In [61]:
#Delete all data in one table
#It can be useful when debugging.
mycursor.execute("delete from position")
db.commit()

In [60]:
#query
#example 1
mycursor.execute("select * from house")
myresult = mycursor.fetchall()

for x in myresult:
    print(x)

(2539, 'Clean & quiet apt home by the park', 40.6475, -73.9724, 'Private room', '149', 1, 9, '2018-10-19', 0.21, 6, 365)
(2595, 'Skylit Midtown Castle', 40.7536, -73.9838, 'Entire home/apt', '225', 1, 45, '2019-05-21', 0.38, 2, 355)
(3647, 'THE VILLAGE OF HARLEM....NEW YORK !', 40.809, -73.9419, 'Private room', '150', 3, 0, '0', 0.0, 1, 365)
(3831, 'Cozy Entire Floor of Brownstone', 40.6851, -73.9598, 'Entire home/apt', '89', 1, 270, '2019-07-05', 4.64, 1, 194)
(5022, 'Entire Apt: Spacious Studio/Loft by central park', 40.7985, -73.944, 'Entire home/apt', '80', 10, 9, '2018-11-19', 0.1, 1, 0)
(5099, 'Large Cozy 1 BR Apartment In Midtown East', 40.7477, -73.975, 'Entire home/apt', '200', 3, 74, '2019-06-22', 0.59, 1, 129)
(5121, 'BlissArtsSpace!', 40.6869, -73.956, 'Private room', '60', 45, 49, '2017-10-05', 0.4, 1, 0)
(5178, 'Large Furnished Room Near B way ', 40.7649, -73.9849, 'Private room', '79', 2, 430, '2019-06-24', 3.47, 1, 220)
(5203, 'Cozy Clean Guest Room - Family Apt', 40.8018, -73.9672, 'Private room', '79', 2, 118, '2017-07-21', 0.99, 1, 0)
(5238, 'Cute & Cozy Lower East Side 1 bdrm', 40.7134, -73.9904, 'Entire home/apt', '150', 1, 160, '2019-06-09', 1.33, 4, 188)
(5295, 'Beautiful 1br on Upper West Side', 40.8032, -73.9654, 'Entire home/apt', '135', 5, 53, '2019-06-22', 0.43, 1, 6)
(5441, 'Central Manhattan/near Broadway', 40.7608, -73.9887, 'Private room', '85', 2, 188, '2019-06-23', 1.5, 1, 39)
(5803, 'Lovely Room 1, Garden, Best Area, Legal rental', 40.6683, -73.9878, 'Private room', '89', 4, 167, '2019-06-24', 1.34, 3, 314)
(6021, 'Wonderful Guest Bedroom in Manhattan for SINGLES', 40.7983, -73.9611, 'Private room', '85', 2, 113, '2019-07-05', 0.91, 1, 333)
(6090, 'West Village Nest - Superhost', 40.7353, -74.0052, 'Entire home/apt', '120', 90, 27, '2018-10-31', 0.22, 1, 0)
(6848, 'Only 2 stops to Manhattan studio', 40.7084, -73.9535, 'Entire home/apt', '140', 2, 148, '2019-06-29', 1.2, 1, 46)
(7097, 'Perfect for Your Parents + Garden', 40.6917, -73.9718, 'Entire home/apt', '215', 2, 198, '2019-06-28', 1.72, 1, 321)
(7322, 'Chelsea Perfect', 40.7419, -73.995, 'Private room', '140', 1, 260, '2019-07-01', 2.12, 1, 12)
(7726, 'Hip Historic Brownstone Apartment with Backyard', 40.6759, -73.9469, 'Entire home/apt', '99', 3, 53, '2019-06-22', 4.44, 1, 21)
(7750, 'Huge 2 BR Upper East  Cental Park', 40.7968, -73.9487, 'Entire home/apt', '190', 7, 0, '0', 0.0, 2, 249)
(7801, 'Sweet and Spacious Brooklyn Loft', 40.7184, -73.9572, 'Entire home/apt', '299', 3, 9, '2011-12-28', 0.07, 1, 0)
(8024, 'CBG CtyBGd HelpsHaiti rm#1:1-4', 40.6807, -73.9771, 'Private room', '130', 2, 130, '2019-07-01', 1.09, 6, 347)
(8025, 'CBG Helps Haiti Room#2.5', 40.6799, -73.978, 'Private room', '80', 1, 39, '2019-01-01', 0.37, 6, 364)
(8110, 'CBG Helps Haiti Rm #2', 40.68, -73.9787, 'Private room', '110', 2, 71, '2019-07-02', 0.61, 6, 304)
(8490, 'MAISON DES SIRENES1,bohemian apartment', 40.6837, -73.9403, 'Entire home/apt', '120', 2, 88, '2019-06-19', 0.73, 2, 233)
(8505, 'Sunny Bedroom Across Prospect Park', 40.656, -73.9752, 'Private room', '60', 1, 19, '2019-06-23', 1.37, 2, 85)
(8700, 'Magnifique Suite au N de Manhattan - vue Cloitres', 40.8675, -73.9264, 'Private room', '80', 4, 0, '0', 0.0, 1, 0)
(9357, 'Midtown Pied-a-terre', 40.7672, -73.9853, 'Entire home/apt', '150', 10, 58, '2017-08-13', 0.49, 1, 75)
(9518, 'SPACIOUS, LOVELY FURNISHED MANHATTAN BEDROOM', 40.8648, -73.9211, 'Private room', '44', 3, 108, '2019-06-15', 1.11, 3, 311)
(9657, 'Modern 1 BR / NYC / EAST VILLAGE', 40.7292, -73.9854, 'Entire home/apt', '180', 14, 29, '2019-04-19', 0.24, 1, 67)
(9668, 'front room/double bed', 40.8224, -73.951, 'Private room', '50', 3, 242, '2019-06-01', 2.04, 3, 355)
(9704, 'Spacious 1 bedroom in luxe building', 40.813, -73.9547, 'Private room', '52', 2, 88, '2019-06-14', 1.42, 1, 255)
(9782, 'Loft in Williamsburg Area w/ Roof', 40.7222, -73.9376, 'Private room', '55', 4, 197, '2019-06-15', 1.65, 3, 284)
(9783, 'back room/bunk beds', 40.8213, -73.9532, 'Private room', '50', 3, 273, '2019-07-01', 2.37, 3, 359)
(10452, 'Large B&B Style rooms', 40.6831, -73.9547, 'Private room', '70', 1, 74, '2019-05-12', 0.66, 2, 269)
(10962, 'Lovely room 2 & garden; Best area, Legal rental', 40.6687, -73.9878, 'Private room', '89', 4, 168, '2019-06-21', 1.41, 3, 340)
(11452, 'Clean and Quiet in Brooklyn', 40.6888, -73.9431, 'Private room', '35', 60, 0, '0', 0.0, 1, 365)
(11708, 'Cute apt in artist s home', 40.7019, -73.9275, 'Entire home/apt', '85', 2, 231, '2019-06-22', 1.96, 2, 22)
(11943, 'Country space in the city', 40.637, -73.9633, 'Private room', '150', 1, 0, '0', 0.0, 1, 365)
(12048, 'LowerEastSide apt share shortterm 1', 40.714, -73.9892, 'Shared room', '40', 1, 214, '2019-07-05', 1.81, 4, 188)
(12192, 'ENJOY Downtown NYC!', 40.7229, -73.982, 'Private room', '68', 2, 245, '2019-06-21', 2.08, 2, 96)
(12299, 'Beautiful Sunny Park Slope Brooklyn', 40.6628, -73.9797, 'Entire home/apt', '120', 3, 15, '2019-05-27', 0.39, 1, 345)
(12303, '1bdr w private bath. in lofty apt', 40.6967, -73.9758, 'Private room', '120', 7, 25, '2018-09-30', 0.23, 1, 311)
(12318, 'West Side Retreat', 40.7901, -73.9793, 'Private room', '135', 4, 81, '2019-06-16', 0.69, 1, 273)
(12343, 'BEST BET IN HARLEM', 40.8117, -73.9448, 'Entire home/apt', '150', 7, 97, '2019-06-13', 0.84, 1, 309)
(12627, 'Entire apartment in central Brooklyn neighborhood.', 40.6594, -73.9624, 'Entire home/apt', '150', 29, 11, '2019-06-05', 0.49, 1, 95)
(12937, '1 Stop fr. Manhattan! Private Suite,Landmark Block', 40.7477, -73.9474, 'Private room', '130', 3, 248, '2019-07-01', 2.25, 1, 215)
(12940, 'Charming Brownstone 3 - Near PRATT', 40.6811, -73.9559, 'Entire home/apt', '110', 7, 61, '2019-05-25', 0.52, 1, 265)
(13050, 'bright and stylish duplex', 40.6855, -73.9409, 'Entire home/apt', '115', 3, 11, '2017-01-01', 0.1, 1, 0)
(13394, 'Fort Greene brownstone ', 40.6914, -73.9738, 'Private room', '80', 3, 135, '2019-06-17', 1.16, 2, 192)
(13808, 'Blue Room for 2 in Brownstone for $1350 monthly', 40.6804, -73.9393, 'Private room', '80', 1, 112, '2019-06-16', 1.01, 3, 251)
(14287, 'Cozy 1BD on Central Park West in New York City', 40.7864, -73.9701, 'Entire home/apt', '151', 2, 73, '2019-07-07', 0.63, 1, 302)
(14290, '* ORIGINAL BROOKLYN LOFT *', 40.7042, -73.9356, 'Entire home/apt', '228', 3, 82, '2019-05-17', 0.7, 1, 140)
(14314, 'Greenpoint Place...Has It All! ', 40.7351, -73.9539, 'Entire home/apt', '144', 2, 328, '2019-06-29', 2.82, 1, 234)
(14322, 'Beautiful Apartment in Manhattan!!!', 40.7396, -73.9807, 'Entire home/apt', '200', 7, 19, '2019-03-25', 0.22, 1, 257)
(14377, 'Williamsburg 1 bedroom Apartment', 40.7088, -73.9593, 'Entire home/apt', '150', 30, 105, '2019-06-22', 0.9, 1, 30)
(14991, 'Great Location, Manhattan Bedroom!', 40.72, -73.991, 'Private room', '110', 5, 19, '2019-05-18', 0.17, 1, 301)
(15220, 'Best Location in NYC! TIMES SQUARE!', 40.7553, -73.9929, 'Private room', '69', 2, 289, '2019-06-09', 2.49, 2, 294)
(15338, 'Room in Greenpoint Loft w/ Roof', 40.724, -73.9379, 'Private room', '49', 4, 138, '2019-06-04', 1.19, 3, 320)
(15341, '**Bright Nolita Apt w Doorman/Elevators/Gym**', 40.7221, -73.9977, 'Entire home/apt', '180', 30, 21, '2019-06-29', 0.3, 1, 154)
(15385, 'Very, very cozy place', 40.7118, -73.962, 'Private room', '80', 2, 42, '2019-06-30', 0.38, 1, 263)
(15396, 'Sunny & Spacious Chelsea Apartment', 40.7462, -73.9953, 'Entire home/apt', '375', 180, 5, '2018-11-03', 0.12, 1, 180)
(15711, '2 bedroom - Upper East Side-great for kids', 40.7706, -73.9527, 'Entire home/apt', '250', 2, 66, '2019-03-30', 0.57, 2, 231)
(16326, 'Comfortable 4-bedroom apt in family house.', 40.6781, -73.9643, 'Entire home/apt', '200', 30, 143, '2019-01-26', 1.33, 2, 297)
(16338, 'Double Room w Private Deck Clinton Hill Best Area', 40.69, -73.9679, 'Private room', '55', 7, 27, '2017-09-30', 0.23, 2, 292)
(16421, 'Your Heaven in Hells Kitchen', 40.7598, -73.9912, 'Private room', '52', 30, 191, '2019-05-16', 1.65, 1, 191)
(16458, 'Light-filled 2B duplex in the heart of Park Slope!', 40.6734, -73.9834, 'Entire home/apt', '225', 3, 4, '2017-09-24', 0.16, 1, 0)
(16580, 'Sunny, Modern room in East Village!', 40.7265, -73.979, 'Private room', '80', 1, 338, '2019-07-01', 4.72, 2, 72)
(16595, '*HAVEN LOFT - Entire Floor - Six Windows - Bricks*', 40.7093, -73.9679, 'Entire home/apt', '275', 1, 148, '2019-06-23', 1.4, 1, 362)
(16821, 'Large Room in Amazing East Village Apt', 40.723, -73.9847, 'Private room', '99', 1, 106, '2019-06-21', 1.26, 2, 336)
(16974, 'SpaHa Loft: Enormous and Bright', 40.8016, -73.9392, 'Entire home/apt', '225', 4, 190, '2019-06-23', 1.64, 1, 215)
(17037, 'Lovely EV Artist s Home', 40.7216, -73.9801, 'Entire home/apt', '230', 9, 49, '2018-05-14', 0.43, 1, 116)
(17092, 'Cool Room in Hell s Kitchen', 40.7634, -73.9886, 'Private room', '51', 7, 23, '2019-06-01', 0.43, 1, 88)
(17693, 'HARLEM, NEW YORK WELCOMES YOU!!', 40.8314, -73.9409, 'Private room', '65', 2, 49, '2019-06-18', 1.6, 2, 336)
(17747, 'BLUE TRIM GUEST HOUSE', 40.6835, -73.9637, 'Private room', '105', 2, 105, '2019-06-26', 0.92, 1, 304)
(18127, 'Charming East Village One Bedroom Flat', 40.7283, -73.988, 'Entire home/apt', '190', 5, 21, '2019-01-02', 0.2, 1, 224)
(18152, 'Manhattan Room', 40.7687, -73.9506, 'Private room', '200', 1, 142, '2019-07-06', 1.5, 1, 322)
(18198, 'Little King of Queens', 40.7504, -73.9033, 'Private room', '70', 30, 25, '2019-05-31', 0.22, 1, 324)
(18590, 'Fort Greene Retreat on the Park', 40.6932, -73.9727, 'Private room', '95', 3, 143, '2019-06-16', 1.28, 1, 132)
(18728, 'Beautiful Meatpacking District Loft', 40.7414, -74.002, 'Private room', '150', 3, 167, '2019-05-28', 1.65, 1, 295)
(18764, 'Cozy 2 BR in Williamsburg ', 40.7115, -73.9611, 'Private room', '145', 3, 61, '2019-04-22', 0.54, 4, 238)
(19159, 'Spacious luminous apt Upper West NYC', 40.8292, -73.9514, 'Entire home/apt', '110', 31, 54, '2019-03-23', 0.49, 1, 209)
(19169, 'Entire 2 Bedroom - Large & Sunny', 40.7185, -73.9889, 'Entire home/apt', '285', 5, 70, '2019-06-30', 0.62, 1, 328)
(19282, 'Sunny, Spacious Top Floor Haven', 40.654, -73.9632, 'Entire home/apt', '130', 6, 16, '2019-06-15', 0.15, 1, 38)
(19319, 'Private room Great Deal at Lower East Side', 40.7114, -73.9879, 'Private room', '94', 30, 94, '2019-04-08', 0.84, 1, 188)
(19601, 'perfect for a family or small group', 40.6972, -73.9927, 'Entire home/apt', '800', 1, 25, '2016-08-04', 0.24, 1, 7)
(19812, '2 bedroom Williamsburg Apt - Bedford L stop', 40.7183, -73.9575, 'Entire home/apt', '105', 3, 61, '2018-08-09', 0.53, 1, 272)
(20299, 'Oh glorious spring!', 40.7233, -73.9844, 'Private room', '60', 3, 194, '2019-06-30', 1.73, 1, 26)
(20300, 'Great Location for NYC', 40.7291, -73.9806, 'Private room', '50', 1, 2, '2016-02-14', 0.05, 1, 0)
(20611, 'Cozy Bedroom in Williamsburg 3 BR', 40.7116, -73.9622, 'Private room', '85', 3, 174, '2019-06-22', 1.54, 4, 288)
(20724, 'Sunny room+Pvte office in huge loft', 40.7003, -73.9383, 'Private room', '65', 4, 24, '2019-05-26', 0.28, 1, 317)
(20734, 'Spacious Prospect Heights Apartment', 40.6823, -73.9726, 'Entire home/apt', '131', 4, 166, '2019-06-27', 3.4, 1, 207)
(20755, 'Large Parlor Room, Landmark Home 1 block to PRATT', 40.6863, -73.966, 'Private room', '98', 7, 16, '2019-05-31', 0.2, 6, 185)
(20853, '2-bed brownstone duplex + garden', 40.6804, -73.9716, 'Entire home/apt', '250', 7, 21, '2019-05-21', 0.3, 1, 158)
(20913, 'Charming 1 bed GR8 WBurg LOCATION!', 40.7098, -73.9577, 'Entire home/apt', '100', 5, 168, '2018-07-22', 1.57, 1, 0)
(21293, 'Sunny Apartment in Artist Home', 40.7009, -73.9261, 'Entire home/apt', '105', 3, 118, '2019-06-18', 1.05, 2, 9)
(21456, 'Light-filled classic Central Park ', 40.7976, -73.9618, 'Entire home/apt', '140', 3, 81, '2019-07-07', 0.71, 1, 198)
(21644, 'Upper Manhattan, New York', 40.828, -73.9473, 'Private room', '89', 1, 1, '2018-10-09', 0.11, 1, 365)
(21794, 'COZY QUIET room 4 DOOGLERS!', 40.7401, -74.0027, 'Private room', '98', 30, 30, '2019-05-01', 0.27, 2, 364)
(22911, 'The Stuydio Modern and Light Filled', 40.6841, -73.9236, 'Entire home/apt', '125', 7, 139, '2018-10-28', 1.23, 2, 311)
(22918, 'loft bed - near transportation-15min to times sq', 40.8228, -73.9514, 'Private room', '60', 3, 11, '2019-01-03', 0.87, 3, 219)
(23135, 'House On Henry (3rd FLR Suite)', 40.6797, -74.0015, 'Entire home/apt', '175', 2, 233, '2019-06-24', 2.09, 3, 342)
(23501, 'Monkey Retreat Manhattan', 40.8393, -73.9428, 'Private room', '65', 2, 68, '2012-11-01', 0.6, 1, 312)
(23686, '2000 SF 3br 2bath West Village private  townhouse', 40.731, -74.0032, 'Entire home/apt', '500', 4, 46, '2019-05-18', 0.55, 2, 243)
(24143, 'Williamsburg—Steps To Subway, Private Bath&Balcony', 40.7133, -73.9418, 'Private room', '101', 3, 335, '2019-05-29', 3.02, 1, 152)
(24285, 'Beautiful Duplex Apartment', 40.6694, -73.9811, 'Entire home/apt', '220', 30, 88, '2018-11-02', 0.79, 1, 9)
(25235, 'Large 2 Bedroom Great for Groups!', 40.6837, -73.9238, 'Entire home/apt', '125', 90, 162, '2019-06-28', 1.46, 2, 137)
(25406, 'Modern Brooklyn Apt., August sublet', 40.7146, -73.9484, 'Entire home/apt', '80', 30, 29, '2018-05-26', 0.4, 1, 222)
(25696, '1,800 sq foot in luxury building', 40.8092, -73.9442, 'Private room', '100', 2, 170, '2019-06-23', 1.61, 1, 346)
(26012, 'Sunny 2-story Brooklyn townhouse w deck and garden', 40.6816, -73.9899, 'Entire home/apt', '200', 30, 19, '2017-03-17', 0.2, 1, 208)
(26362, 'Times Square, Safe, Clean and Cozy!', 40.7553, -73.9929, 'Private room', '59', 2, 334, '2019-06-16', 3.0, 2, 279)
(26520, 'Cozy Room #3, Landmark Home 1 Block to PRATT', 40.687, -73.9657, 'Private room', '125', 2, 19, '2019-06-02', 0.2, 6, 250)
(26559, 'Beautiful Apartment East Village', 40.7288, -73.9819, 'Entire home/apt', '140', 7, 12, '2017-12-11', 0.13, 1, 164)
(26785, 'Park Slope Green Guest House', 40.6685, -73.9891, 'Entire home/apt', '120', 30, 467, '2018-12-30', 4.22, 2, 192)
(26933, '2 BR / 2 Bath Duplex Apt with patio! East Village', 40.7254, -73.9816, 'Entire home/apt', '350', 2, 7, '2017-08-09', 0.06, 4, 298)
(26954, 'NYC fabulous views Manhattan s eye', 40.7429, -73.9801, 'Entire home/apt', '199', 5, 38, '2015-12-02', 0.38, 1, 260)
(26969, '2 story family home in Williamsburg', 40.7194, -73.9575, 'Entire home/apt', '325', 3, 324, '2019-06-23', 3.01, 1, 107)
(27006, 'Comfortable UWS 2-BD Family-Friendly Brownstone', 40.7782, -73.9764, 'Entire home/apt', '235', 6, 27, '2019-04-27', 0.27, 1, 199)
(27385, 'Great Large 1 BR apt  in East Village!', 40.7256, -73.9797, 'Entire home/apt', '225', 1, 115, '2019-06-07', 1.05, 4, 299)
(27531, 'Eveland Private Bed & Living Room w/ Own Entrance', 40.6683, -73.986, 'Private room', '99', 2, 354, '2019-05-20', 3.2, 3, 20)
(27644, 'Sugar Hill Rest Stop ', 40.8275, -73.9492, 'Entire home/apt', '170', 2, 195, '2019-07-01', 2.03, 1, 318)
(27659, '3 Story Town House in Park Slope', 40.665, -73.9792, 'Entire home/apt', '400', 2, 16, '2018-12-30', 0.24, 2, 216)
(27759, 'apartment next to Central park', 40.7784, -73.9756, 'Entire home/apt', '170', 7, 13, '2019-06-26', 0.12, 1, 224)
(27883, 'East Village Sanctuary', 40.7225, -73.9853, 'Entire home/apt', '100', 4, 25, '2011-12-10', 0.23, 1, 0)
(28321, 'Large 1  BR in a 3 BR Brooklyn apt. next to Q Trn.', 40.6559, -73.9605, 'Private room', '75', 2, 9, '2018-10-05', 0.08, 1, 324)
(28396, 'Modern Apt with Spectacular Views', 40.7192, -73.9647, 'Private room', '90', 1, 9, '2011-09-18', 0.08, 1, 245)
(28907, 'Garden studio in the Upper East Sid', 40.778, -73.9482, 'Entire home/apt', '150', 5, 21, '2017-08-15', 0.19, 1, 189)
(29012, 'Secluded Master Bedroom in Beautiful Huge Apt', 40.8588, -73.9313, 'Private room', '85', 15, 36, '2017-08-17', 0.33, 1, 307)
(29013, 'B & B Room 1', 40.6833, -73.9547, 'Private room', '70', 3, 63, '2019-05-14', 0.58, 2, 310)
(29455, 'ACCOMMODATIONS GALORE #1', 40.8162, -73.9489, 'Entire home/apt', '120', 3, 155, '2019-06-20', 1.42, 3, 213)
(29628, 'Sunny Room in New Condo', 40.6841, -73.9635, 'Private room', '89', 3, 260, '2019-07-03', 2.35, 1, 278)
(29683, 'Stylish & Sleek Apartment Near SoHo!', 40.7239, -73.9914, 'Entire home/apt', '185', 5, 73, '2019-06-25', 0.66, 1, 209)
(30031, 'NYC artists’ loft with roof deck', 40.7349, -73.9503, 'Private room', '50', 3, 193, '2019-05-20', 1.86, 1, 0)
(30927, 'Unique & Charming small 1br Apt. LES', 40.7134, -73.9886, 'Entire home/apt', '105', 3, 32, '2019-06-14', 0.29, 1, 16)
(31130, 'Most Central Location!', 40.7675, -73.984, 'Private room', '130', 2, 50, '2019-05-26', 0.45, 3, 234)
(31555, 'Luminous Beautiful West Village Studio', 40.7344, -74.003, 'Entire home/apt', '115', 29, 26, '2019-07-01', 0.25, 1, 12)
(31902, 'Sanctuary in East Flatbush', 40.6319, -73.9325, 'Private room', '77', 2, 2, '2019-01-01', 0.02, 1, 178)
(31994, 'Room with En Suite Bathroom & Deck', 40.6873, -73.9634, 'Private room', '76', 2, 426, '2019-06-24', 3.89, 3, 275)
(32023, 'FLAT MACDONOUGH', 40.683, -73.9366, 'Entire home/apt', '125', 3, 227, '2019-06-23', 2.09, 2, 163)
(32037, 'Huge Private  Floor at The Waverly', 40.6863, -73.9677, 'Private room', '135', 4, 84, '2019-07-01', 0.77, 3, 365)
(32100, 'Modern Greenpoint, Brooklyn Apt', 40.7341, -73.9535, 'Entire home/apt', '250', 29, 3, '2017-07-30', 0.03, 1, 34)
(32289, 'Sun-drenched, artsy modernist 1 BDRM duplex', 40.7156, -73.9483, 'Entire home/apt', '199', 3, 10, '2018-06-11', 0.1, 1, 280)
(32331, 'Sunny, Cobble Hill Apartment', 40.6857, -73.9918, 'Entire home/apt', '140', 2, 4, '2016-04-24', 0.04, 1, 0)
(32363, 'Fully Furnished Basement Apartment', 40.7403, -73.8317, 'Private room', '140', 2, 1, '2011-09-19', 0.01, 1, 1)
(32965, 'FLAT MACDONOUGH GARDEN', 40.6828, -73.9352, 'Entire home/apt', '115', 3, 124, '2019-06-20', 1.72, 2, 170)
(32969, 'Light filled Williamsburg Apartment', 40.716, -73.9394, 'Entire home/apt', '160', 3, 11, '2019-07-02', 0.11, 1, 188)
(33009, 'Retreat in Williamsburg', 40.7149, -73.9594, 'Entire home/apt', '195', 4, 240, '2019-06-17', 2.19, 1, 214)
(33014, 'NYC Zen', 40.7235, -73.9829, 'Entire home/apt', '195', 3, 30, '2019-06-17', 0.28, 1, 248)
(33223, 'Cozy BR in Wiliamsburg 3 Bedroom', 40.7117, -73.9609, 'Private room', '80', 3, 200, '2019-06-22', 1.86, 4, 262)
(34760, 'Sunny Room in Old Historical Brooklyn Townhouse', 40.691, -73.9731, 'Private room', '44', 8, 27, '2019-06-29', 1.05, 5, 280)
(35526, 'Sun Filled Classic West Village Apt', 40.7347, -74.001, 'Private room', '156', 4, 79, '2019-06-22', 0.74, 1, 307)
(36121, 'Lg Rm in Historic Prospect Heights', 40.6739, -73.9664, 'Private room', '85', 15, 9, '2013-05-10', 0.09, 1, 339)
(36133, 'Classic Artist Loft Williamsburg', 40.7154, -73.9606, 'Private room', '125', 3, 155, '2019-06-13', 1.61, 1, 1)
(36442, 'Great location. Spacious on PROSPECT PARK', 40.6741, -73.966, 'Entire home/apt', '115', 15, 4, '2018-08-27', 0.05, 1, 269)
(36647, 'Private Bdrm/Bathrm. New! Elevator!', 40.7929, -73.94, 'Private room', '69', 2, 34, '2017-05-29', 0.32, 1, 10)
(36703, 'Sunny, clean 1 bdrm in W. Village', 40.7323, -74.004, 'Entire home/apt', '225', 45, 134, '2019-03-31', 1.24, 1, 312)
(36934, 'Great location in Williamsburg', 40.7136, -73.964, 'Entire home/apt', '125', 6, 27, '2018-12-27', 0.25, 1, 189)
(38638, 'Light and Airy Upper East Side 1 BDR apartment', 40.7771, -73.9527, 'Entire home/apt', '219', 4, 126, '2019-06-26', 1.16, 2, 290)
(38663, 'Luxury Brownstone in Boerum Hill', 40.6856, -73.9809, 'Entire home/apt', '475', 3, 23, '2018-12-31', 0.27, 1, 230)
(39267, 'CENTRAL PARK LOFT all for YOU', 40.7746, -73.9532, 'Entire home/apt', '99', 1, 234, '2019-06-08', 2.6, 2, 164)
(39282, 'Indie-Chic Share In Williamsburg', 40.7109, -73.9505, 'Private room', '69', 4, 202, '2019-05-28', 1.86, 2, 53)
(39593, 'A room w/ a Manhattan view, longer stay', 40.7456, -73.9231, 'Private room', '79', 30, 28, '2019-04-12', 0.26, 1, 126)
(39704, 'Private, Large & Sunny 1BR w/W&D', 40.6831, -73.9466, 'Entire home/apt', '135', 2, 309, '2019-06-22', 2.86, 2, 3)

In [63]:
#example 2
mycursor.execute("select avg(price) from house")
myresult = mycursor.fetchall()

for x in myresult:
    print(x)

(152.3,)

In [64]:
#example 3
mycursor.execute("select count(*) from house where price>=50 and price<100")
myresult = mycursor.fetchall()

for x in myresult:
    print(x)

(156,)

In [67]:
#example 4
mycursor.execute("select * from house left join locate on house.id=locate.id")
myresult = mycursor.fetchall()

for x in myresult:
    print(x)

(2539, 'Clean & quiet apt home by the park', 40.6475, -73.9724, 'Private room', '149', 1, 9, '2018-10-19', 0.21, 6, 365, 2539, 'Kensington')
(2595, 'Skylit Midtown Castle', 40.7536, -73.9838, 'Entire home/apt', '225', 1, 45, '2019-05-21', 0.38, 2, 355, 2595, 'Midtown')
(3647, 'THE VILLAGE OF HARLEM....NEW YORK !', 40.809, -73.9419, 'Private room', '150', 3, 0, '0', 0.0, 1, 365, 3647, 'Harlem')
(3831, 'Cozy Entire Floor of Brownstone', 40.6851, -73.9598, 'Entire home/apt', '89', 1, 270, '2019-07-05', 4.64, 1, 194, 3831, 'Clinton Hill')
(5022, 'Entire Apt: Spacious Studio/Loft by central park', 40.7985, -73.944, 'Entire home/apt', '80', 10, 9, '2018-11-19', 0.1, 1, 0, 5022, 'East Harlem')
(5099, 'Large Cozy 1 BR Apartment In Midtown East', 40.7477, -73.975, 'Entire home/apt', '200', 3, 74, '2019-06-22', 0.59, 1, 129, 5099, 'Murray Hill')
(5121, 'BlissArtsSpace!', 40.6869, -73.956, 'Private room', '60', 45, 49, '2017-10-05', 0.4, 1, 0, 5121, 'Bedford-Stuyvesant')
(5178, 'Large Furnished Room Near B way ', 40.7649, -73.9849, 'Private room', '79', 2, 430, '2019-06-24', 3.47, 1, 220, 5178, 'Hell s Kitchen')
(5203, 'Cozy Clean Guest Room - Family Apt', 40.8018, -73.9672, 'Private room', '79', 2, 118, '2017-07-21', 0.99, 1, 0, 5203, 'Upper West Side')
(5238, 'Cute & Cozy Lower East Side 1 bdrm', 40.7134, -73.9904, 'Entire home/apt', '150', 1, 160, '2019-06-09', 1.33, 4, 188, 5238, 'Chinatown')
(5295, 'Beautiful 1br on Upper West Side', 40.8032, -73.9654, 'Entire home/apt', '135', 5, 53, '2019-06-22', 0.43, 1, 6, 5295, 'Upper West Side')
(5441, 'Central Manhattan/near Broadway', 40.7608, -73.9887, 'Private room', '85', 2, 188, '2019-06-23', 1.5, 1, 39, 5441, 'Hell s Kitchen')
(5803, 'Lovely Room 1, Garden, Best Area, Legal rental', 40.6683, -73.9878, 'Private room', '89', 4, 167, '2019-06-24', 1.34, 3, 314, 5803, 'South Slope')
(6021, 'Wonderful Guest Bedroom in Manhattan for SINGLES', 40.7983, -73.9611, 'Private room', '85', 2, 113, '2019-07-05', 0.91, 1, 333, 6021, 'Upper West Side')
(6090, 'West Village Nest - Superhost', 40.7353, -74.0052, 'Entire home/apt', '120', 90, 27, '2018-10-31', 0.22, 1, 0, 6090, 'West Village')
(6848, 'Only 2 stops to Manhattan studio', 40.7084, -73.9535, 'Entire home/apt', '140', 2, 148, '2019-06-29', 1.2, 1, 46, 6848, 'Williamsburg')
(7097, 'Perfect for Your Parents + Garden', 40.6917, -73.9718, 'Entire home/apt', '215', 2, 198, '2019-06-28', 1.72, 1, 321, 7097, 'Fort Greene')
(7322, 'Chelsea Perfect', 40.7419, -73.995, 'Private room', '140', 1, 260, '2019-07-01', 2.12, 1, 12, 7322, 'Chelsea')
(7726, 'Hip Historic Brownstone Apartment with Backyard', 40.6759, -73.9469, 'Entire home/apt', '99', 3, 53, '2019-06-22', 4.44, 1, 21, 7726, 'Crown Heights')
(7750, 'Huge 2 BR Upper East  Cental Park', 40.7968, -73.9487, 'Entire home/apt', '190', 7, 0, '0', 0.0, 2, 249, 7750, 'East Harlem')
(7801, 'Sweet and Spacious Brooklyn Loft', 40.7184, -73.9572, 'Entire home/apt', '299', 3, 9, '2011-12-28', 0.07, 1, 0, 7801, 'Williamsburg')
(8024, 'CBG CtyBGd HelpsHaiti rm#1:1-4', 40.6807, -73.9771, 'Private room', '130', 2, 130, '2019-07-01', 1.09, 6, 347, 8024, 'Park Slope')
(8025, 'CBG Helps Haiti Room#2.5', 40.6799, -73.978, 'Private room', '80', 1, 39, '2019-01-01', 0.37, 6, 364, 8025, 'Park Slope')
(8110, 'CBG Helps Haiti Rm #2', 40.68, -73.9787, 'Private room', '110', 2, 71, '2019-07-02', 0.61, 6, 304, 8110, 'Park Slope')
(8490, 'MAISON DES SIRENES1,bohemian apartment', 40.6837, -73.9403, 'Entire home/apt', '120', 2, 88, '2019-06-19', 0.73, 2, 233, 8490, 'Bedford-Stuyvesant')
(8505, 'Sunny Bedroom Across Prospect Park', 40.656, -73.9752, 'Private room', '60', 1, 19, '2019-06-23', 1.37, 2, 85, 8505, 'Windsor Terrace')
(8700, 'Magnifique Suite au N de Manhattan - vue Cloitres', 40.8675, -73.9264, 'Private room', '80', 4, 0, '0', 0.0, 1, 0, 8700, 'Inwood')
(9357, 'Midtown Pied-a-terre', 40.7672, -73.9853, 'Entire home/apt', '150', 10, 58, '2017-08-13', 0.49, 1, 75, 9357, 'Hell s Kitchen')
(9518, 'SPACIOUS, LOVELY FURNISHED MANHATTAN BEDROOM', 40.8648, -73.9211, 'Private room', '44', 3, 108, '2019-06-15', 1.11, 3, 311, 9518, 'Inwood')
(9657, 'Modern 1 BR / NYC / EAST VILLAGE', 40.7292, -73.9854, 'Entire home/apt', '180', 14, 29, '2019-04-19', 0.24, 1, 67, 9657, 'East Village')
(9668, 'front room/double bed', 40.8224, -73.951, 'Private room', '50', 3, 242, '2019-06-01', 2.04, 3, 355, 9668, 'Harlem')
(9704, 'Spacious 1 bedroom in luxe building', 40.813, -73.9547, 'Private room', '52', 2, 88, '2019-06-14', 1.42, 1, 255, 9704, 'Harlem')
(9782, 'Loft in Williamsburg Area w/ Roof', 40.7222, -73.9376, 'Private room', '55', 4, 197, '2019-06-15', 1.65, 3, 284, 9782, 'Greenpoint')
(9783, 'back room/bunk beds', 40.8213, -73.9532, 'Private room', '50', 3, 273, '2019-07-01', 2.37, 3, 359, 9783, 'Harlem')
(10452, 'Large B&B Style rooms', 40.6831, -73.9547, 'Private room', '70', 1, 74, '2019-05-12', 0.66, 2, 269, 10452, 'Bedford-Stuyvesant')
(10962, 'Lovely room 2 & garden; Best area, Legal rental', 40.6687, -73.9878, 'Private room', '89', 4, 168, '2019-06-21', 1.41, 3, 340, 10962, 'South Slope')
(11452, 'Clean and Quiet in Brooklyn', 40.6888, -73.9431, 'Private room', '35', 60, 0, '0', 0.0, 1, 365, 11452, 'Bedford-Stuyvesant')
(11708, 'Cute apt in artist s home', 40.7019, -73.9275, 'Entire home/apt', '85', 2, 231, '2019-06-22', 1.96, 2, 22, 11708, 'Bushwick')
(11943, 'Country space in the city', 40.637, -73.9633, 'Private room', '150', 1, 0, '0', 0.0, 1, 365, 11943, 'Flatbush')
(12048, 'LowerEastSide apt share shortterm 1', 40.714, -73.9892, 'Shared room', '40', 1, 214, '2019-07-05', 1.81, 4, 188, 12048, 'Lower East Side')
(12192, 'ENJOY Downtown NYC!', 40.7229, -73.982, 'Private room', '68', 2, 245, '2019-06-21', 2.08, 2, 96, 12192, 'East Village')
(12299, 'Beautiful Sunny Park Slope Brooklyn', 40.6628, -73.9797, 'Entire home/apt', '120', 3, 15, '2019-05-27', 0.39, 1, 345, 12299, 'South Slope')
(12303, '1bdr w private bath. in lofty apt', 40.6967, -73.9758, 'Private room', '120', 7, 25, '2018-09-30', 0.23, 1, 311, 12303, 'Fort Greene')
(12318, 'West Side Retreat', 40.7901, -73.9793, 'Private room', '135', 4, 81, '2019-06-16', 0.69, 1, 273, 12318, 'Upper West Side')
(12343, 'BEST BET IN HARLEM', 40.8117, -73.9448, 'Entire home/apt', '150', 7, 97, '2019-06-13', 0.84, 1, 309, 12343, 'Harlem')
(12627, 'Entire apartment in central Brooklyn neighborhood.', 40.6594, -73.9624, 'Entire home/apt', '150', 29, 11, '2019-06-05', 0.49, 1, 95, 12627, 'Prospect-Lefferts Gardens')
(12937, '1 Stop fr. Manhattan! Private Suite,Landmark Block', 40.7477, -73.9474, 'Private room', '130', 3, 248, '2019-07-01', 2.25, 1, 215, 12937, 'Long Island City')
(12940, 'Charming Brownstone 3 - Near PRATT', 40.6811, -73.9559, 'Entire home/apt', '110', 7, 61, '2019-05-25', 0.52, 1, 265, 12940, 'Bedford-Stuyvesant')
(13050, 'bright and stylish duplex', 40.6855, -73.9409, 'Entire home/apt', '115', 3, 11, '2017-01-01', 0.1, 1, 0, 13050, 'Bedford-Stuyvesant')
(13394, 'Fort Greene brownstone ', 40.6914, -73.9738, 'Private room', '80', 3, 135, '2019-06-17', 1.16, 2, 192, 13394, 'Fort Greene')
(13808, 'Blue Room for 2 in Brownstone for $1350 monthly', 40.6804, -73.9393, 'Private room', '80', 1, 112, '2019-06-16', 1.01, 3, 251, 13808, 'Bedford-Stuyvesant')
(14287, 'Cozy 1BD on Central Park West in New York City', 40.7864, -73.9701, 'Entire home/apt', '151', 2, 73, '2019-07-07', 0.63, 1, 302, 14287, 'Upper West Side')
(14290, '* ORIGINAL BROOKLYN LOFT *', 40.7042, -73.9356, 'Entire home/apt', '228', 3, 82, '2019-05-17', 0.7, 1, 140, 14290, 'Williamsburg')
(14314, 'Greenpoint Place...Has It All! ', 40.7351, -73.9539, 'Entire home/apt', '144', 2, 328, '2019-06-29', 2.82, 1, 234, 14314, 'Greenpoint')
(14322, 'Beautiful Apartment in Manhattan!!!', 40.7396, -73.9807, 'Entire home/apt', '200', 7, 19, '2019-03-25', 0.22, 1, 257, 14322, 'Kips Bay')
(14377, 'Williamsburg 1 bedroom Apartment', 40.7088, -73.9593, 'Entire home/apt', '150', 30, 105, '2019-06-22', 0.9, 1, 30, 14377, 'Williamsburg')
(14991, 'Great Location, Manhattan Bedroom!', 40.72, -73.991, 'Private room', '110', 5, 19, '2019-05-18', 0.17, 1, 301, 14991, 'Lower East Side')
(15220, 'Best Location in NYC! TIMES SQUARE!', 40.7553, -73.9929, 'Private room', '69', 2, 289, '2019-06-09', 2.49, 2, 294, 15220, 'Hell s Kitchen')
(15338, 'Room in Greenpoint Loft w/ Roof', 40.724, -73.9379, 'Private room', '49', 4, 138, '2019-06-04', 1.19, 3, 320, 15338, 'Greenpoint')
(15341, '**Bright Nolita Apt w Doorman/Elevators/Gym**', 40.7221, -73.9977, 'Entire home/apt', '180', 30, 21, '2019-06-29', 0.3, 1, 154, 15341, 'SoHo')
(15385, 'Very, very cozy place', 40.7118, -73.962, 'Private room', '80', 2, 42, '2019-06-30', 0.38, 1, 263, 15385, 'Williamsburg')
(15396, 'Sunny & Spacious Chelsea Apartment', 40.7462, -73.9953, 'Entire home/apt', '375', 180, 5, '2018-11-03', 0.12, 1, 180, 15396, 'Chelsea')
(15711, '2 bedroom - Upper East Side-great for kids', 40.7706, -73.9527, 'Entire home/apt', '250', 2, 66, '2019-03-30', 0.57, 2, 231, 15711, 'Upper East Side')
(16326, 'Comfortable 4-bedroom apt in family house.', 40.6781, -73.9643, 'Entire home/apt', '200', 30, 143, '2019-01-26', 1.33, 2, 297, 16326, 'Prospect Heights')
(16338, 'Double Room w Private Deck Clinton Hill Best Area', 40.69, -73.9679, 'Private room', '55', 7, 27, '2017-09-30', 0.23, 2, 292, 16338, 'Clinton Hill')
(16421, 'Your Heaven in Hells Kitchen', 40.7598, -73.9912, 'Private room', '52', 30, 191, '2019-05-16', 1.65, 1, 191, 16421, 'Hell s Kitchen')
(16458, 'Light-filled 2B duplex in the heart of Park Slope!', 40.6734, -73.9834, 'Entire home/apt', '225', 3, 4, '2017-09-24', 0.16, 1, 0, 16458, 'Park Slope')
(16580, 'Sunny, Modern room in East Village!', 40.7265, -73.979, 'Private room', '80', 1, 338, '2019-07-01', 4.72, 2, 72, 16580, 'East Village')
(16595, '*HAVEN LOFT - Entire Floor - Six Windows - Bricks*', 40.7093, -73.9679, 'Entire home/apt', '275', 1, 148, '2019-06-23', 1.4, 1, 362, 16595, 'Williamsburg')
(16821, 'Large Room in Amazing East Village Apt', 40.723, -73.9847, 'Private room', '99', 1, 106, '2019-06-21', 1.26, 2, 336, 16821, 'East Village')
(16974, 'SpaHa Loft: Enormous and Bright', 40.8016, -73.9392, 'Entire home/apt', '225', 4, 190, '2019-06-23', 1.64, 1, 215, 16974, 'East Harlem')
(17037, 'Lovely EV Artist s Home', 40.7216, -73.9801, 'Entire home/apt', '230', 9, 49, '2018-05-14', 0.43, 1, 116, 17037, 'East Village')
(17092, 'Cool Room in Hell s Kitchen', 40.7634, -73.9886, 'Private room', '51', 7, 23, '2019-06-01', 0.43, 1, 88, 17092, 'Hell s Kitchen')
(17693, 'HARLEM, NEW YORK WELCOMES YOU!!', 40.8314, -73.9409, 'Private room', '65', 2, 49, '2019-06-18', 1.6, 2, 336, 17693, 'Washington Heights')
(17747, 'BLUE TRIM GUEST HOUSE', 40.6835, -73.9637, 'Private room', '105', 2, 105, '2019-06-26', 0.92, 1, 304, 17747, 'Clinton Hill')
(18127, 'Charming East Village One Bedroom Flat', 40.7283, -73.988, 'Entire home/apt', '190', 5, 21, '2019-01-02', 0.2, 1, 224, 18127, 'East Village')
(18152, 'Manhattan Room', 40.7687, -73.9506, 'Private room', '200', 1, 142, '2019-07-06', 1.5, 1, 322, 18152, 'Upper East Side')
(18198, 'Little King of Queens', 40.7504, -73.9033, 'Private room', '70', 30, 25, '2019-05-31', 0.22, 1, 324, 18198, 'Woodside')
(18590, 'Fort Greene Retreat on the Park', 40.6932, -73.9727, 'Private room', '95', 3, 143, '2019-06-16', 1.28, 1, 132, 18590, 'Fort Greene')
(18728, 'Beautiful Meatpacking District Loft', 40.7414, -74.002, 'Private room', '150', 3, 167, '2019-05-28', 1.65, 1, 295, 18728, 'Chelsea')
(18764, 'Cozy 2 BR in Williamsburg ', 40.7115, -73.9611, 'Private room', '145', 3, 61, '2019-04-22', 0.54, 4, 238, 18764, 'Williamsburg')
(19159, 'Spacious luminous apt Upper West NYC', 40.8292, -73.9514, 'Entire home/apt', '110', 31, 54, '2019-03-23', 0.49, 1, 209, 19159, 'Harlem')
(19169, 'Entire 2 Bedroom - Large & Sunny', 40.7185, -73.9889, 'Entire home/apt', '285', 5, 70, '2019-06-30', 0.62, 1, 328, 19169, 'Lower East Side')
(19282, 'Sunny, Spacious Top Floor Haven', 40.654, -73.9632, 'Entire home/apt', '130', 6, 16, '2019-06-15', 0.15, 1, 38, 19282, 'Flatbush')
(19319, 'Private room Great Deal at Lower East Side', 40.7114, -73.9879, 'Private room', '94', 30, 94, '2019-04-08', 0.84, 1, 188, 19319, 'Lower East Side')
(19601, 'perfect for a family or small group', 40.6972, -73.9927, 'Entire home/apt', '800', 1, 25, '2016-08-04', 0.24, 1, 7, 19601, 'Brooklyn Heights')
(19812, '2 bedroom Williamsburg Apt - Bedford L stop', 40.7183, -73.9575, 'Entire home/apt', '105', 3, 61, '2018-08-09', 0.53, 1, 272, 19812, 'Williamsburg')
(20299, 'Oh glorious spring!', 40.7233, -73.9844, 'Private room', '60', 3, 194, '2019-06-30', 1.73, 1, 26, 20299, 'East Village')
(20300, 'Great Location for NYC', 40.7291, -73.9806, 'Private room', '50', 1, 2, '2016-02-14', 0.05, 1, 0, 20300, 'East Village')
(20611, 'Cozy Bedroom in Williamsburg 3 BR', 40.7116, -73.9622, 'Private room', '85', 3, 174, '2019-06-22', 1.54, 4, 288, 20611, 'Williamsburg')
(20724, 'Sunny room+Pvte office in huge loft', 40.7003, -73.9383, 'Private room', '65', 4, 24, '2019-05-26', 0.28, 1, 317, 20724, 'Bushwick')
(20734, 'Spacious Prospect Heights Apartment', 40.6823, -73.9726, 'Entire home/apt', '131', 4, 166, '2019-06-27', 3.4, 1, 207, 20734, 'Prospect Heights')
(20755, 'Large Parlor Room, Landmark Home 1 block to PRATT', 40.6863, -73.966, 'Private room', '98', 7, 16, '2019-05-31', 0.2, 6, 185, 20755, 'Clinton Hill')
(20853, '2-bed brownstone duplex + garden', 40.6804, -73.9716, 'Entire home/apt', '250', 7, 21, '2019-05-21', 0.3, 1, 158, 20853, 'Prospect Heights')
(20913, 'Charming 1 bed GR8 WBurg LOCATION!', 40.7098, -73.9577, 'Entire home/apt', '100', 5, 168, '2018-07-22', 1.57, 1, 0, 20913, 'Williamsburg')
(21293, 'Sunny Apartment in Artist Home', 40.7009, -73.9261, 'Entire home/apt', '105', 3, 118, '2019-06-18', 1.05, 2, 9, 21293, 'Bushwick')
(21456, 'Light-filled classic Central Park ', 40.7976, -73.9618, 'Entire home/apt', '140', 3, 81, '2019-07-07', 0.71, 1, 198, 21456, 'Upper West Side')
(21644, 'Upper Manhattan, New York', 40.828, -73.9473, 'Private room', '89', 1, 1, '2018-10-09', 0.11, 1, 365, 21644, 'Harlem')
(21794, 'COZY QUIET room 4 DOOGLERS!', 40.7401, -74.0027, 'Private room', '98', 30, 30, '2019-05-01', 0.27, 2, 364, 21794, 'Chelsea')
(22911, 'The Stuydio Modern and Light Filled', 40.6841, -73.9236, 'Entire home/apt', '125', 7, 139, '2018-10-28', 1.23, 2, 311, 22911, 'Bedford-Stuyvesant')
(22918, 'loft bed - near transportation-15min to times sq', 40.8228, -73.9514, 'Private room', '60', 3, 11, '2019-01-03', 0.87, 3, 219, 22918, 'Harlem')
(23135, 'House On Henry (3rd FLR Suite)', 40.6797, -74.0015, 'Entire home/apt', '175', 2, 233, '2019-06-24', 2.09, 3, 342, 23135, 'Carroll Gardens')
(23501, 'Monkey Retreat Manhattan', 40.8393, -73.9428, 'Private room', '65', 2, 68, '2012-11-01', 0.6, 1, 312, 23501, 'Washington Heights')
(23686, '2000 SF 3br 2bath West Village private  townhouse', 40.731, -74.0032, 'Entire home/apt', '500', 4, 46, '2019-05-18', 0.55, 2, 243, 23686, 'West Village')
(24143, 'Williamsburg—Steps To Subway, Private Bath&Balcony', 40.7133, -73.9418, 'Private room', '101', 3, 335, '2019-05-29', 3.02, 1, 152, 24143, 'Williamsburg')
(24285, 'Beautiful Duplex Apartment', 40.6694, -73.9811, 'Entire home/apt', '220', 30, 88, '2018-11-02', 0.79, 1, 9, 24285, 'Park Slope')
(25235, 'Large 2 Bedroom Great for Groups!', 40.6837, -73.9238, 'Entire home/apt', '125', 90, 162, '2019-06-28', 1.46, 2, 137, 25235, 'Bedford-Stuyvesant')
(25406, 'Modern Brooklyn Apt., August sublet', 40.7146, -73.9484, 'Entire home/apt', '80', 30, 29, '2018-05-26', 0.4, 1, 222, 25406, 'Williamsburg')
(25696, '1,800 sq foot in luxury building', 40.8092, -73.9442, 'Private room', '100', 2, 170, '2019-06-23', 1.61, 1, 346, 25696, 'Harlem')
(26012, 'Sunny 2-story Brooklyn townhouse w deck and garden', 40.6816, -73.9899, 'Entire home/apt', '200', 30, 19, '2017-03-17', 0.2, 1, 208, 26012, 'Gowanus')
(26362, 'Times Square, Safe, Clean and Cozy!', 40.7553, -73.9929, 'Private room', '59', 2, 334, '2019-06-16', 3.0, 2, 279, 26362, 'Hell s Kitchen')
(26520, 'Cozy Room #3, Landmark Home 1 Block to PRATT', 40.687, -73.9657, 'Private room', '125', 2, 19, '2019-06-02', 0.2, 6, 250, 26520, 'Clinton Hill')
(26559, 'Beautiful Apartment East Village', 40.7288, -73.9819, 'Entire home/apt', '140', 7, 12, '2017-12-11', 0.13, 1, 164, 26559, 'East Village')
(26785, 'Park Slope Green Guest House', 40.6685, -73.9891, 'Entire home/apt', '120', 30, 467, '2018-12-30', 4.22, 2, 192, 26785, 'South Slope')
(26933, '2 BR / 2 Bath Duplex Apt with patio! East Village', 40.7254, -73.9816, 'Entire home/apt', '350', 2, 7, '2017-08-09', 0.06, 4, 298, 26933, 'East Village')
(26954, 'NYC fabulous views Manhattan s eye', 40.7429, -73.9801, 'Entire home/apt', '199', 5, 38, '2015-12-02', 0.38, 1, 260, 26954, 'Kips Bay')
(26969, '2 story family home in Williamsburg', 40.7194, -73.9575, 'Entire home/apt', '325', 3, 324, '2019-06-23', 3.01, 1, 107, 26969, 'Williamsburg')
(27006, 'Comfortable UWS 2-BD Family-Friendly Brownstone', 40.7782, -73.9764, 'Entire home/apt', '235', 6, 27, '2019-04-27', 0.27, 1, 199, 27006, 'Upper West Side')
(27385, 'Great Large 1 BR apt  in East Village!', 40.7256, -73.9797, 'Entire home/apt', '225', 1, 115, '2019-06-07', 1.05, 4, 299, 27385, 'East Village')
(27531, 'Eveland Private Bed & Living Room w/ Own Entrance', 40.6683, -73.986, 'Private room', '99', 2, 354, '2019-05-20', 3.2, 3, 20, 27531, 'South Slope')
(27644, 'Sugar Hill Rest Stop ', 40.8275, -73.9492, 'Entire home/apt', '170', 2, 195, '2019-07-01', 2.03, 1, 318, 27644, 'Harlem')
(27659, '3 Story Town House in Park Slope', 40.665, -73.9792, 'Entire home/apt', '400', 2, 16, '2018-12-30', 0.24, 2, 216, 27659, 'South Slope')
(27759, 'apartment next to Central park', 40.7784, -73.9756, 'Entire home/apt', '170', 7, 13, '2019-06-26', 0.12, 1, 224, 27759, 'Upper West Side')
(27883, 'East Village Sanctuary', 40.7225, -73.9853, 'Entire home/apt', '100', 4, 25, '2011-12-10', 0.23, 1, 0, 27883, 'East Village')
(28321, 'Large 1  BR in a 3 BR Brooklyn apt. next to Q Trn.', 40.6559, -73.9605, 'Private room', '75', 2, 9, '2018-10-05', 0.08, 1, 324, 28321, 'Prospect-Lefferts Gardens')
(28396, 'Modern Apt with Spectacular Views', 40.7192, -73.9647, 'Private room', '90', 1, 9, '2011-09-18', 0.08, 1, 245, 28396, 'Williamsburg')
(28907, 'Garden studio in the Upper East Sid', 40.778, -73.9482, 'Entire home/apt', '150', 5, 21, '2017-08-15', 0.19, 1, 189, 28907, 'Upper East Side')
(29012, 'Secluded Master Bedroom in Beautiful Huge Apt', 40.8588, -73.9313, 'Private room', '85', 15, 36, '2017-08-17', 0.33, 1, 307, 29012, 'Washington Heights')
(29013, 'B & B Room 1', 40.6833, -73.9547, 'Private room', '70', 3, 63, '2019-05-14', 0.58, 2, 310, 29013, 'Bedford-Stuyvesant')
(29455, 'ACCOMMODATIONS GALORE #1', 40.8162, -73.9489, 'Entire home/apt', '120', 3, 155, '2019-06-20', 1.42, 3, 213, 29455, 'Harlem')
(29628, 'Sunny Room in New Condo', 40.6841, -73.9635, 'Private room', '89', 3, 260, '2019-07-03', 2.35, 1, 278, 29628, 'Clinton Hill')
(29683, 'Stylish & Sleek Apartment Near SoHo!', 40.7239, -73.9914, 'Entire home/apt', '185', 5, 73, '2019-06-25', 0.66, 1, 209, 29683, 'East Village')
(30031, 'NYC artists’ loft with roof deck', 40.7349, -73.9503, 'Private room', '50', 3, 193, '2019-05-20', 1.86, 1, 0, 30031, 'Greenpoint')
(30927, 'Unique & Charming small 1br Apt. LES', 40.7134, -73.9886, 'Entire home/apt', '105', 3, 32, '2019-06-14', 0.29, 1, 16, 30927, 'Lower East Side')
(31130, 'Most Central Location!', 40.7675, -73.984, 'Private room', '130', 2, 50, '2019-05-26', 0.45, 3, 234, 31130, 'Hell s Kitchen')
(31555, 'Luminous Beautiful West Village Studio', 40.7344, -74.003, 'Entire home/apt', '115', 29, 26, '2019-07-01', 0.25, 1, 12, 31555, 'West Village')
(31902, 'Sanctuary in East Flatbush', 40.6319, -73.9325, 'Private room', '77', 2, 2, '2019-01-01', 0.02, 1, 178, 31902, 'Flatlands')

In [69]:
#example 5
mycursor.execute("select neighbourhood_group,count(*) \
                 from house left join locate on house.id=locate.id \
                 left join position on locate.neighbourhood=position.neighbourhood \
                 group by neighbourhood_group")
myresult = mycursor.fetchall()

for x in myresult:
    print(x)

(None, 14)
('Bronx', 7)
('Brooklyn', 237)
('Manhattan', 215)
('Queens', 22)
('Staten Island', 5)

In [70]:
#example 6
mycursor.execute("select neighbourhood_group,avg(price) \
                 from house left join locate on house.id=locate.id \
                 left join position on locate.neighbourhood=position.neighbourhood \
                 group by neighbourhood_group")
myresult = mycursor.fetchall()

for x in myresult:
    print(x)

(None, 123.92857142857143)
('Bronx', 69.14285714285714)
('Brooklyn', 147.76371308016877)
('Manhattan', 168.46976744186045)
('Queens', 112.45454545454545)
('Staten Island', 43.2)